### ISSUE TITLE
Some API docs not wokring

### ISSUE THREAD

**Issue by kenborge** [js-data/js-data#102]
Here are some api documentation pages i found that are not working:
http://www.js-data.io/v1.6.0/docs/dsejectAll
http://www.js-data.io/v1.6.0/docs/dschangeHistory
http://www.js-data.io/v1.6.0/docs/dscreateInstance
http://www.js-data.io/v1.6.0/docs/dsdefineResource
http://www.js-data.io/v1.6.0/docs/dshasChanges
http://www.js-data.io/v1.6.0/docs/dslastModified
http://www.js-data.io/v1.6.0/docs/dslastSaved
http://www.js-data.io/v1.6.0/docs/dslinkAll
http://www.js-data.io/v1.6.0/docs/dslinkInverse
http://www.js-data.io/v1.6.0/docs/dsunlinkInverse
http://www.js-data.io/v1.6.0/docs/dsdestroyAll
http://www.js-data.io/v1.6.0/docs/dsfindAll
http://www.js-data.io/v1.6.0/docs/dsloadRelations
http://www.js-data.io/v1.6.0/docs/dsupdateAll

Found them trying to follow the links here: http://www.js-data.io/v1.6.0/docs/ds

**Comment by jmdobry** [comment]
The links should be fixed now. Thanks for the catch.
