### ISSUE TITLE
phantomjs and lastmodified

### ISSUE THREAD

**Issue by kenborge** [js-data/js-data#103]
I'm having an issue with lastmodified changing differently between chrome and phantomjs. It seems like changing a property of a resource in code changes the lastmodified of that resource when running with phantomjs, but it does not change when running in chrome(running karma with phantomjs or chrome).

This causes binds to trigger at different times with phantomjs then with chrome

**Comment by jmdobry** [comment]
This is because Chrome has native support for `Object.observe`, while PhantomJS must used the polyfill in js-data. Chrome delivers changes after an indeterminate amount of time. You actually have a little more control over when changes are fired in PhantomJS because you can call `DS#digest()`, which is also plugged into your app's $digest cycles if you're using js-data-angular. So, timing of change detection will be slightly different between the browsers.

**Comment by kenborge** [comment]
It didn't seem like just different timing in my case hmm.it seemed like in
Chrome the watch didn't trigger at all but in Phantom it did

**Comment by jmdobry** [comment]
Could you create a plunker that I can view in Chrome that duplicates the issue?

**Comment by kenborge** [comment]
Sure. Here http://plnkr.co/edit/EerX1ACns5oWQkblYFcj

I run this in chrome i get:
![screen shot 2015-04-02 at 15 54 28](https://cloud.githubusercontent.com/assets/599468/6965286/9816ff82-d950-11e4-9c24-fbe8a6b36a0e.png)

In safari it seems to work:
![screen shot 2015-04-02 at 15 55 18](https://cloud.githubusercontent.com/assets/599468/6965304/bdb064b8-d950-11e4-95ed-90e1127e3d05.png)

And in phantom:
![screen shot 2015-04-02 at 15 55 27](https://cloud.githubusercontent.com/assets/599468/6965313/c747a842-d950-11e4-975b-d112ed532f23.png)

**Comment by jmdobry** [comment]
In your plunker you're changing `foo1.test` to `2` _after_ 1000ms and then immediately printing the lastModified timestamp of the item. If you move the line `foo1.test = 2` outside of the `setTimeout` you should see that the lastModified timestamp does change in Chrome. In fact, the following should work:

```js
var Foo = store.defineResource('foo');
var foo = Foo.inject({ id: 1, test: 1 });
var originalTimestamp = Foo.lastModified(1);
foo.test = 2;
setTimeout(function () {
  originalTimestamp === Foo.lastModified(1); // false
}, 30);
```

**Comment by kenborge** [comment]
I see! I refactored the code where the issue actually happened so can't reproduce it anymore. Will close this since it could have been something else that was wrong. Will keep an eye on it
