### ISSUE TITLE
Switch to property accessors (getter/setter) for relations links.

### ISSUE THREAD

**Issue by jmdobry** [js-data/js-data#107]
This eliminates the (potentially) expensive computation needed to link relations upon injection, which links are also prone to becoming stale. Instead, computation is postponed until an item's relation is accessed. Property accessors (getters/setters) will pull the relations dynamically from the data store, and thus always be up-to-date. 

This will also allow for fine grain control over which relation links are available on which items. e.g., disable relation link property accessors entirely, for a single resource, or for a single relation. Perhaps one might want to do this in order to manually link relations (when not injecting relations into the store).

Luckily, property accessors can be defined right on the prototype of each resource's instance constructor, increasing performance and efficiency of the relation linking feature considerably. For those resource where `useClass` is disabled, the property accessors will have to be added to each item individually. (Unless I decide `useClass: false` won't be possible in 2.0) 

It would be interesting to measure just how much the perform of `DS#inject` improves with this change.

Initial experimentation shows a reduction in size of the final minified file by over 2.5kb.

##### Breaking changes

- An official features that is not supported in IE < 8 (polyfill not possible within a reasonable amount effort), though disabling the feature should still other bits to work in IE8 (though I haven't tested it, and probably never will).
- Relation links will no longer be enumerable by default(should also eliminate the need for `DSUtils.removeCircular`)
- `DS#inject` options `findBelongsTo`, `findHasMany`, `findHasOne`, & `findInverseLinks` are no longer needed
- The methods `DS#link`, `DS#unlinkInverse`, `DS#linkAll`, `DS#linkInverse` can be removed from the API
- Relation links will only work if the related items have actually been injected into the store (unless you disable property accessors for a certain relation/resource and then manually attach related data).

##### Implementation

- [x] - Remove `DS#inject` options `findBelongsTo`, `findHasMany`, `findHasOne`, & `findInverseLinks`
- [x] - Remove the methods `DS#link`, `DS#unlinkInverse`, `DS#linkAll`, `DS#linkInverse`
- [ ] - Determine whether `removeCircular` can be removed
- [x] - Add the `Object.defineProperty` code to `DS#inject`/Resource instance constructors
- [x] - Make sure all of this is configurable, including the enumerability of the properties

##### Code

Some pseudo-ish code (to think, this code eliminates the need for four entire API methods and several options of `DS#inject`...):
```js
DSUtils.forEach(definition.relationList, def => {
  let relationName = def.relation;
  let relationDef = _this.defs[relationName];
  let params = {};
  delete attrs[def.localField];
  //console.log(def);
  if (def.type === 'belongsTo') {
    Object.defineProperty(item, def.localField, {
      get: () => item[def.localKey] ? relationDef.get(item[def.localKey]) : undefined
    });
  } else if (def.type === 'hasMany') {
    params[def.foreignKey] = attrs[definition.idAttribute];
    Object.defineProperty(item, def.localField, {
      get: () => {
        return params[def.foreignKey] ? _this.defaults.constructor.prototype.defaultFilter.call(_this, _this.s[relationName].collection, relationName, params, { allowSimpleWhere: true }) : undefined;
      }
    });
  } else if (def.type === 'hasOne') {
    if (def.localKey) {
      Object.defineProperty(item, def.localField, {
        get: () => item[def.localKey] ? relationDef.get(item[def.localKey]) : undefined
      });
    } else {
      params[def.foreignKey] = attrs[definition.idAttribute];
      Object.defineProperty(item, def.localField, {
        get: () => {
          let items = params[def.foreignKey] ? _this.defaults.constructor.prototype.defaultFilter.call(_this, _this.s[relationName].collection, relationName, params, { allowSimpleWhere: true }) : [];
          if (items.length) {
            return items[0];
          }
          return undefined;
        }
      });
    }
  }
});
```

**Comment by Tlvenn** [comment]
+1 looks great !

As mentioned on gitter, no need to define the setter, best to leave it undefined so that if someone try to assign a value, an error will be thrown.

**Comment by jmdobry** [comment]
Yes, will do.
