### ISSUE TITLE
Make filtering more configurable

### ISSUE THREAD

**Issue by jmdobry** [js-data/js-data#109]

**Comment by WillsB3** [comment]
Might be important to consider that some filtering logic may not be possible on the client side. E.G. A location filter where you want to filter results to within x miles of a lat/lng. Some databases do this but it's more tricky on the frontend. I realise that this kind of causes big issues with how the Datastore currently works, but probably important to keep in mind. Would be good if js-data could somehow support these use cases (even if requiring going to the server for filter results).

**Comment by jmdobry** [comment]
For those cases where the filtering can't be done client-side, even by overriding js-data's default filter, then one's last option is to use `DS#findAll`, letting the server to the filtering. As long as `useFilter` is `false`, subsequent `findAll` calls with the same params will resolve with the previously returned data. Since the filtering can't be done client-side, the developer would need to to add items to the cached data manually, or force a new request for the data. So technically, js-data does support this use case, (go to the server for filter results).
