### ISSUE TITLE
cacheResponse not enabled by default

### ISSUE THREAD

**Issue by marklawlor** [js-data/js-data#111]
DS#create does not cache results by default as documented (http://www.js-data.io/v1.6.0/docs/dscreate)

```
var JSData = require('js-data');
var DSMongoDBAdapter = require('js-data-mongodb');

var store = new JSData.DS({ debug: false});
var mongoDBAdapter = new DSMongoDBAdapter('mongodb://localhost:27017/test');
store.registerAdapter('mongodb', mongoDBAdapter, {default: true });

var people = store.defineResource({
  name: 'people',
  idAttribute: '_id',
  table: 'test',
});

people.create({'_id': 1, 'name': 'john'}).then(function(person){
	// Undefined        
	console.log(people.get(person._id));
});

people.create({'_id': 2, 'name': 'bob'}, { cacheResponse: true }).then(function(person){
	// {'_id': 2, 'name': 'bob'}        
	console.log(people.get(person._id));
});
```

JS-Data: 1.6.3
js-data-mongodb: 0.2.3

**Comment by jmdobry** [comment]
I mention in the docs that:

> JSData detects that it is running in Node.js it automatically changes a number of data store defaults to be more server-friendly.

but I don't actually mention which defaults are changed, and I apologize for that. `cacheResponse` is one of those defaults that is set to false when running in Node. If you know you're only going to be running one instance of your app (no workers) and all your data can fit in memory on your machine, then go ahead and set it back to `true`.

`var store = new JSData.DS({ debug: false, cacheResponse: true });`

I will add to the docs the full list of defaults that are changed.

When running in Node.js:

- `cacheResponse` defaults to `false`
- `notify` defaults to `false`
- `reapAction` defaults to `"none"`
- `reapInterval` defaults to `false`
- `upsert` defaults to `false`

**Comment by marklawlor** [comment]
Cheers :+1:
