### ISSUE TITLE
Remove bundled Promise code

### ISSUE THREAD

**Issue by jmdobry** [js-data/js-data#121]
Starting in 2.0, js-data will no longer bundle an ES6 Promise polyfill. It will expect a global `Promise` constructor, allowing developers to polyfill with whatever promise library they want. They can also give js-data a Promise constructor to use by doing:

```js
JSData.DSUtils.Promise = myPromiselib;
```

They must do this before any js-data code (that uses promises) runs.

**Comment by eeejayg** [comment]
How would I add a global promise constructor using Angular's promise constructor?

**Comment by jmdobry** [comment]
Are you using js-data-angular? You don't need to worry about configuring js-data to use `$q`, js-data-angular does that for you.

**Comment by eeejayg** [comment]
Yeah, it seems so, but it's giving me a message in IE (js data needs a
promise constructor).

ej

**Comment by jmdobry** [comment]
You can't disable the message, though perhaps it should be removed and js-data should fail silently? You could even just do `window.Promise = 'foo'` and it will make the message go away. Though in the `.run` of your Angular app you'd want to do `window.Promise = $q`.

**Comment by centigrade-thomas-becker** [comment]
I get the warning "js-data requires a global Promise constructor" when using Karma with PhantomJS. The actual tests run without problem.

**Comment by phhien203** [comment]
yes, @centigrade-thomas-becker , I got the same error when running Karma test

**Comment by jmdobry** [comment]
@centigrade-thomas-becker @phhien203 You can remove the warning by polyfilling the ES6 Promise. An easy way to do this:

1. `<bower/npm> install --save-dev es6-promise`
2. Add `<bower_components/node_modules>/es6-promise/dist/es6-promise.min.js` to the top of the list of files that Karma loads
3. That's it :)

**Comment by centigrade-thomas-becker** [comment]
Thanks for the instructions

**Comment by phhien203** [comment]
It could help. Thanks so much.

**Comment by mhilland** [comment]
I'm getting the same error when attempting to render a page via PhantomJS (not using karma). I've tried including es6-promise to my PhantomJS node server without success. Any pointers on how to circumvent this issue using PhantomJS?

**Comment by jmdobry** [comment]
@mhilland Include the es6-promise code in the bundle of javascript that you're loading into your app (make sure it loads before js-data).
