### ISSUE TITLE
Actions not documented in documentation for defineResource

### ISSUE THREAD

**Issue by WillsB3** [js-data/js-data#123]
Seems like the `actions` option is missing from the [documentation for  `defineResource`](http://www.js-data.io/v1.8.0/docs/dsdefineresource). I'd have expected to see `actions` documented here.

It's documented on the [main configuration page](http://www.js-data.io/v1.8.0/docs/dsdefaults) but that's it.

**Comment by jmdobry** [comment]
There are too many options for me to want to duplicate the documentation for all of them (unless somebody else wants to keep two lists of options in sync). From the `defineResource` doc page:

![screen shot 2015-04-17 at 7 59 34 am](https://cloud.githubusercontent.com/assets/1213510/7203425/cf71a774-e4d7-11e4-8903-57d1c6e7d473.png)

**Comment by WillsB3** [comment]
Right. I think the thing that threw me was the fact that `methods` was documented there but `actions` wasn't.
