### ISSUE TITLE
Direct support for inject of JSON

### ISSUE THREAD

**Issue by robvon** [js-data/js-data#130]
"function _inject(definition, resource, attrs, options) {"

Function inject looks at 'attrs' to see if it is an array. My data, via the HTTP adapter comes in as as JSON string. By simply running a JSON.parse(attrs) in a 'transformResponse' hook, I can wrap the parsed object into an array. This all works and avoids the check:

"if (DSUtils._a(attrs)) {"   <--- this is the line that checks if attrs is an array

Would there be a benefit to the product by supporting JSON out of the box ? Then I wouldn't have to use "transformResponse". A lot of my queries are to Odata back-ends. Not going to get an array there.

If this feature is hiding somewhere please let me know...

**Comment by jmdobry** [comment]
I'm not sure why a JSON string would be sent into `inject`. axios (js-data-http) and $http (js-data-angular) automatically parse the response body into JSON if the response's Content-Type header is application/json. Could you produce a plunker or jsfiddle that demonstrates?

**Comment by jmdobry** [comment]
The API for `DS#inject` is that it accepts either an Object that has a primary key or an Array of Objects that have primary keys. It's not going to accept a string.
