### ISSUE TITLE
Allow filtering by nested fields 

### ISSUE THREAD

**Issue by jmdobry** [js-data/js-data#133]

**Comment by sinsunsan** [comment]
this closed for 2.0 only or also for 1.? @jmdobry

**Comment by jmdobry** [comment]
It's in 2.0. Perhaps I could backport it to 1.x

**Comment by sinsunsan** [comment]
If it is not too complicate, would be nice to have it on 1.X, as it's the version we currently use. 

 By the way, it is easy the move to 2.X version ? Should we wait for it to stabilize ? Do you have a doc, to how to migrate ?

**Comment by jmdobry** [comment]
2.x is under the beta tag in npm. The [CHANGELOG.md](https://github.com/js-data/js-data/blob/2.0/CHANGELOG.md#breaking-api-changes-1) file in the 2.0 branch documents breaking changes.

**Comment by chillyprig** [comment]
Can you give an example for search:

Can I do like this

var params = {
    where: {
        customer: {
            firstname: {
                '==' : $scope.keyword.group
            }
        }
    }
}

Relation.filter(params)

I've tried but it not working.

**Comment by chillyprig** [comment]
Let's say I have 

```Javascript
customer: {
    addresses: [
      {
        detail: "a"
      },
      {
        detail: "b"
      },
      {
        detail: "c"
      }
    ]
}
      
```

Is there any example to filter address inside of the customer?

**Comment by jmdobry** [comment]
Unless you're filtering on a property of the `addresses` array, such as its length, or unless you have actual references to those details objects and you're trying to filter by them, then any other type of filtering on a nested array containing objects is too advanced for js-data's default filter.
