### ISSUE TITLE
All resources get all methods defined on any resource

### ISSUE THREAD

**Issue by kenborge** [js-data/js-data#134]
If you define some default methods for resources, for instance when using angular:
```javascript
angular.extend(DSProvider.defaults, {
        methods: {
            someGlobalMethod: function () {}
        }
});
```
Then if you define some methods on a resource

```javascript
DS.defineResource({
    methods: {
        someMethod: function () {}
    }
});
```
Then this code in js-data somehow adds the methods to the global default so all resources get this method.
```javascript
    var Resource = function Resource(options) {
        _classCallCheck(this, Resource);
        DSUtils.deepMixIn(this, options);  // <---- This line mixes the 
                                           // method into the prototype not the resource
        ...
    }
```

**Comment by jmdobry** [comment]
I had just noticed this bug myself.

**Comment by kenborge** [comment]
Any chance for a fix for this on 1.x version? Kind serious bug and maybe not everyone will update to 2.0 right away

**Comment by jmdobry** [comment]
Yeah I could backport the fix, when I write it.
