### ISSUE TITLE
JSData caching inconsistence behaviour when ejecting items

### ISSUE THREAD

**Issue by zuzusik** [js-data/js-data#135]
JSData removes the cached query result when all the items that belong to this result are ejected.
This happens here: https://github.com/js-data/js-data/blob/master/src/datastore/sync_methods/eject.js#L54

This leads to the inconsistency, which can be illustrated by the following example.

We have an interface with two tabs. One has the list of 4 items. User can remove this items. 

Flow one:
1) User removed 1 item and 3 items are left
2) User switched to another tab
3) User switched back
4) User sees 3 items (JSData uses cached result)

Flow two:
1) User removed all the 4 items
2) User switched to another tab
3) User switched back
4) User sees 4 items again (JSData removed the query result from cache and made the network request and loaded all the items)

As for me, there is no reason in deleting cached result if it becomes empty.

JSData version 1.8.0

**Comment by jmdobry** [comment]
I will make it configurable.

**Comment by zuzusik** [comment]
@jmdobry thanks for quick reply!
Can you please explain what is the reason in such behaviour? I am just curious - maybe I am missing something?

**Comment by jmdobry** [comment]
Here's an example: You do a `findAll` call, but over time the items that were loaded are ejected because you've activated js-data's cache-busting feature (`reapInterval`, `reapAction`). The items expired, so they were removed from the store. Now the user requests those items again, instead of getting an empty array, it needs to make the query again, and it doesn't know to do that unless the cached query is removed when all the items associated with the query get ejected.

**Comment by zuzusik** [comment]
@jmdobry so maybe it would be reasonable to separate this processes? To delete from cache only when cache-busting is enabled? 

Also the cache-busting can be a problem if there is a flow when first some changes needs to be collected and only then saved. For example user adds some items, they are injected into the store and then after user has finished, he pushes 'Save' and items are saved. Is cache busting is smart enough to not to touch such items? On the other hand there can be a flow when items are injected because they came from the push notification... Well, to solve all of this, I suppose, item should have some indicator that tells if it was saved on the adapter's side. 

Sorry if I raised issues that are already solved.

**Comment by jmdobry** [comment]
js-data keeps track of that last time an item was saved via an adapter, e.g.:

`User.lastSaved(1); // 123456789000`

**Comment by jmdobry** [comment]
As of 2.0.0-beta.5, `clearEmptyQueries` can be set to `false` to achieve your desired behavior.
