### ISSUE TITLE
separate singular from plural resource paths

### ISSUE THREAD

**Issue by acroyear** [js-data/js-data#136]
In the API we have to use, the providers use plural forms for the fetch-all (with filters) case. So I might have

GET /email/:id
but
GET /emails
for the set.

This does not appear to be something we can override - .defineResource seems to still think there's only one endpoint possible, not two. Are we misreading this, or is this basically a feature request?

**Comment by jmdobry** [comment]
Try specifying your endpoint on the fly. Pass an `endpoint` value as part of the options hash argument of the method you're calling.

**Comment by acroyear** [comment]
That worked. thanks.
