### ISSUE TITLE
I can't get DS.find to work in a service.

### ISSUE THREAD

**Issue by vialcollet** [js-data/js-data#137]
Hi and congrats for this fantastic library!

I have an issue though when trying to use DS#find in a service whereas it is working well in a controller. 
Similarly, I can't get DS#get to work if find has not been triggered once before, even with the loadFromServer: true param.

Here is my controller:

    .controller('TestCtrl', function ($log, ServerDB) {

        var test = this;

        test.label = 'URL get';
        // in next line get returns undefined if find has not been called yet
        test.url = ServerDB.get(1, {loadFromServer: true}).server.url;

        test.label2 = 'URL find';
       // next line always work (but I'd like to export this in a service/factory)
        ServerDB.find(1).then(function (server) {
            console.log('from Ctrl: ', server);
            test.url2 = server.server.url;
        });

        // Next line triggers the error within the service
        test.label3 = 'URL get from service serverURL';
        test.url3 = serverURL.url;

    })

Here is my service:

    .service("serverURL", function serverURL($log, ServerDB) {
        
        var serverURL;
        ServerDB.find(1).then(function(server) {
            // Next line triggers an error when called from Ctrl as get returns undefined
            serverURL.url = server.server.url;
            console.log('from service: ', serverURL.url);
            return serverURL;
        });
        
    })

Here are my store and resource definition:

    .factory('localStore', function localStore($log) {

        var localStore = new JSData.DS({
            loadFromServer: true
        });

        localStore.registerAdapter('localstorage', new DSLocalStorageAdapter(), { default: true });
        $log.info('localStore created');

        return localStore;

    })

    .factory('ServerDB', function Server($log, localStore) {

        $log.info('serverDB created');
        return localStore.defineResource('server');

    })

**Comment by jmdobry** [comment]
What version of js-data, js-data-localstorage are you using?

**Comment by vialcollet** [comment]
Thanks for your help @jmdobry!
js-data: @version 1.8.0
js-data-localstorage: @version 1.1.1
js-data-angular: @version 2.4.0

I am using ionic and AngularJS v1.3.13

**Comment by jmdobry** [comment]
I would avoid using `DS#get` + `loadFromServer: true`. `loadFromServer` will be removed in 2.x. If you're not sure the item is in the store yet, just use `DS#find`.

Your code, annotated:

```js
.controller('TestCtrl', function ($log, ServerDB) {
    var test = this;
    test.label = 'URL get';
    // avoid using loadFromServer: true
    test.url = ServerDB.get(1, {loadFromServer: true}).server.url;

    test.label2 = 'URL find';
   // put "ServerDB.find" in the resolver for your route,
   // and then you can just grab "$route.current.locals.serverDB"
    ServerDB.find(1).then(function (server) {
        console.log('from Ctrl: ', server);
        test.url2 = server.server.url;
    });

    // Next line triggers the error within the service
    // No wonder, unless it's a global variable, "serverURL" has not been defined anywhere
    // You're trying to access the "url" property of "undefined"
    test.url3 = serverURL.url;
})
```
```js
.service("serverURL", function serverURL($log, ServerDB) {
    // so here you declare "serverURL", but its value is "undefined"
    // also, it's scoped within this function, so it's not visible to your controller
    var serverURL;
    // perhaps you mean to do the following:
    this.serverURL = {};

    ServerDB.find(1).then(function(server) {
        // you can't access "url" of "undefined"
        // you need to initialize "serverURL" with a value somewhere
        serverURL.url = server.server.url;
        // perhaps you mean to do this
        this.serverURL.url = server.server.url;
        return serverURL;
    });
})
```

**Comment by vialcollet** [comment]
Ok point taken for `loadFromServer`, thanks.
What I get from your comments above is that I have two solutions, use a resolve or follow your comments about defining my variables.
Let me try this!

**Comment by vialcollet** [comment]
Ok perfect, it is working better now.
I am not there yet because in fact I need this value in a factory and I don't know how to pass the parameter from the resolve to the factory. And if I call my serverURL service from the factory, it's asynchronous nature messes everything.

    .factory('Contacts', function ($resource, $log, serverURL) {

        var url = serverURL.url;
        return $resource(url + '/contacts/:id', {id: "@id"});

    })

**Comment by jmdobry** [comment]
That's why the `resolve` for your route is so useful, it can guarantee asynchronous data has been loaded before your controller runs.

**Comment by vialcollet** [comment]
...oh ! And as it has been triggered, I won't need to even pass the parameter !!
Great that's working fine now.
Thanks a thousands.
My next work is to try to manage offline/online states... ;)

**Comment by jmdobry** [comment]
The [Gitter channel](https://gitter.im/js-data/js-data) and [mailing list](https://groups.io/org/groupsio/jsdata/threads) are great resources for getting support.
