### ISSUE TITLE
Collection class

### ISSUE THREAD

**Issue by jmdobry** [js-data/js-data#138]
See @WillsB3 's comment: https://github.com/js-data/js-data/issues/68#issuecomment-96818142

My question regarding implementation:

Should I sub-class Array? Or create an wrapper Collection that maintains an internal data structure?

Possible features of collections:

- Observe the data store for changes, and automatically update themselves based on given parameters, like `bindAll` in js-data-angular.
- A `fetch` method, that would do the same thing as `findAll`, and update itself with the result.
- `cacheResponse: false` makes the Collection a stand-alone set of data

Seems like perhaps I could re-architect js-data a bit (or a lot) so that when you define a resource it creates a single collection for that resource, and the collection has a lot of the logic that now sits on the store.

**Comment by jmdobry** [comment]
A collection that is doing some observation in the background will result in memory leaks if its lifecycle cannot be managed. So, a stand-alone collection won't be able to update itself as the contents in the data store change. However, I could it so that collections that register themselves with the store can then be bound to the state of the data that's in the store, so as the data in the store changes, registered collections will update themselves accordingly.

So far, a collection can be created like so:

```js
var params = {
  where: {
    age: {
      '>=': 30 
    }
  }
};

// empty collection
var users = User.createCollection([], params);

// GET /users?<where age >= 30>
// same effect as User.findAll(params)
users.fetch().then(function (u) {
  users === u; // true

  // return cached results
  return users.fetch();
}).then(function (u) {
  users === u; // true

  // return results filtered from what's
  // already in the store, and update
  // this collection's contents to match
  return users.fetch(null, { useFilter: true });
}).then(function (u) {
  users === u; // true
});

// initialize a collection with data
var users2 = User.createCollection([User.get(123)]);

// load data into collection, but don't inject into store
var users3 = User.createCollection([], { role: 'admin' });
// GET /users?role=admin
users3.fetch().then(function (u) {
  users3 === u; // true

  // results were not injected into the store
  User.filter({ role: 'admin' }); // []

  // but the collection now has the results
  users3; // [{...}, {...}, ...]
});
```

What do you think @WillsB3 ?

**Comment by WillsB3** [comment]
Wooo :+1: 

I'm not sure if it'd be best to subclass Array or to create a wrapping Collection class. Can you outline some of the pros/cons of each approach?

I like the concept of the store just being one large "unfiltered" collection of items. That would mean that user instantiated collections were actually sub-collections (which is kind of awesome).

**Comment by jmdobry** [comment]
A subclassed Array means you can interact with the object as if it is a normal array, the data structure isn't hidden or a sub-property of the object. A wrapper means I would have to completely define the API that you can use to interact with the collection. A wrapper class means less interop with the existing API. A subclassed Array can be substituted for the existing return value of `findAll` and `filter`. A subclassed array is `instanceof Array` and `Array.isArray(subclassedArray) === true`, a wrapper class is not. My initial implementation uses a subclassed array.

Stand-alone collections can aid in pagination and working with datasets that you want filtered solely by the backend. Registered collections can bring the js-data-angular `bindAll` method to other frameworks.

**Comment by spawnedc** [comment]
Hey there,

I'm working closely with @WillsB3 for the last couple of years and when we were having a discussion about the collection class, we got a good question to ask.

I just checked the sample code you provided and it makes sense to me. I was wondering if the collections you create for the User model, are a subset of the User datastore, or are they independent instances?

Let's say `users` collection contains `user-1`, `user-2` and `user-3` models. I create `users2` collection and fetch it with some filters which returns `user-2`, `user-3`, `user-4` and `user-5`. Should we expect to `user-2` and `user-3` in both collections to be the same and changes reflected?

**Comment by jmdobry** [comment]
Yes, there will only be a single instance of a given item across all collections _unless_ you use `cacheResponse: false` on a collection, in which case the fetched items are not injected into the main datastore, so the collection might contain copies of data in the main store.

**Comment by spawnedc** [comment]
Awesome! Also subclassing Array makes sense after all your explanations.
