### ISSUE TITLE
Option to specify default values of new resource instances.

### ISSUE THREAD

**Issue by jmdobry** [js-data/js-data#139]

**Comment by kentcdodds** [comment]
Suggested requirements:

- Function OR object
- If function, called with the original data and return the default values.

Prior art: how angular-formly does [`defaultOptions`](http://docs.angular-formly.com/v6.3.2/docs/formlyconfig#settype) ([implementation](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-field.js#L109)). Feel free to ping me with questions.

**Comment by jmdobry** [comment]
That's what I was thinking I would do.
