### ISSUE TITLE
Expose js-data methods in adapter config

### ISSUE THREAD

**Issue by spawnedc** [js-data/js-data#140]
Currently both single model requests `/model/:id` and list requests `/model` uses same method as they should: `GET`. But, there's no way to tell if we are expecting a list response (an array) or a single object. Restangular has a special read-only parameter in its interceptors (operation) which is `get` for single objects and `getList` for list responses. From [their doc](https://github.com/mgonto/restangular#addresponseinterceptor):

> operation: The operation made. It'll be the HTTP method used except for a GET which returns a list of element which will return getList so that you can distinguish them.

This is particularly useful when an API (which we have no control on it) REMOVES empty arrays (I know) from the response. So in our case here's a sample response from the server (note how the response is wrapped with an object under a key called `items`):

```javascript
{
    "items": [{
        "name": "John",
        "surname": "Smith"
    }, {
        "name": "Joe",
        "surname": "Bloggs"
    }]
}
```

And here's an empty list response:
```javascript
{}
```

Yes, there's no "items" object as an empty array. What I'd expect is:
```javascript
{
    "items": []
}
```

But no. And here's a single object response:
```javascript
{
    "name": "John",
    "surname": "Smith"
}
```

So this situation makes things really hard since we can't tell in interceptors if an empty response (`{}`) is actually an empty list or a real empty object. Currently I'm doing something like this:
```javascript
DSHttpAdapterProvider.defaults.deserialize = function (resource, data) {
	if (_.isEmpty(data.data)) {
		// We have a completely empty object,
		// we *assume* that it's an empty array
		data.data.items = [];
	}
	return data.data.items ? data.data.items : data.data;
};
```

It would be really nice to have a third parameter in `deserialize` function which represents what kind of operation we are doing, and maybe the method we call (fetchAll, fetch, updateAll, etc)? Or maybe in `data.config`?

**Comment by jmdobry** [comment]
That's a good idea, I'll think on it. I'm thinking it might also be useful to add method specific configuration on resources, so you can have a different `deserialize` for `findAll` than you do for `find`.

**Comment by jmdobry** [comment]
#145 adds the ability for per-method configuration (available in 2.0.0-beta.6). So to solve your specific problem:

```js
angular.module('app', ['js-data'])
  .config(function (DSHttpAdapterProvider) {
    DSHttpAdapterProvider.defaults.deserialize = function (Resource, response) {
      // handle general deserialization
      return response.data;
    };
  })
  .run(function (DS) {
    function deserializeArrayResponse(Resource, response) {
      return response.data.items || [];
    }

    // AOP
    // Whenever you call findAll, this function will be called first
    DS.findAll.before(function (resourceName, params, options) {
      options = options || {};
      options.deserialize = deserializeArrayResponse;
      // return the arguments that will be passed to the original `findAll`
      return [resourceName, params, options];
    });
    DS.updateAll.before(function (resourceName, attrs, params, options) {
      options = options || {};
      options.deserialize = deserializeArrayResponse;
      // return the arguments that will be passed to the original `updateAll`
      return [resourceName, attrs, params, options];
    });
  });
```

**Comment by spawnedc** [comment]
This.Is.Amazing. Thank you!

**Comment by jmdobry** [comment]
:smile:
