### ISSUE TITLE
Best practice for callback on model property change

### ISSUE THREAD

**Issue by facultymatt** [js-data/js-data#141]
Lets say you want to watch a model property. When the property changes, you want to set a second property to a default value. Here is an example model:

```
var User = store.defineResource({
  name: 'user',
  schema: {
    id: {
      type: 'string'
    },
    username: {
      type: 'string',
      nullable: false,
      minLength: 6,
      maxLength: 30
    },
    email: {
      type: 'string',
      nullable: false
    }
  }
});
```

This is easy to do in a controller using `$watch`, for example:
```
$scope.$watch('user.username', function(newUserName) {
    user.emailAddress = newUserName + '@gmail.com';
});

user.username = 'cool';
console.log(user.email) // cool@gmail.com

user.username = 'cat';
console.log(user.email) // cat@gmail.com
````

**Now, the question is, can we define this behavior in the model? Instead of using scope watch?**

I realize this could be possible with Object.observe... is this the best practice? Could there be a model lifecycle callback for this?

**Comment by jmdobry** [comment]
Computed properties, you'll find them in the docs

**Comment by facultymatt** [comment]
Ahhh, yes, that was a bad example. I'm aware of computed props but they will not work for this situation.

Here is a better example: 

```
var Shop = store.defineResource({
  name: 'shop',
  schema: {
    id: {
      type: 'string'
    },
    mondayOpen: {
      type: 'string'
    },
    mondayHoursApplyToAllWeekdays: {
      type: 'boolean'
    },
    tuesdayOpen: {
      type: 'string'
    },
    wednesdayOpen: {
      type: 'string'
    },
    ///etc...
  }
});

shop.mondayOpen = '11am';
shop.mondayHoursApplyToAllWeekdays = true;
console.log(shop.tuesdayOpen) // 11am
console.log(shop.wednesdayOpen) // 11am

shop.mondayHoursApplyToAllWeekdays = false;
console.log(shop.tuesdayOpen) // null
console.log(shop.wednesdayOpen) // null
```

Perhaps this is a better example...

**Comment by jmdobry** [comment]
Why won't it work?

```javascript
var Shop = store.defineResource({
  name: 'shop',
  schema: {
    id: {
      type: 'string'
    },
    mondayOpen: {
      type: 'string'
    },
    mondayHoursApplyToAllWeekdays: {
      type: 'boolean'
    },
    tuesdayOpen: {
      type: 'string'
    },
    wednesdayOpen: {
      type: 'string'
    },
    ///etc...
  },
  computed: {
    tuesdayOpen: ['mondayOpen', function (mondayOpen) {
      return mondayOpen ? mondayOpen : null;
    }],
    // ...
  }
});
```

**Comment by facultymatt** [comment]
The above would not work because tuesdayOpen, wednesdayOpen, can be set on their own - they are not solely computed properties. 

For example: 

```
// set properties
shop.mondayOpen = '11am';
shop.tuesdayOpen = '12am';
shop.wednesdayOpen = '1pm';

// read values
console.log(shop.mondayOpen) // 11am
console.log(shop.tuesdayOpen) // 12am
console.log(shop.wednesdayOpen) // 1pm

// monday hours rule them all! 
shop.mondayHoursApplyToAllWeekdays = true;
console.log(shop.mondayOpen) // 11am
console.log(shop.tuesdayOpen) // 11am
console.log(shop.wednesdayOpen) // 11am
```

**Comment by jmdobry** [comment]
Prepare to be amazed: http://plnkr.co/edit/vNCoC8?p=preview

**Comment by facultymatt** [comment]
Fantastic! Define property is useful for this example. But can we still
take advantage of validates, nullable, relations, etc? I'm not sure how
base class works exactly...

On Friday, May 22, 2015, Jason Dobry <notifications@github.com> wrote:

> Prepare to be amazed: http://plnkr.co/edit/vNCoC8?p=preview
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/js-data/js-data/issues/141#issuecomment-104704527>.
>


-- 
Matt Miller


Web Master
609-335-4417
matt@superpedestrian.com
https://www.superpedestrian.com/
<https://www.google.com/url?q=https%3A%2F%2Fwww.superpedestrian.com%2F&sa=D&sntz=1&usg=AFQjCNHLEDFaMLgggeXL8rh4gGlNfN0WSA>
________________
Superpedestrian Inc.
84 Hamilton St.
Cambridge, MA 02139

*This message is intended only for the addressee named above.  If you are
not the intended recipient of this message, you are hereby notified that
you must not use, disseminate, or copy it in any form or take any action in
reliance upon it.  If you have received this message in error, please
delete it and any copies of it from your email system and reply immediately
to the sender at the address shown above.  This message may contain
confidential and/or proprietary information.  Neither confidentiality, nor
any proprietary rights are intended to be waived or lost by any error in
transmission.*

**Comment by jmdobry** [comment]
All that stuff should still work normally. I just left it out of the example for simplicity.

**Comment by facultymatt** [comment]
Having trouble getting schema to validate... not sure my Plunker is setup correctly. You mind taking a look?

**Comment by facultymatt** [comment]
Worked a bit more on this plunkr: http://plnkr.co/edit/y7BfVNEQrAeYvbxcvVMf?p=preview

There are two issues I see currently

1. Using `useClass: BaseShopInstance` breaks validation. If you comment out this line, the validation works as expected. 

2. Using `Object.defineProperty` AND returning validation error hash causes an error: 

```
RangeError: Maximum call stack size exceeded
    at BaseShopInstance.get [as mondayHoursApplyToAllWeekdays]
```

**Comment by jmdobry** [comment]
I'll take a look.

**Comment by jmdobry** [comment]
You just need to remove the getter:

```js
Object.defineProperty(this, 'mondayHoursApplyToAllWeekdays', {
        enumerable: true,
        get() {
          return this.mondayHoursApplyToAllWeekdays;
        },
        set(x) {
          fields.forEach(function(field) {
            this[field] = x ? this.mondayOpen : null;
          }, this);
        }
      });
```

should be

```js
Object.defineProperty(this, 'mondayHoursApplyToAllWeekdays', {
        enumerable: true,
        set(x) {
          fields.forEach(function(field) {
            this[field] = x ? this.mondayOpen : null;
          }, this);
        }
      });
```

**Comment by jmdobry** [comment]
Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, JSData, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [Gitter Channel](https://gitter.im/js-data/js-data) or the [mailing list](https://groups.io/org/groupsio/jsdata).

**Comment by facultymatt** [comment]
Im OK with closing this. Now its more of a feature request. 

Yes, the above can be achieved with setters as you demonstrated. 

However, it would be beneficial to hook into the observe or digest cycle. 

For example, [here you track changes](https://github.com/js-data/js-data/blob/912061d70d60d4ff01b77033b3e808ddf93ae59b/dist/js-data.js#L1833) when an object changes. Would it be possible for a developer to hook into this, and provide custom logic like the above example when certain properties change?

Another approach would be to hook into the digest [here](https://github.com/js-data/js-data/blob/912061d70d60d4ff01b77033b3e808ddf93ae59b/dist/js-data.js#L1353) or [here in angular](https://github.com/js-data/js-data-angular/blob/master/src/index.js#L238).

**Comment by jmdobry** [comment]
I've been thinking about ways to immediately respond to changes to an item. I'll keep thinking about it.
