### ISSUE TITLE
DSGetEndpoint instance method

### ISSUE THREAD

**Issue by kentcdodds** [js-data/js-data#143]
I would love to be able to do this:

```javascript
var instance = MyResource.get('x');

var url = instance.DSGetEndpoint();
```

Obviously the workaround isn't a big deal:

```javascript
var instance = MyResource.get('x');

var url = MyResource.getEndpoint(instance.id, {});
```

But not having to workaround would be nice :-)

**Comment by jmdobry** [comment]
Maybe, `getEndpoint` might move into the http adapter.

**Comment by jmdobry** [comment]
`getEndpoint` has been moved to the http adapter, removing concerns for HTTP from JSData (mostly)

**Comment by kentcdodds** [comment]
Sounds great. Does the api change for me at all if I'm using the http adapter?

**Comment by jmdobry** [comment]
No
