### ISSUE TITLE
Debug output

### ISSUE THREAD

**Issue by SystemParadox** [js-data/js-data#150]
The npm version of js-data (2.0.0-beta.5) seems to have debugging output on by default. This confused me for a while before I realised I needed to pass `{ debug: false }` when doing `new JSData.DS()`.

It would be much nicer if debug output was only enabled if the user asks for it.

On a related note, it would be nice if js-data used the `debug` module instead of `console`.

Thanks.

**Comment by jmdobry** [comment]
`debug` will default to `false` in 2.0.0

You can tell js-data to use whatever logging library you'd like:

```js
var store = new JSData.DS({
  log: myLoggingLib.log,
  error: myLoggingLib.error
});
```
