### ISSUE TITLE
Clone instance

### ISSUE THREAD

**Issue by SystemParadox** [js-data/js-data#151]
Related to #57, but probably useful generally, it would be nice if there was an easy way to get an item from the store as a copy rather than having identity mapping.

This would make it easier to use `update` rather than `save` to avoid polluting the store with changes that aren't saved yet.

Thanks.

**Comment by jmdobry** [comment]
Whatever utility library you're using probably has a clone method, but here are two ways to do it with js-data:

```js
var userCopy = store.utils.copy(User.get(1));
var user2Copy = User.createInstance(User.get(2));
```
