### ISSUE TITLE
Allow defineResource(name, options) or throw an error

### ISSUE THREAD

**Issue by SystemParadox** [js-data/js-data#152]
The initial examples always use `defineResource('foo')`. So when I wanted to add some options to it, I naturally assumed it was `defineResource('foo', options)`, not realising that defineResource only takes a single argument. It took me quite a while to work out why my options were being ignored.

Please could `defineResource` either allow `(name, options)` arguments, or else throw an error if too many arguments are passed.

Thanks.

**Comment by jmdobry** [comment]
I updated the documentation for [`DS#defineResource(options)`](http://www.js-data.io/docs/dsdefineresource) to be extremely clear on what the API for the method is.

I also updated the initial examples to not always use `defineResource('foo')`.
