### ISSUE TITLE
Intercept 200/304 responses for caching strategy with DSHttpAdapter

### ISSUE THREAD

**Issue by rquast** [js-data/js-data#154]
Currently, the only way to automatically synchronize data is with a poll, sse or socket. If DSHttpAdapter could send etags/modified TS & intercept responses (200/304) and only update the data when a query is performed, it would be less overhead than using bypassCache which forces a refresh (though I'm assuming the 304 response is cached in the browser). Would be better if the 304 response was intercepted by JSData and the cache was served up by the local DS.

**Comment by jmdobry** [comment]
JSData is completely unaware of the particulars of the various persistence layers (e.g. anything HTTP related), so any solution to this would need to be done without coupling JSData to HTTP.

**Comment by rquast** [comment]
Probably easier to try and synchronize the data instead. I've had a look at the code and see what you mean.

**Comment by jmdobry** [comment]
Maybe. What I meant is that we'd have to design an API that might work for any adapter, something like this:

1. The data is not in the store
1. Store calls adapter, saying "I don't have the data"
1. Adapter returns data from persistence layer
1. Data gets cached
1. Store calls adapter, saying "I have the data" + "here is its timestamp"
1. Adapter responds either with:
  1. Fresh data from the persistence layer
  1. Notification to just use the cached data

From the point of view of JSData, this API would have to be persistence-layer agnostic. The details of "304 not modified" or whatever constitutes a "just use the cached data" notification would have to be handled by the adapters.

**Comment by rquast** [comment]
Right, of course, because the options for find, etc (like bypassCache) are for all of the adapters, not just DSHttpAdapter. I get what you are saying now.

**Comment by jmdobry** [comment]
In v3, the `raw` option when passed to the `create`, `find`, `destroy`, etc. methods will cause the adapter to return more meta information about the operation. In the case of the http adapter, this includes response headers. The basic caching that v3 ships with is just a simple "have I made this read request already?". So in v3 (more so than in v2), with the myriad of hooks available, one could devise a caching scheme that relies on etags, headers, or whatever meta information the adapter can give you.

The main goal of v3 was not to help "add all the features", but make things more flexible so it doesn't get in your way when you want to do something like this. Marking this as closed.

**Comment by rquast** [comment]
the hooks should get around this issue... great addition. thanks!
