### ISSUE TITLE
DSEject not available on instances

### ISSUE THREAD

**Issue by WillsB3** [js-data/js-data#157]
The docs say that DSEject can be called as a method on a model instance: 

```js
Instance#DSEject([, options]) - Where Instance is an instance of a Resource. Note this ejects the item from the store, but you still have a reference to the object, so the object won't get garbage collected just yet.
```

However, as discussed, this does not appear to the case:

![screen shot 2015-06-08 at 11 50 01](https://cloud.githubusercontent.com/assets/868834/8041119/ed2613d6-0e0d-11e5-9730-f89bb2cdb9f3.png)

Feels like it should be added as it's useful to be able to call eject when you only have access to the model instance.

**Comment by jmdobry** [comment]
Will be in 2.x

**Comment by WillsB3** [comment]
:+1:
