### ISSUE TITLE
Create with upsert option bypasses custom update method

### ISSUE THREAD

**Issue by jessehouchins** [js-data/js-data#158]
I have a service that uses a custom update method to do some crazy stuff. However, the custom method is skipped when update is invoked from a create using the `upsert` option. The code in question is here: https://github.com/js-data/js-data/blob/master/src/datastore/async_methods/create.js#L17

So, questions:

1. Does this seem like a valid bug?
2. Couldn't you just replace `_this.update` with `definition.update`
3. Should definition methods be used everywhere they are called from internal code, instead of DS methods?

**Comment by jmdobry** [comment]
> Should definition methods be used everywhere they are called from internal code, instead of DS methods

That's a good point. I think this kind of change would have to go into 2.x though, because it could be a breaking change.

**Comment by jessehouchins** [comment]
ok
