### ISSUE TITLE
Computed properties must not be relayed to the adapter. 

### ISSUE THREAD

**Issue by LoicMahieu** [js-data/js-data#161]
Computed properties must not be relayed to the adapter. 
Demo: http://requirebin.com/?gist=dc098cd7c374e59da3eb

I use `js-data-sql` as adapter. This adapter use all properties when it build the SQL query, so it fall in a SQL exception because it try to set/update a computed properties which is not a column that exists.

**Comment by jmdobry** [comment]
Until I can fix this (I think I'm going to switch computed properties to using non-enumerable property accessors), you're going to have to use `DS#update` instead of `DS#save`. With `DS#update` you manually pass in the attributes that are to be updated.

**Comment by LoicMahieu** [comment]
Thanks for response. I moved it to a instance method... Not the best way but works in my case. `update` would not fit for me because I don't know which attributes has been changed.

Feel free to close the issue or keep it for reminder. Thanks for your work on js-data!

**Comment by jmdobry** [comment]
Added a new options `omit`, which should be an array of strings or regexes of keys to omit when sending data to adapters. Can be set globally, per-resource, or during a method call. By default will include the names of computed properties.
