### ISSUE TITLE
Return query metadata as second parameter from a promise.

### ISSUE THREAD

**Issue by rquast** [js-data/js-data#162]
When needing to cache data on the server side, using the fallback strategy can be helpful. However, there is no way to determine what adapter was used for returning the data. Consider the following scenario (from JSData on the Server - http://www.js-data.io/v1.8.0/docs/jsdata-on-the-server).

```
app.get('/user/:id', function (req, res, next) {

  // automatically attempt to find the user with id "1" in Redis 
  // (see "strategy" and "fallbackAdapters")
  // if it's not in Redis then look in Rethinkdb
  return User.find(1).then(function (user) {

    // ensure the user is cached in Redis
    // remember to do this whenever data is updated
    User.update(1, user, { adapter: 'redis' });

    req.status(200).send(user).end();
  }).catch(next);
});
```

There are two problems with this example. The first might be an oversight - if the record doesn't exist in redis, it should create it rather than update.

The second problem is that the code above would continuously update the redis record, even if the data was returned from redis (because of the fallback strategy would select redis first). If you could do something like this, it would be much better:

```
app.get('/user/:id', function (req, res, next) {

  // automatically attempt to find the user with id "1" in Redis 
  // (see "strategy" and "fallbackAdapters")
  // if it's not in Redis then look in Rethinkdb
  return User.find(1).then(function (user, metadata) {

    // only update if not redis
    if (metadata.adapter != 'redis') {
      // ensure the user is cached in Redis
      // remember to do this whenever data is updated
      User.update(1, user, { adapter: 'redis' });
    }

    req.status(200).send(user).end();

  }).catch(next);
});
```

The only other way to get around this problem is to not use strategy/fallback and catch errors then nest updates and creates.

**Comment by jmdobry** [comment]
The obstacle here is that promises only have 1 return value. Some promise implementations have a `spread` method that can take an array return value and "spread" its contents out as arguments to the callback. So, if js-data were to have a "mode" where metadata is also return, then `DS#find` would resolve with an array, and you would have to have a promise implementation that has `spread`, otherwise you'd be working with the array return value all the time. 

I can't force the array return value on people, as that's a major breaking change, but I can sure make it optional. Perhaps I could also have js-data polyfill whatever promise implementation is being used with a `spread` method.

**Comment by rquast** [comment]
What about a configuration flag to return a data object that contains both the data and metadata?

**Comment by rquast** [comment]
{ 'data': ... , 'metadata': ... }

**Comment by rquast** [comment]
or even an object that contains all of the metadata as fields, then a body which is the data.

**Comment by rquast** [comment]
return User.find(1).then(function (user) {

if ( user.metadata.adapter != 'redis' ) {
  User.update(1, user.data, { adapter: 'redis' });

**Comment by jmdobry** [comment]
I'm introducing a new option called `returnMeta`. It will default to `false`. If you set it to `"array"` then you can do:

```js
.spread(function (response, meta) { ... });
```

If you set it to `"object"` then you can do:

```js
.then(function (data) {
  data.response;
  data.meta;
});
```

**Comment by jmdobry** [comment]
Right now I've only got the metadata including the name of which adapter was used. I'm going to explore attaching additional metadata.
