### ISSUE TITLE
Relationship keys not configurable

### ISSUE THREAD

**Issue by stevehipwell** [js-data/js-data#164]
With the following resource defined I'm attempting to load the *Activity* relations. I would expect the call to load *applicationUnit* to look like `http://test.com/units/1` but instead it looks like `http://test.com/units?applicationUnitId=1`. Is there a solution to this as otherwise it's a deal breaker?

```
DS.defineResource({
  name: 'unitType',
  endpoint: '/unittypes',
  serialize: (resourceName: string, data: IUnitType) => {
    return _.omit(data, 'units');
  },
  relations: {
    hasMany: {
      unit: {
        foreignKey: 'unitTypeId',
        localField: 'units'
      }
    }
  }
});

DS.defineResource({
  name: 'unit',
  endpoint: '/units',
  serialize: (resourceName: string, data: IUnit) => {
    return _.omit(data, 'unitType');
  },
  relations: {
    belongsTo: {
      unitType: {
        parent: true,
        localKey: 'unitTypeId',
        localField: 'unitType'
      }
    }
  }
});

DS.defineResource({
  name: 'business',
  endpoint: '/businesses',
  serialize: (resourceName: string, data: IBusiness) => {
    return _.omit(data, 'farms');
  },
  relations: {
    hasMany: {
      farm: {
        foreignKey: 'businessId',
        localField: 'farms'
      }
    }
  }
});

DS.defineResource({
  name: 'activity',
  endpoint: '/activities',
  serialize: (resourceName: string, data: IFarm) => {
    return _.omit(data, ['business', 'applicationUnit']);
  },
  relations: {
    belongsTo: {
      business: {
        parent: true,
        localKey: 'businessId',
        localField: 'business'
      }
    },
    hasOne: {
      unit: {
        foreignKey: 'applicationUnitId',
        localField: 'applicationUnit'
      }
    }
  }
});
```

**Comment by jmdobry** [comment]
Can you post some actual data? What do your objects look like when you're making the `loadRelations` call?

**Comment by stevehipwell** [comment]
The *Activity* data looks like blow when the load relations call is made.

```
{
  id: 1,
  businessId: business.id,
  type: 1,
  name: 'Activity 1',
  applicationUnitId: 1,
  defaultRate: 1,
  unitPrice: 4.7
}
```

If I change the name of *applicationUnitId* to *unitId* then it works perfectly.

**Comment by jmdobry** [comment]
If you change the relation to `localKey` instead of `foreignKey`, then it should go GET /unit/1

```js
DS.defineResource({
  name: 'activity',
  endpoint: '/activities',
  serialize: (resourceName: string, data: IFarm) => {
    return _.omit(data, ['business', 'applicationUnit']);
  },
  relations: {
    belongsTo: {
      business: {
        parent: true,
        localKey: 'businessId',
        localField: 'business'
      }
    },
    hasOne: {
      unit: {
        localKey: 'applicationUnitId',
        localField: 'applicationUnit'
      }
    }
  }
});
```

**Comment by stevehipwell** [comment]
Sorry, changing it to unit actually didn't work, my unit test was just not working correctly.

**Comment by stevehipwell** [comment]
Thank you.

**Comment by jmdobry** [comment]
Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, JSData, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [Gitter Channel](https://gitter.im/js-data/js-data) or the [mailing list](https://groups.io/org/groupsio/jsdata).
