### ISSUE TITLE
global leak

### ISSUE THREAD

**Issue by SystemParadox** [js-data/js-data#165]
There's a global leak in `src/datastore/sync_methods/defineResource.js`:

```
// Proxy DS methods with shorthand ones
var fns = ["registerAdapter", "getAdapter", "is"];

for (key in _this) {
    if (typeof _this[key] === "function") {
        fns.push(key);
    }
}
```

This leaks `key`.

I tried fixing this, but it seems to be caused by webpack?

**Comment by jmdobry** [comment]
Yes, very weird. The `var` there in the source, but after webpack runs it's gone. I'll have to keep fiddling with it.

**Comment by SystemParadox** [comment]
Using `let` instead of `var` fixes it.

`dist` seems to be included in the git repository? Is this a mistake or should I rebuild and commit this as well?

**Comment by jmdobry** [comment]
Don't commit the files in `dist`, I'll rebuild and commit those when I make a release.

**Comment by SystemParadox** [comment]
It's a babel issue: https://github.com/babel/babel/issues/1819
