### ISSUE TITLE
Audit browser compatibility of js-data's code and...

### ISSUE THREAD

**Issue by jmdobry** [js-data/js-data#172]
make a decision as to exactly what level of browser compatibility to support. This will probably allow some code to be dropped from the library.

**Comment by internalfx** [comment]
Can we drop IE8 officially?

**Comment by jmdobry** [comment]
This may involve breaking changes, so it should be part of #196

**Comment by jmdobry** [comment]
In v3 support for anything less than ES5 has been dropped, allowing the codebase to be slimmer.
