### ISSUE TITLE
Any plan to integrate third-party in memory database

### ISSUE THREAD

**Issue by mfilotto** [js-data/js-data#175]
Hi,
I wonder if a third party in memory database integration like LokiJS would be relevant inside js-data architecture.
Do you think it could be used in place of your in-memory cache, through an adapter for the synchronous API maybe ?

**Comment by jmdobry** [comment]
I've had thoughts about doing something like, but I wasn't able to look into it for the 2.0 release. Making this possible might require some serious architecture changes. I'll keep this in mind for a 3.0 release.

**Comment by jmdobry** [comment]
Playing around with this idea here: https://github.com/js-data/js-data/tree/swappable-store

Out of 155 tests, only 1 failed when using LokiJS as the internal in-memory store.

**Comment by mfilotto** [comment]
Awesome !!
Have you any performance tests to compare solutions ?

**Comment by jmdobry** [comment]
nope

**Comment by mfilotto** [comment]
Loki' has a bunch of benchmarks tests we could use.
Do you want a PR on this one ?

**Comment by jmdobry** [comment]
I'm still in the exploration phase, so hold off for now.

**Comment by mfilotto** [comment]
OK. I stay tune and play a bit with this branch

**Comment by mfilotto** [comment]
@jmdobry Hi Jason, any feedback from your exploration ?
Thanks

**Comment by jmdobry** [comment]
The in-memory store of v3 will be much improved in that it will support secondary indexes. For any other storage engine, I recommend writing an adapter for it, e.g. js-data-loki would be an adapter that uses LokiJS as its persistence layer.

**Comment by mfilotto** [comment]
Where could I find some info/doc on that topic please

**Comment by jmdobry** [comment]
http://www.js-data.io/docs/working-with-adapters#custom-adapters

**Comment by jmdobry** [comment]
Thanks to #184 there is much less need for this. And, in v3 Models use instances of Collection, so you could easily swap out the collection instance for something else that implements the same API (a wrapper around LokiJS, perhaps). So, marking this as closed.
