### ISSUE TITLE
JSData Schema integration discussion

### ISSUE THREAD

**Issue by jmdobry** [js-data/js-data#180]
JSData 2.x does absolutely zero validation or anything else for model schemas. It doesn't even know about schemas. Many different ORMs have various levels of schema integration. This thread is a discussion on what type and level (if any) of schema integration JSData should have. 

- Should it allow schema definition?
- Should it follow JSON Schema?
- Should it allow field mappings?
- camelCase to snake_case mappings?
- Restricted fields (server side adapters)?

What's it gonna be?

**Comment by thebigredgeek** [comment]
Doesn't 2.x support the schema property within the `DS#defineResource` config object?

**Comment by jmdobry** [comment]
Nope, see #122 and https://github.com/js-data/js-data/releases/tag/2.0.0-beta.1

**Comment by davidpp** [comment]
Requirement on this vary greatly.  I would be in favour of a JSON Schema plugin, but don't think it should be in "core".

In my case, I implemented it using meta.schema and a validateFilter.  The features that I'm missing (some might benefit from new hooks in core I think, still have to investigate) :

- Ability to create an Object without persisting (Create without a save) with existing properties from the schema.
- Couldn't specify id as a required field as it do not exist yet in the validate hook
- read-only fields (ex: calculated) (I'm pretty new to both js-data and JSON schema, so this one might be already possible?)
- Automatic relation definition through son-schema standard.  (Basically, create resources through config VS code.)

**Comment by aaronroberson** [comment]
If the Mongoose Schema is not based on the JSON Schema plugin it would be great to have Schema adapters. I would love to re-use my model schema for both mongoose and js-data. This way I could put them in a separate JSON file and a single schema for both cases.

**Comment by jmdobry** [comment]
> read-only fields (ex: calculated) 

Already possible. They're called "computed properties".

As it stands, js-data provides the `beforeValidate`, `validate`, `afterValidate` model lifecycle hooks where users can do whatever kind of schema validation, adding defaults values, etc. that they want. I think that's sufficient for the foreseeable future.
