### ISSUE TITLE
The Query syntax 'contains' method should allow objects and functions for filtering.

### ISSUE THREAD

**Issue by ajbogh** [js-data/js-data#185]
The contains method filters simple array properties, but it should also support complex data structures such as objects and comparison functions. 

Filtering contains by objects:

    where: {
        'property': 'value',
        'users': {
            'contains': {
                'firstName': 'Fred'
            }
        }
    }

Filtering contains by functions:

    where: {
        'property': 'value',
        'users': {
            'contains': function(user){
                return user.role === 'admin';
            }
        }
    }

**Comment by jmdobry** [comment]
More complex contains functionality will not be possible from the adapters' perspectives, but if you just need more advanced filtering for the data in the store, in you can do:

```js
var filteredUsers = store.filter('user', {
  property: 'value'
}).filter(function (user) {
  return user.role === 'admin'
})
```

```js
var filteredUsers = store.filter('user', {
  property: 'value'
}).filter(function (user) {
  // complex contains
  var hasFred = false
  user.users.forEach(function (_user) {
    if (_user.firstName === 'Fred') {
      hasFred = true
      return false
    }
  })
  return hasFred
})
```

Functions obviously can't be reasonably hashed/serialized and read by the adapters, and some data sources don't have the data types of functionality for more complex contains functionality. I avoid adding operators to the query syntax that do not work that same (or very similar) across all adapters.
