### ISSUE TITLE
No way to hook into error events globally

### ISSUE THREAD

**Issue by thebigredgeek** [js-data/js-data#187]
Right now there is no reliable way to hook into outgoing requests (for something like a loading animation, or disabling a save button) because it isn't possible to hook into failed XHR which is required to update state when the request finishes, albeit with a failure.

I can do something like this (via angular):

```
.run(['DS', '$rootScope', function(DS, $rootScope){
    angular.extend(DS.defaults, {
      beforeCreate: function (Resource, instance, cb) {
        $rootScope.$evalAsync(function(){
          instance.$$creating = true;
          cb(null, instance);
        });
      },
      afterCreate: function (Resource, instance, cb) {
        $rootScope.$evalAsync(function(){
          instance.$$creating = false;
          cb(null, instance);
        });
      },
      beforeUpdate: function (Resource, instance, cb) {
        $rootScope.$evalAsync(function(){
          instance.$$updating = true;
          cb(null, instance);
        });
      },
      afterUpdate: function (Resource, instance, cb) {
        $rootScope.$evalAsync(function(){
          instance.$$updating = false;
          cb(null, instance);
        });
      },
      beforeDestroy: function (Resource, instance, cb) {
        $rootScope.$evalAsync(function(){
          instance.$$destroying = true;
          cb(null, instance);
        });
      },
      afterDestroy: function (Resource, instance, cb) {
        $rootScope.$evalAsync(function(){
          instance.$$destroying = false;
          cb(null, instance);
        });
      }
    });
  }])
```
But this doesn't work if an error occurs, because the `instance.$$<action>` property doesn't get set back to false when a request fails (like with a 401).  Any thoughts on how we should implement this?  I was thinking something along the lines of:

`DS#afterCreateError`
`DS#afterUpdateError`
`DS#afterDestroyError` 

This would avoid breaking changes, that could POSSIBLY be made if we simply call `DS#after<action>` with errors, passing the error object in as a 4th param?

Let me know what you think @jmdobry .  I am down to submit a PR for either case.

**Comment by jmdobry** [comment]
This would be easy to implement, and without breaking changes. My question is where to put the hook in the flow? Take [`DS#create`](https://github.com/js-data/js-data/blob/master/src/datastore/async_methods/create.js) for example. You can see the promise chain of `.then`s in the code. Where would we attach `afterCreateError`?

```javascript
  return _this.adapters[adapter].create(definition, DSUtils.omit(attrs, options.omit), options);
})
.catch(err => options.afterCreateError.call(attrs, options, err))
.then(attrs => options.afterCreate.call(attrs, options, attrs))
.then(...)
.then(...);
```

Or 

```javascript
  return _this.adapters[adapter].create(definition, DSUtils.omit(attrs, options.omit), options);
})
.then(attrs => options.afterCreate.call(attrs, options, attrs))
.then(...)
.then(...)
.catch(err => options.afterCreateError.call(attrs, options, err))
```

The first option allows you to potentially handle the error and still get back into the Model lifecycle flow, finishing out the create.

The second option only handles any errors at the very end, without any option to still complete the flow.

Thoughts?

**Comment by antoinebrault** [comment]
Hi, i was looking exactly for the same hooks to show a loading in a toast on each model create/update/delete on a model.

I think you should implement the first option because it's more flexible.

**Comment by jmdobry** [comment]
What I'm deciding to do is implement the second option in js-data, and then eventually implement generic error handlers within each adapter, so eventually both options will be available to you.

**Comment by zuzusik** [comment]
I am looking for something like this right now. Looks like this functionality got lost when implementing 3.0

**Comment by crobinson42** [comment]
Do you have a code example or more details?

**Comment by zuzusik** [comment]
@crobinson42 first post in this issue has pretty much a detailed explanation, but to make it short, I would like to be able to do something like:

```js
this.DS.getMapper('SomeMapper').on('createManyError', handler);
```

**note: ** `after<Action>` hooks don't fire on errors

For now it can be worked around on Adapter level using it's `responseError` like this:

```js
new HttpAdapter({
  responseError: (err)  => {
    this.DS.getMapper(err.config.name).emit(`${err.config.op}Error`);

    return Promise.reject(err);
  }
});
```

This perfectly fits in what I need, but would be nice to have something like this out of the box in core functionality, probably on Mapper level.
