### ISSUE TITLE
Support localKey for hasMany relationships

### ISSUE THREAD

**Issue by gtelljohann** [js-data/js-data#188]
Restricting the hasMany relationship to just using a foreign key makes a lot of sense for a SQL-style database structure, but for a Mongo-style database structure, which better supports embedded arrays in its documents, it would be nice to be able to define a relationship for a local key.  

For example, let's say I have group documents which contain an array of member ids:
```javascript
{
  name: 'JSData Contributors',
  members: [
    ObjectId('490h92398hg'),
    ObjectId('89502hg010gh')
  ]
}
```

Because members can also be part of more than one group, this would be represented by a SQL join table rather than an embedded array, but in this case it would be helpful to be able to say:
```javascript
var Group = DS.defineResource({
  name: 'group',
  relations: {
    hasMany: {
      user: {
        localKey: 'members',
        localField: '_members'
      }
    }
 }
})
```

**Comment by jmdobry** [comment]
You already can. See https://github.com/js-data/js-data/blob/master/test/browser/datastore/async_methods/loadRelations.test.js#L337

**Comment by gtelljohann** [comment]
Oh great!  The documentation here (http://www.js-data.io/docs/relations) makes it sound like you can only use a foreign key: 
```
// hasMany uses "localField" and "foreignKey"
```

I submitted an edit suggestion on your documentation to reflect the update.  Thanks!
