### ISSUE TITLE
support for regex in filter query

### ISSUE THREAD

**Issue by pdemilly** [js-data/js-data#189]
Would be a nice addition to queries if js-data could support Regex in queries. Something like

Resource.findAll( { where: { foo: /^bar$/i } } );

another possible solution would be to add an option like 

Resource.findAll ({ where: { foo: 'bar' } }, { icase: true })

Thanks

**Comment by aaronroberson** [comment]
I currently handle this on the back-end with Mongoose for MongoDB:

```
_.each(fields, function(value, field) {

    // Check if value is an object
    if (/^{.*}$/.test(value)) {

      // Support JSON objects for range queries, etc.
      fields[field] = JSON.parse(value);

      // Check if value is not an ObjectId
    } else if (!/^[0-9a-fA-F]{24}$/.test(value)) {

      // Support Regex for LIKE queries
      fields[field] = {$regex: new RegExp(value, 'i')};
    }
  });
```

You can also perform a SQL like WHERE statement with the following:
```
if (params.where) {
    fields.$where = function() {
      for (var key in this) {
        if (this[key] === params.where) {
          return true;
        }
        return false;
      }};
  }
```

Would definitely be cool to see this supported in the front-end.

**Comment by jmdobry** [comment]
I think this feature was taken care of by the addition of the `like` operator. `DS#filter` supports it for sure, but I'm not sure all adapters have implemented it yet.
