### ISSUE TITLE
Planning 3.0

### ISSUE THREAD

**Issue by jmdobry** [js-data/js-data#196]
See #264 for progress.

#### Implemented in v3
* Support ES6 classes with possibly annotations to define relationships
* Secondary indexes for the in-memory cache

#### Can easily be done yourself in v3
* LRU cache ejection.

#### Out of scope for v3
* OData Adapter
* JSON API Adapter

**Comment by Billskate** [comment]
Is there any plan to support an OData adapter?

**Comment by techniq** [comment]
Any plan to support ES6 classes with possibly annotations to define relationships?

**Comment by jmdobry** [comment]
> Is there any plan to support an OData adapter?

None from me.

> Any plan to support ES6 classes with possibly annotations to define relationships?

I'll have to look into that.

**Comment by internalfx** [comment]
LRU cache ejection.

**Comment by pdemilly** [comment]
Having to define a loading mode for relations of eager/lazy/adhoc with adhoc being the current implementation and default.

Some have proposed some implementation already:

```
function lazyLoad(Resource, definition, instance, getter) {
  Resource.loadRelations(instance, definition.relation);
  return getter();
}

DS.defineResource({
  name: 'User',
  relations: {
    hasMany: {
      Post: {
        localField: 'Posts',
        foreignKey: 'user_id',
        get: lazyLoad
      }
    }
  }
});
```
and:
```
function eagerLoad(Resource, instance) {
  if (Array.isArray(instance)) {
    instance.map(eagerLoad.bind(null, Resource));
    return;
  }
  let relations = Resource.relationList.map(def => def.relation)
  Resource.loadRelations(instance, relations);
}

DS.defineResource({
  name: 'User',
  relations: {
    hasMany: {
      Post: {
        localField: 'Posts',
        foreignKey: 'user_id'
      }
    }
  },

  afterInject: eagerLoad,
  afterCreateInstance: eagerLoad
});
```

**Comment by pdemilly** [comment]
support for http://jsonapi.org ?

**Comment by jmdobry** [comment]
Some thoughts on the decentralization of JSData architecture:

```js
// A Resource doesn't have to be attached to a store
let Base = JSData.Resource.extend({
  name: 'base',
  // other global defaults here
  idAttribute: '_id'
})

let NoCacheBase = Base.extend({
  cacheResponse: false
})

// Inheritance
let User = Base.extend({
  name: 'user',

  // Instance methods
  methods: {
    say() {
      return 'hi'
    }
  },

  // Static methods
  foo() {
    return 'bar'
  }
})

User.cacheResponse // true

// More inheritance
let Developer = User.extend({
  name: 'developer',

  // Also mixins!
  mixins: [NoCacheBase]
})

Developer.cacheResponse // false

let Comment = Base.extend({
  name: 'comment'
})

let user = new User({ name: 'John' })
let developer = new Developer({ name: 'Sally' })

developer.say() // "hi"

Developer.foo() // "bar"

developer instanceof Developer // true
developer instanceof User // true

let user2 = User.inject({ name: 'Bob' })
let user3 = User.inject({ _id: 3, name: 'Bill' })

User.get(2) // undefined
user3 === User.get(3) // true

Comment.belongsTo(User)
User.hasMany(Comment)
```

and/or

js
```
// When you create a store, a "base" resource will be made for you.
let store = new JSData.DS({
  idAttribute: '_id'
})
let Base = store.getResource('base')

// Or, you can make your own.
let Base = store.defineResource({
  name: 'base',
  idAttribute: '_id'
})

// --------------------------------------

let User = store.defineResource({
  name: 'user',
  extends: 'base',

  // Same as User.hasMany(Comment)
  relations: {
    hasMany: {
      comment: {}
    }
  }
})

let Comment = store.defineResource({
  name: 'comment',
  extends: 'base',

  // Same as Comment.belongsTo(User)
  relations: {
    belongsTo: {
      user: {}
    }
  }
})
```

For plugins/extensions, maybe this could work:

```js
// JSData Core can be smaller, just the in-memory store
let Foo = JSData.Resource.extend()

// change detection functionality - its own module
typeof Foo.hasChanges // undefined

// async functionality (for working with adapters) - its own module
typeof Foo.findAll // undefined

// immutability - its own module
typeof Foo.set // undefined
typeof Foo.mergeDeep // undefined

let Base = JSData.Resource.extend({
  name: 'base',
  mixins: [JSDataChangeDetection, JSDataAsync, JSDataImmutable]
})

let User = JSData.Resource.extend({
  name: 'user'
})

typeof User.hasChange // "function"
typeof User.findAll // "function"
typeof User.set // "function"
typeof User.mergeDeep // "function"
```

It would be nice to be able to define your Resources as ES6 classes, but ES6 classes don't allow the definition and extension of static class properties, like `bypassCache`, `cacheResponse`, etc.

We'd have to do this:

```js
class Base {
  static cacheResponse() {
    return true
  }
}

class User extends Base {
  static cacheResponse() {
    return false
  }
}
```

Which is either crazy or awesome.

What I've suggested here could mean some serious breaking changes for 3.0

**Comment by techniq** [comment]
@jmdobry I like a pretty much everything you're presenting.  I would love to have ES6 class support, but understand the limitations of the static properties.  I do something similar to support `$inject` in my Angular 1.x controllers/etc 

```js
class SomeController {
  static get $inject() { return ['foo', 'bar', 'baz']; }

  ...
}
```
or
```js
class SomeController {
  ...
}
SomeController.$inject = ['foo', 'bar', 'baz'];
```

worth noting is [ES class fields and static properties](https://github.com/jeffmo/es-class-static-properties-and-fields) are currently stage 1 and would support:

```js
class Base {
  static cacheResponse = true
}

class User extends Base {
  static cacheResponse = false
}
```

Babel has [support](http://babeljs.io/docs/plugins/transform-class-properties/) for this transformation although I'm not using it on any of my projects yet to understand any of it's limitations

---

I like the modularity and use of mixins, but I would hate to loose too much of the approachability of the project if too much isn't included by default (but then again, a good `Base` class and you're good to go).  Could also help keep the compiled size of the project down as not all users will need all features/mixins.

**Comment by internalfx** [comment]
-Rant

I'm starting to feel that I'm in the minority on the `class` debate. I have to agree with crockford that the ES6 `class` is gonna be a bad part. It still doesn't work like a real class, but now we officially call it a class. I personally have been not using classes, just objects. If I want to have an object delegate to another, I use `Object.create()`, much simpler.

-EndRant

@jmdobry I have a new implementation of secondary indexes that now supports compound keys!
It's much simpler too...less code.

Example: index users by city and age!
```javascript
    index.set(['Denver', 29], '1')
    index.set(['Denver', 28], '2')
    index.set(['Phoenix', 20], '3')
    index.set(['Phoenix', 34], '4')
    index.set(['Phoenix', 21], '5')
    index.set(['Denver', 25], '6')
    index.set(['Phoenix', 24], '7')

// uses greater than, and less than keys, so it's easy to read the syntax...
console.log(index.query({'>': ['Denver'], '<': ['Seattle']}))
// [ '3', '5', '7', '4' ]

// Also supports greater than or equal to, and the reverse.
console.log(index.query({'>=': ['Denver', 28], '<=': ['Denver', null]}))
// [ '2', '1' ]

// Passing null means un-bounded, goes to the end of the index.
console.log(index.query({'>=': [null], '<=': [null]}))
// [ '6', '2', '1', '3', '5', '7', '4' ]
```
You'll notice that all the results are sorted by city then age...

It also works for simple indexes as well, let me know if this could be of use and I'll open source it as a npm lib.

**Comment by jmdobry** [comment]
This is different than your btree thing?

**Comment by internalfx** [comment]
Yes

**Comment by jmdobry** [comment]
how is it different?

**Comment by internalfx** [comment]
It uses sorted arrays with binary search...

Code: https://gist.github.com/internalfx/d805d7db9eaa2412905c

**Comment by jmdobry** [comment]
A major limitation of ES6 classes is the inability to execute code during the class definition. `DS#defineResource` executes a lot of code when it is called. Here is something I was playing around with in the babeljs.io REPL:

```js
function defaults (target) {
  target.$idAttribute = 'id'
}

function index(target) {
  target.$index = {}
}

function belongsTo(Resource, options = {}) {
  return function (target) {
    let localField = options.localField || Resource.name.toLowerCase()
    let localKey = options.localKey || Resource.name.toLowerCase() + 'Id'
    Object.defineProperty(target.prototype, localField, {
      get() {
        return Resource.get(this[localKey])
      },
      set(parent) {
        this[localKey] = parent[Resource.idAttribute]
      }
    })
    return target
  };
}
// Decorators are the only way to execute code at design time
@defaults
@index
class Resource {
  constructor(props) {
    for (var key in props) {
      if (props.hasOwnProperty(key)) {
        this[key] = props[key]
      }
    }
  }
  // Instance methods, which can delegate to static methods
  hasChanges() {
    return this.constructor.hasChanges(this[this.constructor.idAttribute])
  }
  
  // Static class properties
  static get idAttribute() { return this.$idAttribute }
  static set idAttribute(value) { return this.$idAttribute = value }
  
  // Static methods
  static hasChanges(id) {
    return 'foo'
  }
  static get(id) {
    return this.$index[id]
  }
  static inject(props, options) {
    var Constructor = this
    if (!(props instanceof Constructor)) {
      props = new Constructor(props)
    }
    return this.$index[props[this.idAttribute]] = props
  }
  static belongsTo(Resource, options) {
    return belongsTo(Resource, options)(this) 
  }
}

class User extends Resource {}
@belongsTo(User)
class Post extends Resource {}
@belongsTo(User)
@belongsTo(Post)
class Comment extends Resource {}

// Could also do this:
// Post.belongsTo(User, { ... })

console.log(User.name)
console.log(User.idAttribute)

let user = User.inject({ id: 1, name: 'John' })
let user2 = new User({ id: 2, name: 'Sally' })
console.log(user, user instanceof User)
console.log(user2, user2 instanceof User)
console.log(user2 === User.inject(user2))
console.log(user2 === User.get(2))
console.log(User.hasChanges(2), user2.hasChanges())

let comment = Comment.inject({ id: 1, userId: 1, postId: 9 })
Post.inject({ id: 9 })
console.log(comment.user, comment.post)
```

**Comment by techniq** [comment]
:+1: I like the decorator approach myself (but I was also already [on board](https://github.com/js-data/js-data/issues/196#issuecomment-136685376)).  They are also being embraced by Angular 2.0 (and [React](https://twitter.com/sebmarkbage/status/571389309586051072) it appears)

**Comment by jmdobry** [comment]
Yeah, I'm struggling to get ES6 classes + decorators to be able to do everything `DS#defineResource` does.

**Comment by jmdobry** [comment]
Here's [a Gist](https://gist.github.com/jmdobry/519a375009cd744b8348) where I'm recording stuff I come up with.

**Comment by techniq** [comment]
@jmdobry what's some examples of limitations your running into.

Might be worth starting a 3.0 branch soon so we can hack around and write some tests to help flesh out them problems.

My plate is pretty full currently with work/overtime but I'll try to get a few hours here and there to help out.

**Comment by jmdobry** [comment]
The #1 limitation of ES6 classes is that you can't execute code at design time, because a class is just a declaration. When someone executes `let User = store.defineResource({...})`, then `defineResource` gets executed. `defineResource` gets to do a bunch of stuff like validate its input, setup relations, computed properties, events, etc. When someone writes `class User extends JSData.Resource {...}` nothing gets executed.

The way around this is with decorators:

```js
@doEverythingDefineResourceUsedToDo
class Resource {...}
```

```js
class User extends JSData.Resource {...}
```

Right now I'm figuring out a clean way of being able to do everything `defineResource` did without a giant `@doEverythingDefineResourceUsedToDo` decorator. Basically, I'm splitting bits of `defineResource` out into individual decorators so they can be composed as needed.

#2 limitation (related to #1), you can't define static/instance properties unless you use get/set, e.g.

```js
class Resource {
  static get idAttribute() { return this.$idAttribute }
  static set idAttribute(value) { return this.$idAttribute = value }
}
Resource.idAttribute = 'id'
```

which is lame. All I want is:

```js
class Resource {
  static idAttribute: 'id'
}
```

__Another concern: change detection__

Chrome is dropping support for Object.observe, and so should js-data I think. But, I'd still like to have change detection, even if it moves to its own module/plugin. Backbone.js does this be _requiring_ the use of `.get` and `.set` on its model instances, but doing this would be a major shift from js-data's POJO philosophy, which is that you can interact with instances as if they're POJOs and still get the cool functionality. 

Now, the only way to maintain current POJO-ness _and_ get change detection (without 3rd-person observation, e.g. Object.observe) is to use ES5 getter/setters, but there's no way to dynamically add those to non-function properties without proxies, which won't be supported by all major browsers anytime soon. The only other option is to require the user to define a schema for a resource, so we know which properties to make the getters/setters for. Another issue with using getter/setters is that the property can't simultaneously hold a value, so the actual value would have to be store somewhere else. Backbone Model instances have an attributes property where the data is stored. Thinking...

**Comment by techniq** [comment]
Regarding #2, you can with babel if you are using stage1 (or however babel 6 configures it now).  See my [comment](https://github.com/js-data/js-data/issues/196#issuecomment-153556359) a few days ago.  It gives you

```js
class Resource {
  static idAttribute = 'id'
}
```

---

Regarding change detection: I saw that about Object.observe (and that all the potential users of it: ie Polymer (removed with the 1.x rewrite), Angular 2.x (not using it), etc, and it seems like it's now we're all waiting for Proxy to land to give us this capability (as their's no way to shim them from what I've read).

I REALLY prefer the POJO style (with decorators when needed) and was a big reason I came over to using js-data-sql on the backend over bookshelf.js which is backbone inspired (always hard to remember when I need to `.get()/`.set()` something vs. just de-referencing the variable/etc).

For change detected properties, could we require the user to decorate a property on their class to have it observed for change detection, such as:

```js
class Person {
  @observe // or @whatever
  name;

  @observe
  address;

  ...
}
```

This is using class instance fields as outlined in the ES proposal.  The user wouldn't have to declare all their propeties, just the ones they wanted to observe...

This would be putting more reliance that the spec lands (and on babel), but the user would already be leaning on babel for other things, and we'll be sure to always offer a "native" ES5 approach for the paranoid/concerned that won't be as elegant to look at, but functionally the same.

Might be nice to make sure we have a good user story for all features for the following:
- No transpiling required ES5 (js-data can transpile to ES5, but not require the user to have transpiling setup to use js-data)
- Transpiling with only es2015 (es6) features in the space (no stage-# stuff)
- Transpiling with anything babel/[ecma262](https://github.com/tc39/ecma262) has to offer (maybe no stage-0 stuff if we can :)).  I know it would be best to stay off the lower stage items as much as we can, but even some items at a lower stage (decorators being a huge one) seem like they have too much momentum to be derailed (Angular 2 / typescript)

**Comment by jmdobry** [comment]
Ah yes Babel, I recently ran into https://github.com/babel/babel/issues/2702

**Comment by techniq** [comment]
I subscribed to see if/when it's resolved

**Comment by jmdobry** [comment]
Where does the `useClass` feature fit in with `class User extends JSData.Resource {...}` and `var User = JSData.Resource.extend({...}, {...})`?

**Comment by jmdobry** [comment]
Some experimentation: https://github.com/js-data/js-data/blob/v3/src/core/resource.js

**Comment by techniq** [comment]
Regarding `useClass` - Seems like `JSData.Resource` is both a service and data object.  Most of the distinction is "static methods = service" and "instance methods = data object".

Should JSData.Resource be a decorator instead, which would allow `useClass` functionality to be through inheritance?

```js
@resource
class User extends BaseUser { ... }
```

**Comment by techniq** [comment]
maybe also allow the belongs to on instance properties as well (which will be make the localFIeld be the instance property)

```js
@resource
@belongsTo(User, { localKey: 'myUserId' })
class Post {...}
 
@resource
@belongsTo(User)
@belongsTo(Post, { localField: '_post' })
class Comment {...}
```

```js
@resource
class Post {
  @belongsTo(User, { localKey: 'myUserId' })
  user;  
}
 
@resource
class Comment {
  @belongsTo(User)
  user;

  @belongsTo(Post)
  post;
}
```

**Comment by jmdobry** [comment]
I was just thinking we could encourage this:

```js
class BaseUser extends JSData.Resource {...}
class User extends BaseUser {...}
```

or

```js
class MyCustomBaseResource extends JSData.Resource {...}
class User extends MyCustomBaseResource {...}
class Post extends MyCustomBaseResource {...}
class Comment extends MyCustomBaseResource {...}
```

**Comment by techniq** [comment]
true.  using the decorator `@resource` would allow us to pass in configuration to it directly, if needed (might not need it as another decorator would probably be used), but just showing what's available.

For example

```js
@resource({defaultAdapter: 'http'})
class User { ... }
```

Likely those types of settings would be another decorator like
```js
@resource
@defaultAdapter('http')
class User { ... }
```

I'm just bringing it up as to a pro for using decorators to define resources over inheritance.

**Comment by jmdobry** [comment]
I think there's a balance that can be made between inheritance and mixins. Arguably, User _is_ a Resource, so it makes sense for User to inherit Resource behavior. Mixins (decorators) can be used to add functionality, like User _has_ a mongodb adapter, or User _has_ a schema (`@schema({...})`). I think going 100% inheritance leads to limitations, because inheritance. I think going 100% mixins can be a mess. In the context of js-data, there is a subset of behavior and properties in a User that make it what it is–a Resource. This needs to work: `user instanceof Resource === true`. Not everything a User does comes from Resource though, which is where mixins come in. User HasMany Post, User has a schema, User has an adapter, User does this, User does that. That can all be mixed-in from plugins, extensions, and custom code.

Decorators are required for configuration that requires extra code to be executed. The simple properties and methods that define what a Resource _is_, and therefore also what a User _is_, these can be inherited.

A `@configure` decorator could achieve the equivalent of stage-0 class properties, and the `.extend` can serve those writing in ES5.

```js
import {Resource, schema} from 'js-data'

// Must use mixin because this requires code execution
@schema({
  name: {}
})
class User extends Resource {
  static defaultAdapter = 'mongo'
  static autoInject = false
  static idAttribute = '_id'
}
```
or
```js
import {Resource, configure, schema} from 'js-data'

@configure({
  defaultAdapter: 'mongo',
  autoInject: false,
  idAttribute: '_id'
})
@schema({
  name: {}
})
class User extends Resource {}
```

or

```js
// Internally, `extend` creates a child class
// and then applies the appropriate decorators
var User = JSData.Resource.extend({}, {
  name: 'user',
  defaultAdapter: 'mongo',
  autoInject: false,
  idAttribute: '_id',
  schema: {
    name: {}
  }
})
```

**Comment by techniq** [comment]
:+1:

**Comment by techniq** [comment]
For my own understanding, why must `user instanceof Resource === true`?

**Comment by jmdobry** [comment]
Like I said, because a User _is_ a Resource. This is the syntactical way of making that assertion. When instantiating a User, it will end up calling the super constructor.

```js
class User extends Resource {}
let user = new User({ name: 'user' })
user instanceof User // true
user instanceof Resource // true

class Post extends Resource {
  // custom constructor, contrived example
  constructor(user, props) {
    // you don't get this if Resource was just a mixin
    // we'd have to make up an arbitrary mechanism, like Backbone's "initialize"
    super(props)
    this.userId = user.id
  }
}
```

**Comment by techniq** [comment]
what kind of `props` would we pass up to `Resource`

**Comment by jmdobry** [comment]
> what kind of props would we pass up to Resource

Whatever you're putting into the instance.

Currently in js-data you _have_ to use `createInstance`, but in v3 you'll be able to "new" up instances. Currently, a resource is _not_ the constructor function. In v3, the resource will be the service _and_ the constructor function, hence the ease of putting static and instance properties onto a single class, instead of the weird `methods` option and being required to use `createInstance`.

v2
```js
var User = store.defineResource({
  // ...
  methods: {
    say: function () {
      console.log(this.name)
    }
  }
})
var user = User.createInstance({ name: 'John' })
user.say() // "John"
```

v3

```js
class User extends Resource {
  say() {
    return this.name
  }
}
let user = new User({ name: 'John' })
user.say() // "John"
```

**Comment by techniq** [comment]
I follow.  I guess also all the `DS` prefixed methods like `DSSave` etc would would be on the user instance that way as well (`user.DSSave()`).

I was trying to see if there was any way we could give js-data a plain POJO class and through conventions / store config have it work.  Such that:
```js
class User { ... }
store.inject(new User(1))
store.create(new User()).then((u) => expect(u.id).to.be.defined);
```
would work as long as the instance adhered to the convention/configuration of the store (had an `id` property set if injecting or will receive one after an adapter's create, etc).  The instance could at this point also be enhanced to have the `DSSave` and other methods.

Which on that topic, do you think we could call them `user.$save()`/etc?

**Comment by jmdobry** [comment]
Regarding the plain class, I don't know. That reminds me of golang-style interfaces, and I'm not sure I like that approach. This might not even be possible because functionality is moving from DS to the Resource class. In v3 DS will just be a convenient container for Resources.

> Which on that topic, do you think we could call them user.$save()/etc?

I was thinking about just changing it to `save` (along with removing the `DS` prefix on the other instance methods).

With ES6 classes, users can easily override methods:

pseudo-code from proposed `Resource` implementation:
```js
class Resource {
  // Instance method
  save(opts) {
    return this.constructor.save(this[this.constructor.idAttribute], opts)
  }
  // Class method
  static save(id, opts) {
    // call adapter#update
  }
}
```
Then
```js
class User extends Resource {
  static save(id, opts) {
    // do custom thing
    return super.save(id, opts).then(item => {
      // do some other custom thing
    })
  }
}

let user = User.inject({ id: 1 })
user.name = 'John'
User.save(1)
// or
user.save()
```

**Comment by techniq** [comment]
That looks good. Will overriding the methods then replace some/all of the
events since you can hook into the life cycle before/after easily?

**Comment by jmdobry** [comment]
Perhaps, I'll think about it. I really don't like having this rigid, messy chain: https://github.com/js-data/js-data/blob/master/src/datastore/async_methods/create.js#L49

**Comment by jbadeau** [comment]
I also would love to see an ODATA adapter

**Comment by stalniy** [comment]
My 2 cents:
having a decorator with big configuration object is bad as eventually you will end up having a lot of configuration stuff and empty model class which extends `Record`. This is what Angular2 it's. In my opinion,  convention + few smaller decorators which updates metadata is much better .

So, I'd like to see something like:
```js
import { Record, Entity, hasMany, belongsTo, string, date, boolean } from 'js-data'

@Entity()
export class Post extends Record {
  @hasMany() comments = [];

  @belongsTo() user;

  @string() title;
  @string() content;
  @date() createdAt;
  @boolean() isActive = true;
}

/**
 * @Entity - creates mapper with default configuration. Additional config may be passed as first argument for decorator
 * @hasMany, @belongsTo - defines relation with default `local/foreign fields` (e.g., for `comments`, relation name is "comment", `localField` is `comments` and `foreignKey` is `post_id`). May be changed if configuration is passed
 * @string, @date, @boolean, etc - types for fields
 */
```

**Comment by jmdobry** [comment]
@stalniy The ideas in this thread are way out-of-date, you should instead look at the current [v3 beta docs](http://www.js-data.io/v3.0/docs/home) and [API reference](http://api.js-data.io/js-data/latest/)

**Comment by jmdobry** [comment]
I'm closing this thread, moving towards a release candidate. See the CHANGELOG for everything that's been implemented in v3.
