### ISSUE TITLE
Support for temporary entites

### ISSUE THREAD

**Issue by jmdobry** [js-data/js-data#197]
Something like:

```javascript
Foo.inject({ id: 1, foo: 'baz' });
Foo.filter().length; // 1

var foo = Foo.inject({ foo: 'bar' }, { temporary: true });
foo.id; // "3849e94d-0d58-4088-ba61-b690d420bff6"
Foo.filter().length; // 2
Foo.filter(null, { includeTemporary: false }).length; // 1
foo.DSIsNew(); // true

// or foo.DSSave()
foo.DSCreate().then(function (foo) {
  foo.id; // 2
  foo.DSIsNew(); // false
});
```

**Comment by internalfx** [comment]
Do you already have a UUID implementation?

**Comment by jmdobry** [comment]
I will just include the one in moutjs

**Comment by davincho** [comment]
+1

**Comment by awhitty** [comment]
+1

**Comment by internalfx** [comment]
Thinking of tackling this next.

The problem is, how do you match up the saved record with the temporary, now that the ID has changed?

**Comment by jmdobry** [comment]
The create method can do it, as it will have a reference to both the temp object and the one returned by the server.

**Comment by internalfx** [comment]
Oh I see, it gets the direct response from the server.

So it knows "I sent this data to the server, and it responded with this."

So whatever Id it comes back with must be the right one.

**Comment by davincho** [comment]
An interesting case would be, if the server returns an error, then one would have to re-inject the object with its uuid.

**Comment by jmdobry** [comment]
I was thinking you wouldn't eject the temp one until the server responds succesfully.

**Comment by jmdobry** [comment]
Implemented in 3.0.0-alpha.x.

**Comment by davincho** [comment]
@jmdobry Are you planning to backport this feature to 2.x?

**Comment by jmdobry** [comment]
No, as it relies on some other new architectural changes in v3. There is however, #284 which adds temporary items to v2, albeit with a different implementation. Follow #284 for v2 support of temporary entities.
