### ISSUE TITLE
Changes via ng-model to nested object does not trigger DS.change event

### ISSUE THREAD

**Issue by davincho** [js-data/js-data#198]
Take the following object
```javascript
var blog = Blog.inject({
    id: 1,
    normal: 'test',
    nested: {
        text: 'test'
    }
});

blog.on('DS.change', function() {
  console.log('Change');
});

blog.normal = 'changing';  // Triggers callback
blog.nested.text = 'changing';  // Triggers callback
```

When changing properties of the ``blog`` object programmatically, everything works as expected. But when I bind the object via ng-model to an input field, only shallow object properties will trigger the callback

```html
<form action="">
  <!-- Does trigger callback when text is changed -->
  <input type="text" ng-model="vm.blog.normal">

  <!-- Does not trigger callback when text is changed -->
  <input type="text" ng-model="vm.blog.nested.text">
</form>
```

Example: http://plnkr.co/edit/ngllVEQNk6xWzHAJV2fC?p=preview

**Comment by internalfx** [comment]
Its because of how `object.observe` works.

the `blog` is an object
and `blog.nested` is another object

`blog` is the observed object

so when you run `blog.normal = 'changing';` you modified `blog`
but when you run `blog.nested.text = 'changing';` you modified `blog.nested` which is a different object.

this will work, however `blog.nested = {text: 'changing'};`

**Comment by davincho** [comment]
Thanks for your comment. Okay that makes sense - but when assigning a value to ``blog.nested.text`` the callback gets triggered, whereas changing it via ng-model it does not.
As in both cases the nested object is modified, the callback should not be triggered at all, or did I miss something?

**Comment by jmdobry** [comment]
What callback? The one where you're logging "Change"?

**Comment by jmdobry** [comment]
It may actually be that `Object.observe` _does_ pick up the change because I tweaked their comparison algorithm, but, Angular doesn't pick up the change because `Object.observe` is not directly tied into Angular's $digest loop. js-data-angular does its best to let Angular know about changes, but it can't do everything. So, you could do this (and it's something we do in our apps at work):

```javascript
vm.blog = Blog.inject({
  id: 1,
  normal: 'test',
  nested: {
    text: 'test'
  }
});

function onChange() {
  console.log('Change');
  if (!$scope.$$phase) {
    $scope.$apply();
  }
}

vm.blog.on('DS.change', onChange);

$scope.$on('$destroy', function () {
  vm.blog.off('DS.change', onChange);
});
```

**Comment by davincho** [comment]
Probably I should clarify the problem: It is not that Angular does not pick up the change, but js-data does not recognize a change from Angular on a nested object.

Taking the code from jmdobry:

```javascript
vm.blog = Blog.inject({
  id: 1,
  normal: 'test',
  nested: {
    text: 'test'
  }
});

function onChange() {
  console.log('Change');
}

vm.blog.on('DS.change', onChange);

```

```html
<input type="text" ng-model="vm.blog.normal">
<input type="text" ng-model="vm.blog.nested.text">
```

Both statements beneath update **the textbox value** bound to the value via ng-model and **log "change" to the console**.

```javascript
vm.blog.normal = 'newValue'; // logs "Change" to the console and updates textbox
vm.blog.nested.text = 'newValue'; // logs "Change" to the console and updates textbox
```
Till now everything works as expected, but changing the value of a textbox **bound to a nested object**, does not log "change" to the console.

**Comment by davincho** [comment]
Okay my fault, actually ``vm.blog.nested.text = 'newValue';`` does not trigger the onChange method. The plunker example (http://plnkr.co/edit/ngllVEQNk6xWzHAJV2fC?p=preview) I posted above was not correct. Sorry!
