### ISSUE TITLE
HasOne resource via nested endpoint

### ISSUE THREAD

**Issue by sido378** [js-data/js-data#199]
Hi, 
ive got a following setup:
user hasOne Company
Company belongsTo User
my backend allows me to only retrieve the company via this route:
user/USERID/company
i cant seem to get this to work - findAll seems to produce the correct route but will then expect an array instead of a singular resource

basically - i need to retrieve the company without knowing its primary key, and only knowing its parent key...

the endpoint i'd like to see seems to have been discussed in the first two answers of this issue:
https://github.com/js-data/js-data-angular/issues/40
but i think a different  way was implemented...
am i missing something or is there a way around this issue?

**Comment by sido378** [comment]
return Company.findAll({userUuid: uuidUser}).then(function (company) {
        return Company.inject(company);
    });

so this solution from js-dta-angular issue #113 seems to make it work, but i still get the error
    company Error: response is expected to be an array!
which is hardly ideal
so im still wondering: is there any clean way to retrieve a hasOne resource via only the parents key?

**Comment by jmdobry** [comment]
```javascript
var Company = DS.defineResource(...);

var User = DS.defineResource({
  name: 'user',
  idAttribute: 'userUuid',
  relations: {...},
  /** INSTANCE METHODS **/
  methods: {
    findCompany: function () {
      return User.findCompany(this.userUuid);
    }
  },
  /** STATIC METHODS **/
  actions: {
    findCompany: {
      pathname: 'company',
      response: function (response) {
        var company = DSHttpAdapter.defaults.deserialize(Company, response);
        return Company.inject(company);
      }
    }
  }
});

var user = User.inject({ userUuid: 1 });

// via the static method
User.findCompany(1).then(function (company) {

  // via the instance method
  return user.findCompany();
});
```

**Comment by sido378** [comment]
thank you! much appreciated

**Comment by VenkatRamReddyK** [comment]
@jmdobry, 
 
I am trying to access `/api/v1/users/:userId/settings/ui`

The following code able to point `/api/v1/users/:userId/settings/` but not `/api/v1/users/:userId/settings/ui`

```
$provide.factory('UserSettings', function ($resource) {
      
      return DS.defineResource({
        basePath: '/api/v1',
        endpoint: '/users',
        name: 'user1',
        actions : {
          settings: {
            method: 'GET'
          }
        },
        cacheResponse: true,
        maxAge: 1000 * 60 * 10 // cache expires after 10 minutes
      });
    });

```

Can any one let me know how to do that using `actions` ?
Appreciate your help in advance !

**Comment by VenkatRamReddyK** [comment]
## **Adding pathname resolved this issue.** 

https://github.com/js-data/js-data/issues/113 : resolved this issue

```

$provide.factory('UserSettings', function ($resource) {

      return DS.defineResource({
        basePath: '/api/v1',
        endpoint: '/users',
        name: 'userSettings',
        actions : {
          getSettings: {
            method: 'GET', 
            pathname: 'settings/ui'
          },
          saveSettings: {
            method: 'PUT',
            pathname: 'settings/ui'
         }
        },
        cacheResponse: true,
        maxAge: 1000 * 60 * 10 // cache expires after 10 minutes
      });
    });

```

**Use it the following way.**

```

UserSettings.getSettings(userId).then(function (userSettingsResponse) {
              $log.debug('userSettingsResponse: ', userSettingsResponse);
            }).catch(function (userSettingsError) {
               $log.debug('User Settings Error: ', userSettingsError);
              });

```
