### ISSUE TITLE
Multiple hasOne relations not related properly

### ISSUE THREAD

**Issue by jaspoor** [js-data/js-data#200]
When defining two hasOne relations [doc's: Triangle-Points ](http://www.js-data.io/docs/relations) like shown below, none will get populated.

```
DS.defineResource({
    name: 'item',
    endpoint: '/items',
    relations: {
      hasOne: {
        tag: [{
            localKey: 'tag1Key',
            localField: 'tag1'
        } , {
            localKey: 'tag2Key',
            localField: 'tag2'
        }]
      },
    }
});
```

I would expect an object returned with a tag1 and a tag2 field set. When you uncomment the second tag relation, it returns an object with tag2 (!!!) populated instead of tag1?. I got lost somewhere in the jsdata core, but couldn't find how injected relations got populated.
Am i doing something wrong here?

See plunker: http://plnkr.co/edit/vw5OTY55T99w14mQsINA?p=info

Regards, Jasper

**Comment by jmdobry** [comment]
I'll take a look when I get back in town.

**Comment by jaspoor** [comment]
That would be perfect Jason. If you give me some directions, I love to help out. This is where I got stuck:

It first tries to _inject(..) each relation defined in the resource definition. Then this piece of code checks for a foreignKey definition (which my hasOne definition doesn't have) to set the _injected object:
```
[js-data.js:3946]
var _injected = relationDef.inject(attrs[def.localField], options.orig());
if (def.foreignKey) {
   _utils['default'].set(_injected, def.foreignKey, attrs[definition.idAttribute]);
}
```
I can't find how my _injected Tag objects are populated on the Item object, so I am not sure how to continue. Could there be something missing here for relations with localKeys instead of foreignKeys?

Regards, Jasper

**Comment by jmdobry** [comment]
hasOne relations can follow the localKey or foreignKey format. Relations aren't populated directly on object, but rather, objects have property accessors that retrieve relations from the store synchronously. Here's the code for that: https://github.com/js-data/js-data/blob/master/src/utils.js#L575

**Comment by jmdobry** [comment]
@jaspoor So I've looked at your plunker, and the item that gets logged doesn't have a `tag1key` or `tag2key` like the defined relation calls for.

Example:

```javascript
DS.defineResource({
  name: 'item',
  endpoint: '/items',
  relations: {
    hasOne: {
      tag: [{
        localKey: 'tag1Key',
        localField: 'tag1'
      }, {
        localKey: 'tag2Key',
        localField: 'tag2'
      }]
    }
  }
});

var item = DS.inject('item', {
  id: 1,
  tag1Key: 2,
  tag2Key: 3
});

DS.inject('tag', [{ id: 2 }, { id: 3}]);

item.tag1; // { id: 2 }
item.tag2; // { id: 3 }
```

**Comment by jaspoor** [comment]
@jmdobry I might misunderstand how localKey's should be used, but changing the item's data in the datastore (firebaseio) with two attributes (tag1Key and tag2Key) doesn't seem to make any difference. The tag1 and tag2 fields are still left undefined. Am I missing something?

**Comment by jmdobry** [comment]
Here's a fork of your plunker with how it should be used: http://plnkr.co/edit/3B9EI4xQfty50ArwMajd?p=preview

And here's a plunker with a working hasOne relation that you can play around with, so you can see what the data should look like: http://plnkr.co/edit/0hMiB4?p=preview

**Comment by jmdobry** [comment]
Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, JSData, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [Gitter Channel](https://gitter.im/js-data/js-data) or the [mailing list](https://groups.io/org/groupsio/jsdata).
