### ISSUE TITLE
Feature request: hook into loadRelations

### ISSUE THREAD

**Issue by dts** [js-data/js-data#201]
loadRelations is pretty great, and satisfies a lot of different use cases, but since we can write our own relation getters, it would be perfect to be able to hook into loadRelations in order to back those up.  My specific use case is for polymorphic belongsTo, which I can make work with the getter, but doing it to a group of objects, etc. is just too one-off for me to be really happy long term.  I'm happy to write the code and PR it, but I won't bother if this isn't of interest.  The way I would do it is just have an optional `load` function defined in the relation options hash that would be called if present, and otherwise would just use the existing code.

**Comment by jmdobry** [comment]
That's interesting, let me give this some thought

**Comment by dts** [comment]
Another way to do this would be to refactor things so that I can monkey-patch some of these things more easily.  The widespread use of the function-returns-promise methodology makes it difficult to replace smaller pieces of the broader codebase.  It would be helpful to break out the smaller actions within functions like loadRelations into smaller functions that can be monkey-patched and hooked into at a more fine-grained level.

**Comment by jmdobry** [comment]
I just realized the the `afterLoadRelations` hook that I implemented does not satisfy this feature request.

**Comment by jmdobry** [comment]
@dts I added a `load` option to relation definitions, where you can provide your own function for loading the relation. The function will be passed `Resource, relationDef, instance, options` and must return a promise that should resolve with the relation object/array of objects. See https://github.com/js-data/js-data/blob/master/test/browser/datastore/async_methods/loadRelations.test.js#L467

**Comment by jmdobry** [comment]
p.s. This will be available in 2.5.0

**Comment by dts** [comment]
That's great news!  I'll check it out in my next projects.
