### ISSUE TITLE
Choose official code style for project

### ISSUE THREAD

**Issue by internalfx** [js-data/js-data#204]
It would improve quality of submissions if there was an official code style chosen.

Some suggestions...

[![js-standard-style](https://cdn.rawgit.com/feross/standard/master/badge.svg)](https://github.com/feross/standard)

[![js-semistandard-style](https://cdn.rawgit.com/flet/semistandard/master/badge.svg)](https://github.com/Flet/semistandard)

[![js-happiness-style](https://cdn.rawgit.com/JedWatson/happiness/master/badge.svg)](https://github.com/JedWatson/happiness)

**Comment by internalfx** [comment]
I've gotten really used to standard, but I see you have semicolons everywhere.

Maybe SemiStandard would be a good fit

**Comment by jmdobry** [comment]
Standard looks fine to me, I'm not married to semicolons

**Comment by internalfx** [comment]
Yay! I love standard. I was determined not to be pushy with my opinions as it would be better to just accept whatever you choose, even if its not my favorite.

**Comment by internalfx** [comment]
Wow...big commit.

:clap:
