### ISSUE TITLE
DS#revert should ignore omitted fields

### ISSUE THREAD

**Issue by awhitty** [js-data/js-data#205]
Just as the title says. The docs say:
> Synchronously revert the state of an item to the last time it was saved via an async adapter. Returns the reverted item.

I know it can be interpreted several ways, but I take this to mean revert the item back to the last "true" state, as defined by the external backend. Since the backend is blind to the omitted fields, I'd expect the omitted fields to be... omitted from the state.

In my specific use case, I'm using an omitted field to keep track of whether the user has selected an item. If the user makes a change to the item while it is selected, saves the change to the server, and deselects the item, the next time the user reverts a change, the item will be selected again.

**Comment by jmdobry** [comment]
This is a good point.

**Comment by awhitty** [comment]
I'm not too familiar with the js-data codebase, but I can try to draft up a pull-request in the next few days if you're interested in incorporating this?

I imagine something like
```js
var item = Item.get(5);
item.DSRevert({
  skipOmittedFields: true
});
```
would be enough.

I asked about skipping over fields in the gitter channel for an unrelated use case where I have two forms responsible for editing different parts of an item in the store, and I'd like to be able to cancel changes from one form without reverting the changes in the other form. I understand that this use case is a bit more unique than the one that I've described above, but I imagine this would be a good opportunity to add functionality that would cover both cases.

In my mind something like 
```js
var item = Item.get(5);
item.DSRevert({
  skip: ['title', 'author']
});
```
would get us there, and the `skipOmittedFields` from above would just append the omitted fields array to this `skip` array.

**Comment by jmdobry** [comment]
Both of those suggestions sound good

**Comment by internalfx** [comment]
@awhitty I think this may be a rather surprising behavior.

I think `revert the state of an item` is quite clearly the state the item was in before it was changed. It mentions nothing about the adapter.

Also what if you are not using a adapter?

The store doesn't care what state the adapter has because it's autonomous.

**Comment by internalfx** [comment]
@awhitty @jmdobry please see PR

**Comment by internalfx** [comment]
Oh, I also used the term "preserve" I thought it best described what it did.

Comments?

**Comment by internalfx** [comment]
```javascript
item.DSRevert({
  preserve: ['title', 'author']
});
```
