### ISSUE TITLE
Add case insensitive filtering in query syntax

### ISSUE THREAD

**Issue by mapsi** [js-data/js-data#211]
I am currently struggling to find a way of doing a case insensitive search.
I was wondering if this has already planned?

Otherwise #185 would be helpful as it would allow for a case insensitive filter to be applied manually.

**Comment by jmdobry** [comment]
Yeah, when #185 is implemented it may solve this for you.

**Comment by oliverhr** [comment]
Any clues on when it will be ready?

**Comment by jmdobry** [comment]
Not sure. This is a bit of tricky one, as whatever changes are made to the Query Syntax need to be understandable by all the adapters.

**Comment by jmdobry** [comment]
Implemented, with the limitation that `%` and `_` cannot be escaped, so you can't match `%` and `_` literals. If someone wants to figure that out, I'd be happy to see what you come up with.

You can now do:

```
User.filter({
  where: {
    name: {
      // match will, willy, william, etc.
      'like': 'will%'
    }
  }
})
```

You can control case sensitivity by appending any of the valid javascript regexp flags to the end of the operator itself, e.g.

```
User.filter({
  where: {
    name: {
      // match will, Will, WILL, willy, william, etc.
      'likei': 'will%'
    }
  }
})
```

You can also do `notLike`

**Comment by oliverhr** [comment]
Great!, thank you.

**Comment by jmdobry** [comment]
Note, adapters (except http adapter) still must implement the `like` and `notLike` operator
