### ISSUE TITLE
Incorrect url when fetching nested resource

### ISSUE THREAD

**Issue by techniq** [js-data/js-data#219]
I have the following resources defined as angular factories:
```js
// Feedback
DS.defineResource('feedbacks');

// Comment
DS.defineResource({
  name: 'comments',
  relations: {
    belongsTo: {
      feedback: {
        parent: true,
        localKey: 'feedbackId',
        localField: 'feedback'
      }
    }
  }
});
```

When I call `Comment.findAll({feedbackId: 1234})`, I'm expecting this url to be fetched:
```
/feedbacks/1234/comments
```
but instead the following is executing:
```
/comments?feedbackId=1234
```

Reading about [nested resource endpoints](http://www.js-data.io/docs/relations#section-nested-resource-endpoints) it seemed like setting `parent: true` and referencing the `localKey` as the name of the parent was the solution, but I'm guessing I'm overlooking something.

**Comment by jmdobry** [comment]
Try this: `Comment.findAll(null, { params: { feedbackId: 1234 } })`

**Comment by techniq** [comment]
@jmdobry Same result (querystring instead of path)

**Comment by techniq** [comment]
Fixed out the issue.  I didn't realize the key of the belongsTo property needed to match the name of the other defined resource.  So I needed to change
```js
belongsTo: { feedback: { ... } }
```
to
```js
belongsTo: { feedbacks: { ... } }
```
