### ISSUE TITLE
Optionally disable injection of nested relations

### ISSUE THREAD

**Issue by Patrik-Lundqvist** [js-data/js-data#220]
It would be useful to have the ability to disable automatic injection on specific nested relations as it gives a lot of freedom how relations are handled, especially when using custom relation loading with #201.

Something like:
```
relations: {
  belongsTo: {
    user: {
        localField: 'owner'
        localKey: 'userId',
        inject: false
    }
  }
}
```

**Comment by jmdobry** [comment]
I add the `inject` option to relation definitions, which if set to `false` should probably also be paired with `link: false`. You can also set the `inject` option to a function that will be passed `Resource, relationDef, instance`, which you can use to manually inject the relation into the store. See https://github.com/js-data/js-data/blob/master/test/both/datastore/sync_methods/inject.test.js#L342 and https://github.com/js-data/js-data/blob/master/test/both/datastore/sync_methods/inject.test.js#L381 and https://github.com/js-data/js-data/blob/master/test/both/datastore/sync_methods/inject.test.js#L437

**Comment by Patrik-Lundqvist** [comment]
Nice, works great :+1:
