### ISSUE TITLE
Zero value Id in relations

### ISSUE THREAD

**Issue by Pencroff** [js-data/js-data#223]
Data for model:
```
{
    Id: 123,
    Value: 'Some value',
    ClientId: 0,
    Client: {
        ClientId: 0,
        ClientName: 'Default Client'
    }
}
```
Models: 
```
store.defineResource({
    name: 'clientModel'
})

var model = store.defineResource({
    name: 'itemModel',
    endpoint: '/item',
    idAttribute: 'Id',
    relations: {
        hasOne: {
            'clientModel': {
                localField: 'Client',
                localKey: 'ClientId'
            }
        }
    }
})
```
If model in relation has id = 0, then it doesn't available in `localField` (`Client` return `undifined`) after resolving `loadRelations`.

**Comment by Tronix117** [comment]
On version 2.6.1, this issue doesn't seem to be fixed:

        belongsTo:
          something:
            localField: 'something'
            localKey: 'something_id'

If `something_id` is 0, then the relation `model.something` will always return `undefined`.

**Comment by jmdobry** [comment]
Can you make a plunker that demonstrates?

**Comment by Tronix117** [comment]
Check this plunker,
change the value to 1 in script.js and it will work fine.

http://embed.plnkr.co/iI9iWmPneUsaEw2LxlgG/

**Comment by Pencroff** [comment]
It seems I have covered `hasOne`, but didn't covered `belongsTo`. If you want I could take care about that.

**Comment by jmdobry** [comment]
Yeah
