### ISSUE TITLE
Add 'store.unregisterAdapter(...)' to remove an adapter

### ISSUE THREAD

**Issue by techniq** [js-data/js-data#225]
I've recently moved from using `bookself.js` to `js-data-sql` for my data access needs.  Before, I was using [mock-knex](https://github.com/colonyamerican/mock-knex) within some of my tests, but had ran into an [issue](https://github.com/colonyamerican/mock-knex/pull/13) with it not "unmocking" correctly.  I then came to the realization with `js-data` that I could use a custom adapter during testing to stub out the data access (and not actually try to execute sql).  In doing so, I'm using the following setup/teardown within my tests:

```js
describe('Example', function() {
  before(function() {
    let dataset = {
      post: [
        { ... },
      ]
    };
    store.registerAdapter('test', new TestAdapter(dataset), { default: true });
  });

  after(function() {
    delete store.adapters['test'];
    store.defaults.defaultAdapter = 'sql';
  });

  ...
}
```

It seems like it would be nice if there was a `store.unregisterAdapter('test')` that would remove the adapter from `store.adapters` instead of calling `delete store.adapters['test']` myself.  Also, I wasn't sure how best to handle `store.defaults.defaultAdapter`.  By default it's set to `'http'`, but once it's overridden (like in my case with `'sql`'), we can't simple set it back to `'http'`.  I considered if there is only one adapter, you could set it as `store.defaults.defaultAdapter = store.adapters[0].name`, but who's to say that adapter was ever the default.  For example:

```js
const JSData = require('js-data');
const DSSqlAdapter = require('js-data-sql');

let store = new JSData.DS();
let sqlAdapter = new DSSqlAdapter(config);
store.registerAdapter('sql', sqlAdapter/*, { default: true }*/);
```

If you don't set `{ default: true }`, `'http'` will still be the default adapter.

Maybe instead when calling `store.registerAdapter(...)`, if it is the first adapter being added (`store.adapters.length === 0`), it should be the implied default, and if you additional adapters later (and you want one of them to be the default), they should have the explicit `{ default: true }`, which brings me back to `store.unregisterAdapter(...)`, if we change how we handle the `registerAdapter` (first is default), we could then imply the same when removing (if only 1 registered, it's the default).  If you have say 3 and remove 1, you'll still be required to set it to the desired one (maybe expose `store.setDefaultAdapter(name)` instead of requiring `store.defaults.defaultAdapter = name`

---

On a semi-related note, I'm currently in the process of building out a `TestAdapter` that works against a simple object that might be helpful to add to the official `js-data` adapters.  I've only stubbed out the `findAll` method for my current needs, but could finish the others if it lives outside my project.

```js
'use strict';
const matches = require('lodash.matches');

class TestAdapter {
  constructor(dataset) {
    this.dataset = dataset;
  }

  create(definition, attrs, options) {
    // Must resolve the promise with the created item
    return new Promise((resolve, reject) => {
      reject(new Error('TestAdapter#create Not implemenented'));
    })
  }

  find(definition, id, options) {
    // Must resolve the promise with the found item
    return new Promise((resolve, reject) => {
      reject(new Error('TestAdapter#find Not implemenented'));
    })
  }

  findAll(definition, params, options) {
    return new Promise((resolve, reject) => {
      let limit = null;
      if (params.limit) {
        limit = params.limit;
        delete params.limit;
      }

      let items = this.dataset[definition.name].filter(matches(params));

      if (limit) {
        items = items.slice(0, limit);
      }

      resolve(items);
    })
  }

  update(definition, id, attrs, options) {
    // Must resolve the promise with the updated item
    return new Promise((resolve, reject) => {
      reject(new Error('TestAdapter#update Not implemenented'));
    })
  }

  updateAll(definition, attrs, params, options) {
    // Must resolve the promise with the updated items
    return new Promise((resolve, reject) => {
      reject(new Error('TestAdapter#updateAll Not implemenented'));
    })
  }

  destroy(definition, id, options) {
    // Must return a promise
    return new Promise((resolve, reject) => {
      reject(new Error('TestAdapter#destroy Not implemenented'));
    })
  }

  destroyAll(definition, params, options) {
    // Must return a promise
    return new Promise((resolve, reject) => {
      reject(new Error('TestAdapter#destroyAll Not implemenented'));
    })
  }
}

module.exports = TestAdapter;

```

**Comment by jmdobry** [comment]
Very good, I'll review this tonight.

**Comment by techniq** [comment]
:+1:

**Comment by jmdobry** [comment]
> By default it's set to 'http', but once it's overridden (like in my case with 'sql'), we can't simply set it back to 'http'

Here's some of the magic of js-data:

```javascript
let store = new JSData.DS();
console.log(store.defaults.defaultAdapter); // "http"

store.defaults.defaultAdapter = 'sql';
console.log(store.defaults.defaultAdapter); // "sql"

delete store.defaults.defaultAdapter;
console.log(store.defaults.defaultAdapter); // "http"   O.o
```

so there's that

----

Regarding the test adapter, what do you think about me ripping out the non-Angular part of https://github.com/js-data/js-data-angular-mocks and releasing that as `js-data-test`?

**Comment by jmdobry** [comment]
Also, here's an updated `findAll` implementation for your custom test adapter (gives your `findAll` full support for js-data's query syntax):

```javascript
findAll(definition, params, options) {
  return new Promise((resolve, reject) => {
    // Assumes "definition" was created by DS#defineResource
    resolve(definition.defaultFilter(this.dataset[definition.name], definition.name, params, options));
  })
}
```

**Comment by techniq** [comment]
@jmdobry Thanks for the tip on using `definition.defaultFilter`.  Regarding making `js-data-test` from the non-angular pars of `js-data-angular-mocks`, that sounds good.  I've only briefly looked at it and some of the example usage.  Is there any guides or other docs I'm overlooking?

Currently the `TestAdapter` I'm using is working well for me

**Comment by jmdobry** [comment]
> Is there any guides or other docs I'm overlooking?

No.

For now I'm not going to take any action on this.

**Comment by techniq** [comment]
@jmdobry I've recently switched my tests to use this adapter `MemoryAdapter` which is basically a facade from the asynchronous adapter methods to the synchronous store methods.  It currently has a reliant on an `.id` property (which I could use the definitions `idAttribute` to look it up) as well the `id` needing to be an incrementing integer for new creates.

```js
'use strict';
const JSData = require('js-data');

class MemoryAdapter {
  constructor(store) {
    this.store = store;
  }

  create(definition, attrs, options) {
    return new Promise((resolve, reject) => {
      if (!attrs.id) {
        this.findAll(definition).then(objs => {
          const maxId = Math.max.apply(null, objs.map(o => o.id))
          attrs.id = maxId === -Infinity ? 1 : maxId;
          resolve(this.store.inject(definition.name, attrs, options));
        })
      } else {
        resolve(this.store.inject(definition.name, attrs, options));
      }
    });
  }

  find(definition, id, options) {
    return new Promise((resolve, reject) => {
      resolve(this.store.get(definition.name, id, options));
    });
  }

  findAll(definition, params, options) {
    return new Promise((resolve, reject) => {
      resolve(this.store.filter(definition.name, params, options));
    });
  }

  update(definition, id, attrs, options) {
    return new Promise((resolve, reject) => {
      resolve(this.store.inject(definition.name, attrs, options));
    });
  }

  updateAll(definition, attrs, params, options) {
    return new Promise((resolve, reject) => {
      resolve(this.store.inject(definition.name, attrs, options));
    });
  }

  destroy(definition, id, options) {
    return new Promise((resolve, reject) => {
      resolve(this.store.eject(definition.name, id, options));
    });
  }

  destroyAll(definition, params, options) {
    return new Promise((resolve, reject) => {
      resolve(store.ejectAll(definition.name, params, options));
    });
  }
}

module.exports = MemoryAdapter;
```

I originally thought about trying to use the memory `store` only (removing all the adapters) but it doesn't look like this is possible.  It's a little odd to use in practice since I pass the store into the adapter so all the resources are defined, but then pass the instance back to the store

```js
  before(function*() {
    db.store.registerAdapter('test', new MemoryAdapter(db.store), { default: true });

    // Add test fixture data
    yield models.User.create({ id: 1, name: 'Sean' });
    yield models.User.create({ id: 2, name: 'Jason' });
    ...
  });
```

@jmdobry Any thoughts on this adapter, or allowing js-data to run adapter-free for tests?

**Comment by jmdobry** [comment]
I guess I can see a use-case for a simple in-memory adapter. I'll look at it tonight.

**Comment by techniq** [comment]
:+1:

**Comment by jmdobry** [comment]
What if someone sets their store to `cacheResponse: false`, in that case the in-memory adapter can't rely on the store for data storage.

**Comment by techniq** [comment]
hmm, good point.  Maybe they could override that when they setup their tests.  I for instance set back my `sql` adapter after my tests are ran (and of course register the test adapter in `before`

```
  after(function() {
    delete db.store.adapters['test'];
    db.store.defaults.defaultAdapter = 'sql';
  });
```

It would be nice if `defineResource(...)` wasn't applied directly to the store instance as I could create a new test-only store instance but need a way to have the same resources defined.

**Comment by jmdobry** [comment]
Is auto-incrementing IDs a requirement? Or can it be guids? Make that configurable?

**Comment by techniq** [comment]
I think it could be configurable (i just created `MemoryAdapter` to fulfill my needs`).  I needed a way to do `User.create({name: 'Sean})` for instance/

**Comment by jmdobry** [comment]
@techniq I just added support to js-data-localstorage for a custom storage medium, so you can just do this:

```js
const memory = {}
let memoryAdapter = new DSLocalStorageAdapter({
  storage: {
    getItem(key) {
      return memory[key]
    },
    setItem(key, value) {
      return memory[key] = value
    },
    removeItem(key) {
      delete memory[key]
    }
  }
})
```

**Comment by techniq** [comment]
@jmdobry nice.  thanks
