### ISSUE TITLE
hasMany relation setter defect

### ISSUE THREAD

**Issue by bikesandcode** [js-data/js-data#226]
I encountered this bug while attempting to do some manipulation of an array of relations on a parent class. In short, this was done to allow an immediate UI update when a service call could potentially take a few seconds.

Essentially, I had a Parent which hasMany Child. I was explicitly setting the parent.children array like so:

    var subsetOfChildren = calculateSubset() //returns an array
    parent.children = subsetOfChildren

I observed that immediately after setting this array of relations to a new (truncated in this case), the relation array was incorrect and the inverse of what I had set it to. That is:

    // parent.children = [{id: 1}, {id: 2}, {id: 3}]
    var subsetOfChildren = [{id: 2}, {id: 3}]
    parent.children = subsetOfChildren
    //Now? parent.children = [{id: 1}]

I've written a test to expose the bug. 

    describe('Array set inconsistency', function () {
      var Parent, Child;
      beforeEach(function () {
        Parent = store.defineResource({
          name: 'parent',
          relations: {
            hasMany: {
              child: {
                localField: 'children',
                foreignKey: 'parentId'
              }
            }
          }
        });

        Child = store.defineResource({
          name: 'child',
          relations: {
            belongsTo: {
              parent: {
                link: false,
                localField: 'parent',
                localKey: 'parentId'
              }
            }
          }
        });
      });

      it("defect reproduction", function () {
        var p1 = Parent.inject({id: 1})
        var c1 = Child.inject({id: 1000, parentId: 1})
        var c2 = Child.inject({id: 1001, parentId: 1})
        var c3 = Child.inject({id: 1002, parentId: 1})
        var c4 = Child.inject({id: 1003, parentId: 1})

        var pStored = Parent.get(1)
        assert.isDefined(pStored)
        assert.equal(pStored.id, 1)
        assert.equal(pStored.children.length, 4)

        pStored.children = [c2, c3, c4];

        //This fails as the length of children is now 1,
        assert.equal(pStored.children.length, 3)

        //What is actually happening: children is the inverse
        //of what we set. c1 was notably absent from the children set
        //These *should* fail. If the above assert is commented out, both will pass.
        assert.equal(pStored.children.length, 1)
        assert.equal(pStored.children[0].id, c1.id)
      });
    });

There may be a better approach, but I am fairly certain this was not the intended behaviour. The specific issue I noted boiled down to an oversight in the hasMany relation setter:

    prop.set = function (children) {
      if (children && children.length) {
        if (foreignKey) {
          forEach(children, function (child) {
            set(child, foreignKey, get(this, definition.idAttribute)) //'this' is wrong
          })
        } else if (localKeys) {
          let keys = []
          forEach(children, function (child) {
            keys.push(get(child, definition.getResource(relationName).idAttribute))
          })
          set(this, localKeys, keys)
        }
      }
      return get(this, localField)
    }

When I was debugging this initially, the 'this' reference in the annotated line above wasn't an instance of the Parent class, but a reference to Window. This doesn't fully address the the issue I was having, but I think this was not the intended behaviour.

**Comment by jmdobry** [comment]
Being worked on in #227

**Comment by jmdobry** [comment]
Was fixed in 2.5.0
