### ISSUE TITLE
findAll should be able to return metadata

### ISSUE THREAD

**Issue by mightyguava** [js-data/js-data#228]
From gitter:

*c-mac*: Hey @jmdobry! Thanks for the awesome library. I’m having an issue implementing server-side pagination. I’m using a custom adapter that wraps wraps our own http service to make API requests. `myResource.findAll()` returns a data structure like: `{data: [{}, … {}], totalCount: 1337}`. I want to inject JUST the array of objects into the store, whilst still saving the totalCount to a variable. If I don’t set `cacheResponse: false` in the resource definition, it breaks because js-data is trying to inject the object that contains both the count and the array into the store, which obviously fails since there is no `id` field. Any thoughts here? I thought that the solution would involve a `beforeInject` hook that just injects the myResources, but I’m not sure how to do that whilst still returning the `totalCount`.

*mightyguava*: @jmdobry regarding @c-mac's question, is there no way to return the totalCount through the data or as metadata? Assigning it the way you suggest effectively makes it a global instead of being tied to the call.

*jmdobry*: @mightyguava
- you can attach metadata to the data about to be injected
- You can store the `totalCount` in a structure managed by whatever is calling `findAll`, keyed by the hash of the params object passed into findAll `(DSUtils.toJson(params))`
- You can contribute and improve the `returnMeta` feature so that you can call `findAll` and then do `.spread (array)` on the promise and get the data and metadata returned, have the data and metadata get returned as properties on an object.

**Comment by mightyguava** [comment]
I plan to work on the 3rd bullet when I get a chance.

**Comment by minibikini** [comment]
:+1: desperately need this in my project (which supposed to be database agnostic)

**Comment by Tronix117** [comment]
:+1: Also desesperaly needed

**Comment by jmdobry** [comment]
Implemented in 3.0.0-alpha.1, now the adapters just need to implement support for the `raw` option.
