### ISSUE TITLE
findAll should query adapter if previous query is expired.

### ISSUE THREAD

**Issue by antoinebrault** [js-data/js-data#234]
Currently, if i use reap = "none", findAll() always returns cached data even if it is expired.

Similar to https://github.com/js-data/js-data/issues/154, I think there should be a way to refresh data with findAll when previous query is expired instead of refreshing on reapInterval with reap="refresh".

Maybe something along the lines of:

```js
// force a new request
if (options.bypassCache || !options.cacheResponse) {
  delete resource.completedQueries[queryHash];
  delete resource.queryData[queryHash];
}
if (queryHash in resource.completedQueries && resource.completedQueries[queryHash] + options.maxAge >= new Date().getTime()) {
 // ...
}
}).then(function (items) {
    if (!items) {
        if (!(queryHash in resource.pendingQueries)) {
```

**Comment by jmdobry** [comment]
Sounds good. PR?
