### ISSUE TITLE
actions defined in defineResource are shared across definitions

### ISSUE THREAD

**Issue by MikaAK** [js-data/js-data#236]
I was using `actions` to define some new actions for a specific resource and I expected them to be individual to a resource since they are defined at the time of creating a specific resource. However this was not the case. They are globally available on all models and this causes some bugs particularly when extended actions don't automatically inject into the data store. 

Previously I had talked with @jmdobry about how to get actions to actually inject into the store and i was informed of the extra `request` and `response` functions you can use when defining an action.
#### EG
```javascript
actions: {
  findOne: {
    request(params) {
      return MyStore.inject(params.data)
    }
  }
}
```

This however is not possible if the actions are shared globally and currently I'm running into the issue of if I've defined `findOne` in one model (and i have it injecting into the store) when i define a second model with `findOne` it can no longer inject because the inject is now going to the wrong place due to the config being overwritten. 

Why are the actions shared across resources when you define them at the time of the resource? Wouldn't it make more sense to add them to defaults in that case and have `response` and `request` get passed which modelResource it is? Or just have the actions actually tie to the definition and not be shared.

**Comment by jmdobry** [comment]
Fixed in 2.6.0. Here's a plunker that demonstrates the fix and also the ability to tell which resource the action is executing for: http://plnkr.co/edit/YjBGmN?p=preview

**Comment by MikaAK** [comment]
@jmdobry just to confirm they are still shared but now we get resourceConfig as part of the config?

**Comment by jmdobry** [comment]
Not "shared" per se, but if you define default actions then each resource now gets its own copy of the action, instead of overwriting the default action every time you define a resource. The plunker shows exactly what is possible.

**Comment by MikaAK** [comment]
Thank you for the info! One thing I've noticed with defining defaults in angular is it's impossible to use DSHttpAdapter query transform and serialze inside of default actions due to having to configure default actions inside of a `config` block. It makes it hard to keep them insync! Not sure a fix for this, it's more just and observation

**Comment by jmdobry** [comment]
Why don't you just inject `DSHttpAdapterProvider` into the config block?

**Comment by MikaAK** [comment]
I did think of that but due to needing `DS` inside of the query transformations I had to set `DSHttpAdapter`'s defaults in a run block :(
