### ISSUE TITLE
LocalForage Adapter doesn't retrieve related entities after page reload

### ISSUE THREAD

**Issue by mobidev111** [js-data/js-data#238]
See this plunker:
http://plnkr.co/edit/jUZ5KPH8yz38n7BPn3Cx?p=preview

To reproduce:
(opened in Chrome)
1) play -> create 1 User with 1 related Post
2) reload page -> previously created User doesn't have any posts any more

Probably the same for LocalStorage Adapter

**Comment by jmdobry** [comment]
I found two issues with your plunker

1. `User.findAll()` only retrieves users. If you wants posts as well, you should do `User.findAll(null, { with: ['post'] })` instead.
1. `console.log(users.posts)` will always be `undefined`. You need `console.log(user.posts)` instead.

**Comment by mobidev111** [comment]
Good. Thanks for the elaborate feedback. 

I corrected the plunker for future reference.

This confused me: The in-memory store works perfectly without the "with" parameters - whereas the adapter needs this parameter to work with relations. maybe this can be better explained in the docs.
