### ISSUE TITLE
DS#commit

### ISSUE THREAD

**Issue by jmdobry** [js-data/js-data#243]
Initial implementation:

```javascript
commit (resourceName, id) {
  let {_this, definition, _resourceName, _id} = check.call(this, 'commit', resourceName, id)
  let resource = _this.store[_resourceName]
  let item = _this.store[_resourceName].index[_id]
  if (item) {
    resource.previousAttributes[_id] = DSUtils.copy(item, null, null, null, definition.relationFields)
  }

  if (resource.changeHistories[_id].length) {
    DSUtils.forEach(resource.changeHistories[_id], function (changeRecord) {
      DSUtils.remove(resource.changeHistory, changeRecord)
    })
    resource.changeHistories[_id].splice(0, resource.changeHistories[_id].length)
  }
  return item
}
```

**Comment by robertdp** [comment]
I think the intention behind this is to provide an alternative to `inject()` and its all-or-nothing approach to change histories.

@internalfx wants a way to clear the change history for a particular item in the store, but this is a knock-on effect of the way he's using it.

An alternative approach might be for `commit()` to inject an item without wiping its change history, and then removing any change history entries that are redundant.

**Comment by internalfx** [comment]
> wants a way to clear the change history for a particular item in the store.

That is the very thing I want to do. Not sure what you mean by knock-on.

If commit just injects, but keeps the change history, it will be utterly useless to me. unless another alternate method is implemented.

**Comment by jmdobry** [comment]
> clear the change history for a particular item in the store

That's exactly what `DS#commit` does

**Comment by internalfx** [comment]
@jmdobry sorry, for the confusion. I was responding to @robertdp.

As I dive into doing full realtime with js-data, and with me using js-data's change tracking, I find that I need more tools to manipulate the change history of an object.
