### ISSUE TITLE
IE9 compatibility

### ISSUE THREAD

**Issue by mattlewis92** [js-data/js-data#247]
When running our tests in IE9 we were getting a lot of "Function expected" errors from this library. I narrowed it down to [this line](https://github.com/js-data/js-data-http/blob/master/src/index.js#L127) of the http adapter and then browserstack started crapping out locally so I couldn't carry on running the tests. A best guess would be `(value instanceof File)` on [this line](https://github.com/js-data/js-data/blob/master/dist/js-data.js#L1195) as the File object isn't available on IE9 but I can't say for certain.

If you run your tests with browserstack on your CI in IE9 you will see a bunch of them failing with this error. [This plugin](https://github.com/karma-runner/karma-browserstack-launcher) makes it super easy to run tests on browserstack and it's free for open source.

**Comment by jmdobry** [comment]
Closing in favor of js-data/js-data-http#30
