### ISSUE TITLE
Define custom error types to be used in adapters

### ISSUE THREAD

**Issue by phparkle** [js-data/js-data#257]
Currently adapters `throw new Error("Not Found!")`. Something like `throw new NotFoundError()` would be better. The custom error classes could be defined in https://github.com/js-data/js-data/blob/master/src/errors.js

Other types of errors could be added too, I think we could take some hints from HTTP status codes.

**Comment by jmdobry** [comment]
I would like to hear more argument on why js-data should have custom error types at all? Is it not sufficient to use the built-in error types?

**Comment by phparkle** [comment]
In Koa for example I've been using an error handler like this:

```js
app.use(function *(next) {
    try {
        yield next;
    } catch(error) {
        if (error.message === "Not Found!") { // (1)
            this.status = 404;
        } else {
            this.status = error.status || 500;
            app.emit("error", error, this);
        }
    }
});
```

I guess it's ok to just check the error message like in `(1)` but it seems kind of arbitrary. It would be nice if a certain set of errors were predefined somewhere all in one place so you have a better idea of what types of errors to expect in order to handle them accordingly.

Another reason (but I don't know if it's valid) is if at some point you wanted to use the error message to provide more information about the error, the code above would break. But if custom error types were used, the error message is freed up so to speak for any other info.

**Comment by jmdobry** [comment]
No custom classes, instead error codes have been standardized. They've already been standardized in js-data core, adapters need to follow suit.
