### ISSUE TITLE
CSP violations due to use of new Function()

### ISSUE THREAD

**Issue by nealedj** [js-data/js-data#258]
It looks like `new Function()` is used [here](https://github.com/js-data/js-data/blob/64e765695f6142360733c40ccd90f5dde0b394d8/src/datastore/sync_methods/defineResource.js#L141)

It appears to be handled within the `try/catch` but it still raises a CSP violation in the browser.

It'd be most excellent if there was a setting where this could be disabled and the fallback behaviour was always used. I see that this was suggested in [this issue](https://github.com/js-data/js-data-angular/issues/242).

Thanks!

**Comment by jmdobry** [comment]
Hmm, I didn't know `new Function()` would do this. Your link to the issue is the same as the link to the code.

**Comment by nealedj** [comment]
Ah sorry - have updated to the actual issue (https://github.com/js-data/js-data-angular/issues/242)

**Comment by jmdobry** [comment]
My proposed fix is to add a flag that forces the library to not execute the code that raises the CSP violation warning. Is that sufficient?

**Comment by jmdobry** [comment]
@nealedj Thoughts?

**Comment by nealedj** [comment]
Sorry @jmdobry - was going to give that a test today but haven't got round to it yet.

The fix looks perfect though.

**Comment by nealedj** [comment]
Just to follow up - tested this and it works great. Thanks!
