### ISSUE TITLE
DSSqlAdapter and "endpoint"

### ISSUE THREAD

**Issue by andrejkaurin** [js-data/js-data#266]
I am working with NodeJS and have 2 models points to the same "table" in PostgreSQL.
As I see Adapter is ignoring the "endpoint" part in defineResource config which is, I suppose, by design (works fine on client side when pointing to the API endpoint).

```js
module.exports = db.store.defineResource({
  name: 'account',
  endpoint: 'my_table_name'
});
```
```js
module.exports = db.store.defineResource({
  name: 'invoice',
  endpoint: 'my_table_name'
});
```

Any chance to accomplish to have 2 defined resources/models pointing to the same table?

**Comment by jmdobry** [comment]
Yes, the sql adapter will look for a `table` option on Resources.



```js
module.exports = db.store.defineResource({
  name: 'account',
  table: 'my_table_name'
});
```
```js
module.exports = db.store.defineResource({
  name: 'invoice',
  table: 'my_table_name'
});
```
