### ISSUE TITLE
Accessing non-lazy loaded related object via property

### ISSUE THREAD

**Issue by nebulaszlonemethi** [js-data/js-data#267]
Hi,
maybe i missed something but could you tell me why i cannot get the related record via the object property defined as "localField", after i inject()-ed of find()-ed a record that contains the related data?

Yes i've read the documentation:) but this is not clear for me. I wrote some tests some monts ago on an earlier version of js-data, it worked fine.

See http://codepen.io/nlac/pen/jbQxLB?editors=001

**Comment by jmdobry** [comment]
The song that you're injecting is missing the `artistID` field. There is currently an [open issue](https://github.com/js-data/js-data/issues/251) to have js-data automatically add the field for you (like it does for the hasMany), but right now you need to make sure it's there. The examples in the docs always include the "localKey" field on child objects in belongsTo relationships.

**Comment by nebulaszlonemethi** [comment]
Ah, indeed, i missed that.. it works now, thanks for the tip.
