### ISSUE TITLE
endpoint should be part of queryHash in findAll

### ISSUE THREAD

**Issue by Patrik-Lundqvist** [js-data/js-data#276]
When doing two request against the same resource but using different endpoints only one request will be executed. Many APIs uses custom url-endpoints as resource filters, which should make the request unique.

**Comment by jmdobry** [comment]
Caching will be more configurable in v3. You'll be able to provide a custom hashing method.

**Comment by jmdobry** [comment]
In v3 you can now define your own query hashing function.
