### ISSUE TITLE
Creating instances of models doesn't work well with relations

### ISSUE THREAD

**Issue by MikaAK** [js-data/js-data#278]
Say I need to create an instance of a model so that I can work with a clone of the data, `model.createInstance` ignores relations so relations will not be cloned. Combined that with the inability to set relations since they are fetched via a getter makes it impossible to have relations that are unique instances. How can I solve this?

**Comment by jmdobry** [comment]
Relation links only work if the relations have been injected into the store.

This plunker demonstrates how even copies can still access relations if the relations have been injected: http://plnkr.co/edit/JupHjP?p=preview

If you also want copies of the relations (not just references to the originals) that you can modify, then don't use `createInstance` to create your copy. Use a POJO or custom class. Because if you use `createInstance`, then the resulting object will try to use the relation links, looking in the store for the relations.

**Comment by MikaAK** [comment]
Is there no way to disable getter/setters on an instance basis? I built up a library to manage js-data models so it can handle automatically saving/canceling but because I cannot clone relations this causes a bit of a bug. Using a POJO is a good idea my only concern is all the things I will need to reinvent to get it to work like a normal js-data object. The main model's js-data methods are heavily used as are the relational fields methods!

**Comment by jmdobry** [comment]
> Is there no way to disable getter/setters on an instance basis? 

The property accessors are on the prototype, so no.

Could you provide a more detailed description of what you're trying to accomplish? Perhaps provide some pseudo-code of how it "should" work, and I can help come up with a solution.

**Comment by MikaAK** [comment]
Sure! So essentially we display and modify many instances of the same data throughout a single page of our website. As an example, we have model `User` which we can say looks like this
```javascript
{
  userId: 5,
  name: 'billy'
  homeInfo: {
    address: '5423 Driver Street'
  }
}
```
Now in our display, it looks something like this
```
Name: Billy
Main Address: 5423 Driver Street

Edit Your Name:
name: Billy
cancel  save

Edit Your Address: 
address: 5423 Driver Street
cancel save
```

We don't want the address to update when saving name even if the address field has been changed. To solve this I created what I call ViewModel. ViewModel will do things such as when your saving it will pull the data from the store and only save usedFields you specified. So for example:

```
address changes from "5423 Driver Street" to "123 Hello Street" ->
name changes from "Billy" to "bob" ->
user hits save for name section ->
ViewModel.save is called with usedFields: ['name'] -> 
pulls last saved data from the store ->
takes name property from cloned instance of the model (created with `createInstance`) and appends it to store data -> 
calls save on this data -> 
data is successfully saved -> 
overwrite clonedInstances with the new name via on afterInject event listener. -> 
the title is updated to "bob"
``` 

Now this works absolutely great for base models, and it's proven itself to be one of the most useful things for our app. However, let's do address which is also used in the title.

```
address changes from "5423 Driver Street" to "123 Hello Street" -> 
because is a relation it automatically updates the title to "123 Hello Street" since they are referenced object.
```

As you can see this is where we are left hanging. Our code to create view models of data looks something like this, 
```javascript
  new ViewModel({
    model: 'User',
    sections: {
      naming: {
        usedFields: ['name'],
        createClone: true
      },
      
      addressArea: {
       usedFields: ['homeInfo'],
        createClone: true
      }
   }
  })
```

which returns an object similar to this

```
var viewModel = {
  data: {name: 'billy', ...etc}
  sections: {
    naming: {
       usedFields: ['name'],
       data: {name: 'billy', ..etc}
    },
 

    addressArea: {
       usedFields: ['homeInfo'],
      data: {name: 'billy', ..etc}
    }
  }
}
```
So we would use `viewModel.data.name` and `viewModel.data.homeInfo.address` to display the data and used the two section data's to modify it. 

The reason I would like to keep the data clones actual js-data models as opposed to just creating a POJO and using the POJO to update is for the use of `DSPrevious/DSRevert`. Both of which are instrumental to our cancels! With the addition of computed properties and such it allows for many different use cases and a very open-ended API to use.

Maybe it's possible to recreate all the methods I use and create a sort of stub object but ideally, I would like to avoid doing this.

**Comment by jmdobry** [comment]
If you disable the relation links entirely, then relations will be cloned, but they will not be kept up-to-date for you

**Comment by jmdobry** [comment]
v2 will probably be stuck with its limitations on relation linking. Relations are by far the most complicated part of js-data. Relation linking in v3 will be more flexible than v2, and your use case should be easier to address then.

**Comment by MikaAK** [comment]
Awesome I look forwards to v3. Will it be released soon since Object.observe is being done away with in April and being replaced by the new spec for [Observables](https://github.com/zenparsing/es-observable)

**Comment by jmdobry** [comment]
See #300 #307 #312
