### ISSUE TITLE
Delete object with hasMany does not delete dependend children?

### ISSUE THREAD

**Issue by AntonTrapp** [js-data/js-data#279]
Bug? Or could it be that there is no way to handle that? Or am I just blind and can't find something obvious like the "dependent: :destroy" in ActiveRecord? Can't find anything in the relations, destroy, ... docs. Neither do the examples address that topic.

If that is not provided I would have to handle all associations manually (then I could stick with $http too, less overhead and I have to do everything manually) or I can try to invalidate every data store after a delete od I could try to parse the relations and delete the children automatically in the afterDestroy callback. I can't be the only js-data user with associations... :D

**Comment by jmdobry** [comment]
v2 does not support this, but v3 will

**Comment by AntonTrapp** [comment]
Tnx for the fast answer (as always). I think I will try to hack in in something the next days (if I find the time) with parsing the data definition. Maybe I find something simple that I can add to v2 and some people can use it...

**Comment by jmdobry** [comment]
Yeah in v2 I usually use one of the "after" hooks to make cascading changes/deletions.
