### ISSUE TITLE
[Docs] Multiple adapters

### ISSUE THREAD

**Issue by mryellow** [js-data/js-data#28]
It's not immediately apparent if js-data supports saving to multiple adaters and syncing between them.

Use-case: Firebase with local storage for offline use.

API seems to register them into an array of adapters, so seems like it should at a glance of the source, however until I install and attempt it, there is no information in the docs to inform me of these capabilities.

**Comment by jmdobry** [comment]
I anyone doing offline syncing with js-data? I'd love to hear what devs are doing.

**Comment by jimthedev** [comment]
We currently are doing offline but are not using js-data in our angular app. I'd love to but I want to test the sql adapter with the SQLite cordova plugin but haven't yet had a chance.

**Comment by pdorgambide** [comment]
I am working on a offline sync implemetation with AngularJS and REST API.
[Best practice for on/off line data synchronization using AngularJS and Symfony 2](http://stackoverflow.com/a/28483715/1203628)

It doesn't use js-data but I think that integration could be a great bet.

**Comment by thebigredgeek** [comment]
I was actually thinking about this just today.  It might be a good idea to conceptualize the idea of having a "slave" adapter.  Where data read from the primary adapter gets sync'd into the slave.  IDK

**Comment by louiealmeda** [comment]
@jmdobry are there any plans on implementing this for v3? I think this would be a very helpful feature. Thanks for the wonderful framework.

**Comment by francesco-carrella** [comment]
+1
