### ISSUE TITLE
Building issues due to missing dependencies

### ISSUE THREAD

**Issue by davincho** [js-data/js-data#281]
I was not able to run `npm run test` js-data on a fresh Debian Jessie Box unless I installed the following npm dependencies globally.

``sudo npm install -g standard webpack babel-eslint uglifyjs mocha karma``

Probably this should be mentioned in https://github.com/js-data/js-data#pull-requests

**Comment by jmdobry** [comment]
What branch? Master?

**Comment by davincho** [comment]
Yes master

**Comment by jmdobry** [comment]
Each of the dependencies you mentioned are listed in [package.json](https://github.com/js-data/js-data/blob/master/package.json#L35). Did you not install devDependencies?

**Comment by davincho** [comment]
I followed each step and did `cd js-data; npm install; bower install;` as well. I will double check it with another fresh Vagrant Box!

**Comment by jmdobry** [comment]
Is the `NODE_ENV` env var somehow set to `production` on your box? That would prevent devDependencies from installing.

**Comment by davincho** [comment]
My bad - Vagrant had troubles symlinking some binaries. Building works just as described in your Readme.md!
