### ISSUE TITLE
LIKEI operator not supported

### ISSUE THREAD

**Issue by andrejkaurin** [js-data/js-data#285]
Regarding to this documentation LIKEI operator should be supported

http://www.js-data.io/docs/query-syntax

but it is not - at least for DSSqlAdapter (PostgreSQL)

Error is : ERR [Error: Operator not found]

**Comment by jmdobry** [comment]
Closing and moving this issue to js-data/js-data-sql#50

**Comment by techniq** [comment]
@andrejkaurin See my comment on https://github.com/js-data/js-data-sql/issues/50#issuecomment-176747855 about using a custom query operator until a better solution is provided
