### ISSUE TITLE
Same localField and localKey

### ISSUE THREAD

**Issue by Tronix117** [js-data/js-data#289]
Hello,

I'm using an API I have no control on and I'm running into some issues.
Those two structures can be sent to me (I changed exemple objects so it can be easily understandable):

```coffee
    # Let's imagine some structure like those
    
    # /api/comments
    [
      {
        id: 1,
        subject: 'Subject 1',
        author: 1
      },
      {
        id: 1,
        subject: 'Subject 2',
        author: 2
      }
    ]

    # /api/comments/1
    {
      id: 1,
      subject: 'Subject 1',
      content: 'This is the first comment.',
      author: {
        id: 1,
        alias: 'foo-bar',
        name: 'Foo Bar',
        group: 1
      }
    }
```

Like you can noticed, in the `/api/comments` collection, the `author` is NOT nested and only the `id` is returned. However in `/api/comments/1`, we got the nested `author` object and not directly its `id`. 

For collection, there will be 0 level of nesting, and for resources, there will be 1 level of nesting.

The issue here is not really the design, but the naming, there is no `author_id` or `group_id`, but only `group` and `author` either for the `id` or for the nested object. However in JS-Data, the localField can not be the same as the foreignKey otherwise, there will be an issue with the injection.

Is there a workaround, knowing that the API can not be modified ?

```coffee
    DS.defineResource
      name: 'comment'
      relations:
        belongsTo:
          user:
            localField: 'author'
            localKey: 'author'

**Comment by jmdobry** [comment]
Have you looked at http://plnkr.co/edit/DwbJOS?p=preview? (Which is found [here](http://www.js-data.io/docs/examples#relations).)

**Comment by Tronix117** [comment]
Ok I dig a little bit more, and to get your `fixRelations` function to work with my needs, I just had to had a check to the `fixLocalKeys` function like this:

```javascript
function fixLocalKeys(_instance) {
  //=> Code addition
  if(!JSData.DSUtils.isObject(_instance[def.localField])) {
    delete _instance[def.localField];
  }
  //<=

  var relationInstance = _instance[def.localField];
  
  if (relationInstance) {
    if (!_instance[def.localKey] && relationInstance[relationDef.idAttribute]) {
      _instance[def.localKey] = relationInstance[relationDef.idAttribute];
    }
    if (def.type === 'hasOne') {
      fixRelations(relationDef, relationInstance);
    }
  }
}
```

It allows a structure like this:

```coffeescript
# /api/comments/1
{
  id: 1,
  subject: 'Subject 1',
  content: 'This is the first comment.',
  author: {
    id: 1,
    alias: 'foo-bar',
    name: 'Foo Bar',
    group: 1,
    comment: 1 # it removes this field on the deserialization. Of course for a user/comment structure it will never be like that, but for a more hierarchical structure, I had this issue.
  }
}
```
