### ISSUE TITLE
Please update docs

### ISSUE THREAD

**Issue by mxrguspxrt** [js-data/js-data#292]
In documentation it is really hard to find how to create a new instance into memory, store it into store and backend.

Please add an example into Javascript section: 
http://www.js-data.io/docs/home 

I come from ember-data background, and even for me it is really hard to understand .createInstance vs .inject and why my model requires to have ID, if it has not been saved, or why it does not create POST (but UPDATE instead) if I generate id on client side and try to save with Model.create(instance).

It would be awesome also a simple guide for those who come from ember-data world.

**Comment by mechanicalpulse** [comment]
The project is using readme.io for documentation, which makes it really easy to integrate user suggested documentation changes.  There is a link on every page of the documentation you may use to suggest changes for the page.  Here's the direct link from the one you mentioned: http://www.js-data.io/docs/home/edit

**Comment by jmdobry** [comment]
Closing in favor of #308
