### ISSUE TITLE
Eject related objects

### ISSUE THREAD

**Issue by ostcar** [js-data/js-data#295]
I have a resource 'motion' with a relation to motionpoll. The relation is defined on the motion relation with
```
relations: {
  hasMany: {
    'motionpoll': {
    localField: 'polls',
    foreignKey: 'motion_id',
  }
}
```
If there is a motion with some polls and I eject the motion, then the motionpoll objects are still in the DS-store. This is a problem when I later inject a motion with the same id. In this case the new motion will have all posts from the old motion.

What I relay trying to do is replacing a motion object from the store with a new one where some poll objects do not exist anymore. I tried this with ```motion.inject(motion.id, newMotion, {'onConflict': 'replace'})``` but in this case motion.polls does still have the old poll objects.

**Comment by jmdobry** [comment]
In 2.x, you'll either need to eject the related motionpolls, or delete their `motion_id` field.

```js
Motion.eject(motion.id)
MotionPoll.eject({ motion_id: motion.id })
```
or
```js
Motion.eject(motion.id)
MotionPoll.filter({ motion_id: motion.id }).forEach(function (motionpoll) {
  delete motionpoll.motion_id
})
```

**Comment by ostcar** [comment]
Do you have any tip how this could be done in a generic way? In my case the server sends all data to the client, that has changed. Then the client calls:
```
DS.inject(data.collection, data.data);
```

In a generic way I have to go though all relations, and enject them.

On the django ORM there is a "on_delete" featur: https://docs.djangoproject.com/en/1.9/ref/models/fields/#django.db.models.ForeignKey.on_delete

It would be nice if there could be a similar feature in ds-data.

**Comment by jmdobry** [comment]
Each Resource has a `relationList` field, which is an array. You can iterate over the array and eject each of the relations. This is a generic solution.

```js
function ejectRelated (Resource, instance) {
  Resource.relationList.forEach(function (relationDef) {
    if (relationDef.localKey) {
      Resource.getResource(relationDef.relation).eject(instance[relationDef.localKey])
    } else if (relationDef.foreignKey) {
      var query = {}
      query[relationDef.foreignKey] = instance[Resource.idAttribute]
      Resource.getResource(relationDef.relation).ejectAll(query)
    }
    // there are a few other edge cases to account for still
  })
}

Motion.eject(motion.id)
ejectRelated(Motion, motion)
```

**Comment by ostcar** [comment]
Thanks. It works.

I only had to remove ```if (relationDef.localKey) {...}``` because I only want to eject related object that are "inside" the motion object.
