### ISSUE TITLE
js-data.io is not resolving

### ISSUE THREAD

**Issue by jsenecal** [js-data/js-data#296]
js-data.io is not resolving anymore...

**Comment by jmdobry** [comment]
Perhaps the Readme.io servers were down for a time? It's up for me now. This is what I see
![screen shot 2016-01-19 at 9 20 53 am](https://cloud.githubusercontent.com/assets/1213510/12426336/03123568-be8e-11e5-8a52-77a4f4370983.png)

Is it up for you now?

**Comment by jsenecal** [comment]
ERR_NAME_NOT_RESOLVED in chrome - i'll try to flush my dns entries...

**Comment by jsenecal** [comment]
Okay - its back :)
