### ISSUE TITLE
Add documentation that defining a resource can only happen once

### ISSUE THREAD

**Issue by chrisabrams** [js-data/js-data#298]
When calling `defineResource`, the result is stored on the `store` as `store.definitions.<resource name>`. You cannot call `defineResource` a second time with the same name, and `defineResource` does _not_ return the instance when it's already created.

Recommending that it's added to the docs, as well as in the command line, making it clear the error is that the resource is what was already created.

**Comment by jmdobry** [comment]
Note that there is a "Suggest Edits" button at the top right of every doc page where you can make your suggested changes, which can then be merged in.

**Comment by chrisabrams** [comment]
I did that once the slack group showed me that :O
