### ISSUE TITLE
Injecting a new record object structure of an existing record throws an error

### ISSUE THREAD

**Issue by crobinson42** [js-data/js-data#299]
js-data 2.8.2
js-data-http 2.1.2

When injecting an object over an existing instance already in the resource (same id's), if an attribute on the new object being injected is different then the existing attribute type (`typeof`), an error is thrown that does not relate.

Console showing `console.log` of existing record attribute being a string then an `inject` comes along with an attribute in the record that is now an object and the error is thrown
```
bundle.js:17644 Existing Location attr:  5671e6538abd876429ffe0ff
bundle.js:17645 Injecting Location attr:  5671e6538abd876429ffe0ff
bundle.js:17644 Existing Location attr:  5671e6538abd876429ffe0ff

bundle.js:17645 Injecting Location attr:  Object {active: true, city: "Sacramento", createdAt: "2015-12-16T22:31:47.576Z", fullAddress: "undefined↵ undefined, undefined undefined"…}

Uncaught (in promise) IllegalArgumentError {type: "IllegalArgumentError", message: ""id" must be a string or a number!"}

bundle.js:17644 Existing Location attr:  Object {active: true, city: "Sacramento", createdAt: "2015-12-16T22:31:47.576Z", fullAddress: "undefined↵ undefined, undefined undefined"…}
bundle.js:17645 Injecting Location attr:  Object {active: true, city: "Sacramento", createdAt: "2015-12-16T22:31:47.576Z", fullAddress: "undefined↵ undefined, undefined undefined"…}
```

It seems that anytime an existing instance's attribute `typeof` is changed on an inject it throws this error: 

```
Uncaught (in promise) IllegalArgumentError {type: "IllegalArgumentError", message: ""id" must be a string or a number!"}
```

Screencast:
http://recordit.co/lA6YrL7rBw

**Comment by jmdobry** [comment]
Can you post the _exact_ data that's being passed to `inject`?

**Comment by crobinson42** [comment]
user code issue...
