### ISSUE TITLE
Object.observe is deprecated since Chrome 49

### ISSUE THREAD

**Issue by greenify** [js-data/js-data#300]
When using js-data I see the message:

> 'Object.observe' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/6147094632988672 for more details.

Is this known?

**Comment by jmdobry** [comment]
Yes, use of Object.observe had been dropped in 3.x

**Comment by greenify** [comment]
Oh thanks - sorry for troubling you then ;-)

**Comment by nealedj** [comment]
Presumably observe.js will fall back to microtask checkpoints when Chrome removes `Object.observe`? So people don't need to upgrade to v3 (beta) yet?

**Comment by jmdobry** [comment]
Right, and this is also why js-data works in other browsers.

**Comment by yogidevbear** [comment]
Any idea when v3 will be out of beta? We are running a 2.x version in production and are a bit concerned about this warning for deprecation in Chrome in April (which we are now into).

**Comment by jmdobry** [comment]
js-data 3.0.0-beta.1 was only released 12 hours ago, I haven't exactly set a date for 3.0.0 stable.

While that warning is annoying, js-data 2.x will continue to work in Chrome for the same reason js-data works in all the other browsers (which don't support `Object.observe`).
