### ISSUE TITLE
Docs: Show how to override caching hooks to update cached queries

### ISSUE THREAD

**Issue by antoinebrault** [js-data/js-data#301]
Just an idea. I keep copying the same code for each project I do.

Currently, when an item is ejected, it is removed from each resource queryData lists but it is not added on creation. 

See: https://github.com/js-data/js-data/blob/edc7793feb10ca001a6a9efe2be4e92247d5aad1/src/datastore/sync_methods/eject.js#L53

I keep using:

``` javascript
afterCreate: function(resource, data, cb) {
    var queryData = DS.store[resource.name].queryData;

    for (var k in queryData) {
        if (queryData.hasOwnProperty(k)) {
            queryData[k].length = 0;
            Array.prototype.push.apply(queryData[k], DS.filter(resource.name, angular.fromJson(k)));
        }
    }

    cb(null, data);
}
```

The only issue I see is when you have special queries filtered on the backend.

Maybe it could be added as an example in the docs for others to use.
- [x] - [Example in API docs](http://api.js-data.io/js-data/latest/index.html)
- [ ] - Example in tutorial docs (http://js-data.io)

**Comment by jmdobry** [comment]
Have you ever tried using the `useFilter: true` option instead of doing this?

**Comment by antoinebrault** [comment]
My issue isn't with findAll, it is with .create(). 

Let's say I have a data table, a "Add" button that opens a dialog and a "Delete" button on each row.

When I delete a row, .destroy() will automatically remove the item from my array.
When I add a new row, .create() will not add the new item to the array. I have to manually add it.

**Comment by jmdobry** [comment]
Understood

**Comment by jmdobry** [comment]
This will be a little tricky because how will JSData know which lists to add the new item to?

**Comment by jmdobry** [comment]
I think this is one of those things that is not well suited to a general solution. That being said, the `DataStore` component in v3 provides hooks that allow one to implement a solution to this that is specific to the app.

Will keep this open until overriding those hooks in v3 is documented.
