### ISSUE TITLE
Cannot override default suffix

### ISSUE THREAD

**Issue by eeejayg** [js-data/js-data#303]
If you set up a default suffix, such as this:

        DS.adapters["http"].defaults.suffix = ".json";

When you subsequently try to override with a different suffix:

    .factory('PromoAction', function( DS ) {
        return DS.defineResource({
            suffix: ".action",
        });
    });

It works fine.  the new suffix ".action" is used.  However, if you try to override the suffix with null or an empty string, you get the default suffix.  In this example I am trying to say "do not use a suffix" but it still uses the default ".json" suffix:

    .factory('PromoAction', function( DS ) {
        return DS.defineResource({
            suffix: "",
        });
    });

**Comment by jmdobry** [comment]
This might work until I can get a fix in:

```js
.factory('PromoAction', function( DS ) {
  var emptySuffix = {};
  emptySuffix.toString = function () { return ""; };
  return DS.defineResource({
    suffix: emptySuffix,
  });
});

**Comment by jmdobry** [comment]
Closing in favor of js-data/js-data-http#39
