### ISSUE TITLE
'Object.observe' is deprecated -- in Google Chrome Canary

### ISSUE THREAD

**Issue by slanska** [js-data/js-data#307]
Warning ['Object.observe' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/6147094632988672 for more details.], in js-data.js:2410 is being reported when running pn Google Chrome Canary (Version 50.0.2643.0 canary (64-bit)). I guess, a conditional workaround would be needed to resolve this? Thanks.

**Comment by jmdobry** [comment]
Duplicate of #300
