### ISSUE TITLE
Resource with multiple parent isn't working

### ISSUE THREAD

**Issue by mustela** [js-data/js-data#309]
I have the following `MessageResource`:

```
DS.defineResource({
    changesOnly: true,
    name: 'message',
    endpoint: 'messages',
    relations: {
        belongsTo: {
            user: {
                localField: 'user',
                localKey: 'user_id'
            },
            job: {
                parent: true,
                localField: 'job',
                localKey: 'job_id'
            },
            estimate: {
                parent: true,
                localField: 'estimate',
                localKey: 'estimate_id'
            }
        }
    }
});
```

If I do
```
payload.job = job;
MessageResource.create(payload)
```
It `POST /messages` when it should post to `/jobs/xxx/messages`, but if I remove the `parent: true,` from the estimate relations it works as expected. 

I followed whats documented in here https://github.com/js-data/js-data/pull/305

Thanks

**Comment by jmdobry** [comment]
Sorry, I haven't released js-data-http yet, where there is another pull request to support this functionality.

**Comment by mustela** [comment]
Oh sorry didn't see that. Np, will wait for that release ;)

**Comment by jmdobry** [comment]
js-data-http has a new release with #305 incorporated.

**Comment by mustela** [comment]
Nice!!
