### ISSUE TITLE
Potential issue with multiple belongsTo relations with parents defined

### ISSUE THREAD

**Issue by jimobrien** [js-data/js-data#311]
I'm encountering a strange behavior when requesting a resource that belongs to more than one parent.  Say the following  `Action` can be owned by a `User` and a `Concept`:

```js
...
.service('Action', function(DS) {
  return DS.defineResource({
    name: 'actions',
    idAttribute: '_id',
    relations: {
      belongsTo: {
        concepts: {
          localField: 'concept', 
          localKey: 'conceptId', 
          parent: true
        },
        users: {
          localField: 'user',
          localKey: 'createdById',
          parent: true
        }   
      }
    }
  });
})

``` 

Here's what I was expecting: 
`Action.findAll({ createdById: 1 })` => `GET /users/1/actions`
`Action.findAll({ conceptId: 2 })` => `GET /concepts/2/actions` 

But that doesn't appear to be the case when making the request through the parent Concept.. Instead this happens:
`Action.findAll({ conceptId: 2 })` => **`GET /actions?conceptId=2`**

What's interesting is that by changing the order in which the `belongsTo` relationships are defined flips the above results:

```js
// flip order that the belongsTo relations are defined
relations: {
  belongsTo: {
    users: {
      localField: 'user',
      localKey: 'createdById',
      parent: true
    },
    concepts: {
      localField: 'concept', 
      localKey: 'conceptId', 
      parent: true
    }
  }
}
```

Making the same `findAll` calls produces this:

`Action.findAll({ createdById: 1 })` => `GET /actions?createdById=1`
`Action.findAll({ conceptId: 2 })` => `GET /concepts/2/actions` 

plunker: http://plnkr.co/edit/MDxL4gL7sqnwf5vnxXHB

Is this expected?

**Comment by tfoxy** [comment]
This was solved in v2.9.0 of js-data and v2.2.0 of js-data-http. But js-data-angular 3.1.0 is built with js-data-http 2.1.1.

A new release of js-data-angular with js-data-http 2.2.0 would solve this issue.

**Comment by jmdobry** [comment]
Good catch, I need to make a new release.

**Comment by jmdobry** [comment]
Done: https://github.com/js-data/js-data-angular/releases/tag/3.2.1
