### ISSUE TITLE
Aurelia Integration - Unknown changeRecord type: reconfigure

### ISSUE THREAD

**Issue by jimnorth55** [js-data/js-data#312]
Using  js-data in an Aurelia project causes an 'Unknown changeRecord type: reconfigure' to be thrown.  The Aurelia team (re: [Issue 322](https://github.com/aurelia/binding/issues/322)), is citing the use of Object.observe in js-data as the "cause".   

I would like to utilize js-data in my project, but this issue is of concern.  Do you have any comments or suggestions?

Thanks for all of your excellent work!

**Comment by jmdobry** [comment]
Have you read #300 and #307?

**Comment by jimnorth55** [comment]
No I hadn't.  My search of existing issues was a bit hasty. Sorry.
