### ISSUE TITLE
v3: build in function to return difference between current and previous data

### ISSUE THREAD

**Issue by k2s** [js-data/js-data#313]
To use `Record.hasChanged()` in v3 I have to implicitly enable change tracking.
The function Record.revert() works different, it loops over the values.

Could there be function e.g. `Record.hasChangedPrevious()` which would evaluate change in data by looping over the values ?

**Comment by jmdobry** [comment]
Are you looking for `Record#changes()`?

**Comment by k2s** [comment]
If I understood you right on gitter, changes are accumulated only if I implicitly enable it.

I need to test if the record was changed without to enable change monitoring and came up with something like (using lodash):
{code}
var previous = record._get('previous') || {};
if (!_.isEqual(record.toJSON(), previous)) {
    // data was changed
}
{code}

**Comment by jmdobry** [comment]
Ah, haha! I didn't even think of that. I forgot that when `Record` is instantiated the values are saved and can be retrieved via `Record#previous()`. Yeah, `track: true` enabled real-time change detection and on-assignment validation, and `Record#changes()` returns statically saved changes. But diffing `Record` and `Record#previous()` can be a sort of passive change detection.

I will think on this a little more and clean up the API a bit.

**Comment by k2s** [comment]
I am happy I am not completely wrong.
Maybe you could also consider that if `revert()` supports `opts.preserve`, the same property should be supported by `changes()` and `passiveChanges()`.

**Comment by jmdobry** [comment]
http://api.js-data.io/js-data/3.0.0-alpha.19/Record.html#changes__anchor

http://api.js-data.io/js-data/3.0.0-alpha.19/Record.html#hasChanges__anchor
