### ISSUE TITLE
Example given for relations in docs now working

### ISSUE THREAD

**Issue by riorulzz** [js-data/js-data#314]
http://plnkr.co/edit/UsPrQBG9Oo4JVAItYZar?p=preview

```js
angular.module("app", ['js-data']);
app = angular.module("app");

app.service('Comment', function(DS) {
		    return DS.defineResource({
          name: 'comment',
          relations: {
            belongsTo: {
              post: {
                parent: true,
                localKey: 'postId',
                localField: 'post'
              }
            }
          }
        });
		  });
		  
app.run(function($http, Comment){
  Comment.find(5, { params: { postId: 4 } }); // GET /post/4/comment/5
});
```

This is triggering `GET /comments/5?post=4` and not `GET /post/4/comment/5`

**Comment by riorulzz** [comment]
Issue resolved .. 
Problem was angular services are lazily loaded.. 
If we have defined model, it will only be activated if injected anywhere ...

I was injecting Comment Model for calling Comment.find ... So comment model was getting initialised but Post Model was never getting initialised and hence relationship was never established ..

**Comment by jmdobry** [comment]
Yep: http://www.js-data.io/docs/js-data-angular#section-angular-s-di-is-lazy
