### ISSUE TITLE
Merge/Replace inject does not reevaluate computed properties

### ISSUE THREAD

**Issue by kenborge** [js-data/js-data#316]
Hi.
Have discovered something i would consider a bug with the inject code.
The first time an item is injected into the store the result you get back from DS.inject() will have all computed properties evaluated and ready when the function returns. 
But if an item exists in the store already with the same ID, then computed properties on the value returned from DS.inject() have not been reevaluated yet. This means for the different OnConflict strategies:
Merge: The item will have the old computed properties and not be updated yet. 
Replace: The item will have no computed properties because they where deleted and are not evaluated again yet.

My guess is that this happens because the computed properties are triggered manually the first time the item is injected, but on the second there is some async change handler that causes them to be reevaluated so it happens after the function returns.

**Comment by kenborge** [comment]
This also means that if you have a find or findAll with bypassCache for instance the computed properties will not be ready when the find/findAll promise resolves.

**Comment by jmdobry** [comment]
So after merge, need to recompute properties, and _before_ replace, need to invoke the computed properties on the replacing item, so the computed properties won't be removed from the existing item?
