### ISSUE TITLE
Performance issue - diffObjectFromOldObject

### ISSUE THREAD

**Issue by samuelcastro** [js-data/js-data#318]
I'm getting troubles with bad performance, looks like this is related to diffObjectFromOldObject, see screenshots got from Firefox:

"js-data": "2.8.2",
"js-data-angular": "~3.1.0"

![debug1](https://cloud.githubusercontent.com/assets/5281701/14545608/73ee9480-0276-11e6-827d-1718cdd2d907.png)
![debug2](https://cloud.githubusercontent.com/assets/5281701/14545680/ae565464-0276-11e6-9375-0e865bed8374.png)

**Comment by samuelcastro** [comment]
@jmdobry Debugging I was able to see the issue is related to `diffObjectFromOldObject`.
![screen shot 2016-04-15 at 11 23 57 am](https://cloud.githubusercontent.com/assets/5281701/14564385/b744d48e-02fc-11e6-9d03-aa10ef40cd27.png)

**Comment by jmdobry** [comment]
Ah, change detection. Are you injecting a lot of data into the store?

**Comment by samuelcastro** [comment]
@jmdobry Yes, I'm injecting and looks like this issues is related, not sure yet: https://github.com/js-data/js-data-angular/issues/282

**Comment by jmdobry** [comment]
Try disabling change detection: `watchChanges: false`

**Comment by samuelcastro** [comment]
@jmdobry Disabling change detection fix the problem, but based on the documentation, disabling change detection we disables the standard computed properties, recording of change history, the automatic updating of entities' "last modified" timestamp, and the firing of the DS.change event right? Is there a workaround on it?

**Comment by MikaAK** [comment]
Disabling change detection isn't a great solution here as it breaks how js-data works at it's core and causes forced awareness over where you have used `watchChanges: false`, this leads to all sorts of problems and hurts maintainability. Maybe something like `watchChanges: false` as part of config for calls? Is there another way?

**Comment by jmdobry** [comment]
From Slack:

> @samuelcastro: @jmdobry I think should be helpful has a `watchChanges` per-method call dont you think?
> @jmdobry: It doesn’t work that way. What you want would require a fundamental change in how change detection works. JSData would need to be rewritten from scratch.
> Which is exactly what I did for v3 (currently in alpha)

**Comment by MikaAK** [comment]
so then it's either break maintainability or wait till v3, is there no other solution?

**Comment by samuelcastro** [comment]
@jmdobry @MikaAK The issue was not related with `diffObjectFromOldObject ` and `change detection` was related to a relationship that was using `enumerable: true`.

Thank you guys.

**Comment by freedomflyer** [comment]
Turning off `watchChanges` did wonder for me with this specific issue.
