### ISSUE TITLE
Not all destroy callbacks are fired

### ISSUE THREAD

**Issue by iabdulin** [js-data/js-data#319]
http://www.js-data.io/docs/model-lifecycle#section-ds-destroy-ds-destroyall

Lists following callbacks:
- beforeValidate
- validate
- afterValidate
- beforeDestroy
- afterDestroy

Looks like only `beforeDestroy` and `afterDestroy` are actually fired.
I don't know if it's a problem with documentation or the code itself.

Plunker:
http://plnkr.co/edit/r7ZqX5se7Y3LDxGA8GXo?p=preview

![image](https://cloud.githubusercontent.com/assets/622315/14582941/462e9094-03d0-11e6-94f6-09be0a2901ec.png)

**Comment by jmdobry** [comment]
It's a problem with the documentation. `destroy` and `destroyAll` do not call validation lifecycle hooks.

Docs are fixed now.
