### ISSUE TITLE
New created data only accessible after a page refresh

### ISSUE THREAD

**Issue by remicastaing** [js-data/js-data#321]
I'm using js-data with angular and the DSLocalStorageAdapter.

After creating (DS#create) new data, I'm changing the page and request an overview of all datas (DS#findAll). But I'm not getting the new created data.

Only after refreshing the page, I can get this new data.

Is there a reason why all new created data are only accessible after a page refresh?

**Comment by jmdobry** [comment]
Yes, it's because in 2.x, `useFilter` defaults to `false`. Try setting `useFilter` to `true`.

You can find the details regarding the mechanics of `DS#findAll` here: http://www.js-data.io/v2.8/docs/dsfindall

**Comment by remicastaing** [comment]
Merci @jmdobry, you rock! It works!
