### ISSUE TITLE
jspm incompatibility

### ISSUE THREAD

**Issue by k2s** [js-data/js-data#322]
js-data 2 and 3 doesn't work when bundled with latest jspm

jspm handles js-data as AMD module and bundles it wrongly

possible fix would be add to package.json:
```
"format": "global"
```

https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#package-module-format

**Comment by guilhermeaiolfi** [comment]
You can enforce the format in your config.js file so jspm ignores detecting the format and use the one you specify. But, sure, it would be better in the long term to solve it upstream.

**Comment by k2s** [comment]
@guilhermeaiolfi yes, I did it this way, but overrides are removed by jspm when it touches package.json. in jspm tickets it is mentioned that overrides are meant only for debugging.

**Comment by jmdobry** [comment]
> When loading modules from `npm`, the module format is treated as `cjs` by default and no automatic detection is run.

@k2s Are you loading js-data from npm? `require('js-data')` or `import JSData from 'js-data'` or something like that?

**Comment by k2s** [comment]
using it in Aurelia and `import JSData from 'js-data'`
simple loading is not a problem, but if I try to bundle it then it is recognized as amd module

js-data-http is recognized correctly.

**Comment by guilhermeaiolfi** [comment]
I meant something like that in your config file:

```javascript
System.config({
  "meta": {
    "js-data/js-data": {
      "format": "global"
    }
  }
});
```

**Comment by jmdobry** [comment]
Note, `js-data` v3 does not have a default export, so `import JSData from 'js-data'` won't work. You need `import * as JSData from 'js-data'`, or only import the components you need: `import {DataStore} from 'js-data'`.

I just confirmed `js-data` `3.0.0-beta.10` works with jspm by following [this tutorial](http://jspm.io/docs/getting-started.html) to create a new jspm project, then I did `jspm install npm:js-data@3.0.0-beta.10`, then imported js-data into the app via `import {DataStore} from 'js-data'`, and everything worked.
