### ISSUE TITLE
Inconsistent defaultValues behavior. 

### ISSUE THREAD

**Issue by facultymatt** [js-data/js-data#324]
jsData 2.9.0
Angular 1.5.3

When defining a resource, its possible to set defaultValues, as documented here: http://www.js-data.io/docs/dsdefaults#defaultvalues

This only works when calling `DS.createInstance()`. Why not also apply defaults in `DS.inject()`? I would expect that any method which injects, creates, etc. a new instance of a model applies the defaultValues.  

Secondly, the documentation for createInstance incorrectly notes `options.defaults` see https://github.com/js-data/js-data/blob/v2/src/datastore/sync_methods/index.js#L153

**Comment by jmdobry** [comment]
I can't make any breaking changes in 2.x, so I'm adding an option `applyDefaultsOnInject` so you can opt into your desired behavior. This will be available in 2.10.0, but not in 3.x (3.x doesn't have this issue).
