### ISSUE TITLE
Return query metadata in 

### ISSUE THREAD

**Issue by kpelckmans** [js-data/js-data#325]
Following the great implementation after discussion in https://github.com/js-data/js-data/issues/162, could the metadata also be made available in all events listed on http://www.js-data.io/docs/events?

**Comment by jmdobry** [comment]
With how [`raw: true`](http://api.js-data.io/js-data/latest/Mapper.html#toc14__anchor) is implemented in v3, this is already available. For some events however, there is no other metadata besides what's already passed to the event.
