### ISSUE TITLE
filter with parenthesis ()

### ISSUE THREAD

**Issue by georgi-kovachev** [js-data/js-data#331]
I am wondering how to create filter json to accomplish like this.

select * from history where entity_type='contract' or (entity_type='contract_section' and parent_id = 3)

I am checking on this page, but couldn't find it.
http://www.js-data.io/docs/query-syntax

where: {
    'age': {
      '>=': 30,
      '<=': 33
    }
  }

**Comment by georgi-kovachev** [comment]
or something like this
select * from history where (entity_type='contract_section' and parent_id = 3) or (entity_type='document' and parent_id = 3) or entity_type='contract'

**Comment by jmdobry** [comment]
Unfortunately, neither of those queries are expressible in the current JSData query syntax.

**Comment by jmdobry** [comment]
Closest you could get would be:

```js
{
  where: {
    entity_type: {
      'in': ['contract', 'contract_section']
    },
    parent_id: {
      '==': '3'
    }
  }
}
```

or

```js
{
  where: {
    entity_type: {
      'in': ['contract_section', 'document', 'contract']
    },
    parent_id: {
      '==': 3
    }
  }
}
```

**Comment by jmdobry** [comment]
I just added support for grouped clauses in js-data 3.0.0-beta.6
