### ISSUE TITLE
Cannot cancel requests from the DSHttpAdapter in Angular

### ISSUE THREAD

**Issue by n8agrin** [js-data/js-data#338]
Angular 1.3.15
js-data 2.3.2
js-data-angular 3.1.0

The docs claim that when working with Angular, DSHttpAdapter will act as a pass through to Angular's `$http` library. While this is mostly true, it appears that DSHttpAdapter mutates any values set in options, perhaps by copying them. This is particularly noticeable if you would like to pass a Promise object through to the `timeout` property of `$http` calls in order to cancel them. DSHttpAdapter converts them to a vanilla object and queries cannot be canceled.

**Comment by jmdobry** [comment]
Upgrade to the latest `js-data-angular`, as this has already been fixed.

See js-data/js-data-http#44

**Comment by n8agrin** [comment]
@jmdobry any idea why this is not in 2.3 or higher? We're running 2.8.2 and it definitely does not work.

![image](https://cloud.githubusercontent.com/assets/6043/15554806/aabe950e-227a-11e6-85fb-1c141ab2afa8.png)

**Comment by n8agrin** [comment]
I see, it's a different repro, js-data-http
