### ISSUE TITLE
Update bower 

### ISSUE THREAD

**Issue by demisx** [js-data/js-data#34]
Installing from bower gives me 0.4.2 version. The latest stable appears to be `1.0.0-beta.1`. Is it time to update bower, so it's in sync with latest stable as npm?

**Comment by jmdobry** [comment]
The `1.0.0-beta.1` release is available from both Bower and Npm. Bower handles things differently, so you'll just have to specify `"js-data": "1.0.0-beta.1"` in your `bower.json`.

`bower install js-data` yields 0.4.2

`npm install js-data` yields 1.0.0-beta.1

Go figure...

**Comment by demisx** [comment]
I think it pulls 0.4.2 because bower has current version set as `0.4.2` (see info output below).  Maybe you should add the `version` field to your package `bower.json` and set the version there, similar how you have it in `package.json`? 

```bash
$ bower info js-data
```

yields this (see `version: '0.4.2'` line):
 
```js
{
  name: 'js-data',
  description: 'Data store.',
  version: '0.4.2',
  },
  author: {
    name: 'Jason Dobry',
    url: 'http://www.pseudobry.com',
    email: 'jason.dobry@gmail.com'
  },
  main: './dist/js-data.min.js',
  ignore: [
    '.idea/',
    '.*',
    '*.iml',
    'src/',
    'lib/',
    'doc/',
    'guide/',
    'coverage/',
    'Gruntfile.js',
    'node_modules/',
    'test/',
    'package.json',
    'karma.conf.js',
    'karma.start.js'
  ],
  devDependencies: {
    'observe-js': '0.3.4',
    'js-data-http': '~0.4.x',
    'js-data-localstorage': '~0.4.x'
  }
}

Available versions:
  - 1.0.0-beta.1
  - 1.0.0-alpha.5-8
  - 1.0.0-alpha.5-7
  - 1.0.0-alpha.5-6
  - 1.0.0-alpha.5-5
  - 1.0.0-alpha.5-4
  - 1.0.0-alpha.5-2
  - 1.0.0-alpha.5-1
  - 1.0.0-alpha.5-0
  - 1.0.0-alpha.4-3
  - 1.0.0-alpha.4-2
  - 1.0.0-alpha.4-1
  - 1.0.0-alpha.4-0
  - 1.0.0-alpha.3-0
  - 1.0.0-alpha.1-2
  - 1.0.0-alpha.1-1
  - 1.0.0-alpha.1-0
  - 1.0.0-alpha.2
  - 0.4.2
  - 0.4.1
  - 0.4.0
  - 0.3.1
  - 0.2.0
  - 0.0.1
```

**Comment by demisx** [comment]
Also, this could be because bower doesn't see `1.0.0-beta.1` as latest stable due to `-beta*` prefix and gives 0.4.2 as latest stable. I am rereading bower docs now.

**Comment by demisx** [comment]
OK, if I understood correctly, bower considers `1.0.0-beta.1` a pre-release version and if no version is specified at command line, it will download the latest **release** version that is currently `0.4.2`. To install the latest beta at command line, one needs to run this:

```bash
$ bower i js-data#1.0.0-beta.1
```

**Comment by jmdobry** [comment]
Bower completely ignores the "version" field if it exists in `bower.json` and only considers git tags to be available versions.
