### ISSUE TITLE
Lifecycle hook not firing

### ISSUE THREAD

**Issue by remicastaing** [js-data/js-data#346]
I define following ressources (`WPI_Segment` is a children element `ScheduledMaintenance`):
```
angular.module('itechApp')
.factory('WPI_Segment', function (store, ataspechelper) {
  return store.defineResource({
    name: 'WPI_Segment',
    idAttribute : 'WPI',
    beforeCreate: beforeCreateWPI,    
    relations: {
      belongsTo: {
        ScheduledMaintenance: {
            localField: 'ScheduledMaintenance',
            localKey: 'WPI'
          }
        }
      },
      methods : {
        toJson: function(){
          return _.pick(this,_.keys(ataspechelper.definition.WPI_Segment));
        }
      }
    }
    );
})
```

If I'm running `WPI_Segment.create(data)`, the lifecycle hook `beforeCreate`is not firing. None of the other lifecycle hooks of the children element of `ScheduledMaintenance` are firing. Only the lifecycle hooks `ScheduledMaintenance` are working.

**Comment by remicastaing** [comment]
There is something weird. I created a new Ressource: `Test_segment`:
```
'use strict';

angular.module('itechApp')
.factory('Test_Segment', function (store) {
  return store.defineResource({
    name: 'Test_Segment',
   // idAttribute : 'WPI',
    beforeCreate: beforeCreateTestSegment
  }
  );
});

function beforeCreateTestSegment (resource, data, cb) {
  console.log('create Test_Segment')

  console.log(data);

  cb(null, data);
};
```

If I define an custom `idAttribute`, the beforeCreate hook is not fired. He is only fired without a custom  `idAttribute`.

**Comment by jmdobry** [comment]
Can you post the data you're passing to `Test_Segment.create(...)`?

**Comment by remicastaing** [comment]
Here it is:
```
{
   WPI: "AXAA00000432", 
   WOD: "2015-06-08", 
   WOE: "0001-01-01", 
   MCI: "G1", 
   MCV: "16 MO", 
   CTH: "8062.50", 
   CTY: "7581"
}
```

**Comment by jmdobry** [comment]
If you call `create` with data that already has a primary key, then `update` will be called instead. You can set the `upsert` option to `false` to force the `create` when the primary key is already present. In this instance, `beforeUpdate` and `afterUpdate` were being called, instead of `beforeCreate`.

**Comment by remicastaing** [comment]
Thanks for the explanation, @jmdobry!
