### ISSUE TITLE
Unsubscribing from an event listener in the case of no event listeners, shouldn't raise an error

### ISSUE THREAD

**Issue by jvanveen** [js-data/js-data#354]
> store.getMapper('collection').off('afterCreate')

 raises the following error:

```
Unhandled rejection TypeError: Cannot assign to read only property '_listeners' of object '#<Mapper>'
    at Mapper.<anonymous> (/home/jeroen/projects/high5/garage11/node_modules/js-data/dist/js-data.js:1508:21)
```

According to the docs, the following is expected:

> Remove an event listener from this Component. If no listener is provided, then all listeners for the specified event will be removed. If no event is specified then all listeners for all events will be removed.

**Comment by jmdobry** [comment]
Fixed in [47729b9](https://github.com/js-data/js-data/commit/47729b9eb6dda8bebf831493520d33b0ce2be927)

**Comment by jvanveen** [comment]
Awesome, thanks for the quick fix!

**Comment by jmdobry** [comment]
I'll cut a release in the next day or so.
