### ISSUE TITLE
Resource returns cached instance even though additional data was requested.

### ISSUE THREAD

**Issue by kakato10** [js-data/js-data#357]
If you call `find` with more relations for an instance that's already in the data store, the data store will return the cached instance directly, without the requested new relations.

Here's a plunker demonstrating the issue: https://plnkr.co/edit/az4sYI?p=preview

**Comment by jmdobry** [comment]
This is currently the intended behavior. If your record is _not_ in the store, then when you load it you can also eager load its relations via the `with` option.

If your record _is_ in the store, then you need to lazy load its relations via the `loadRelations` method. 

So in your plunker, switch that second `find` call to a `loadRelations` call, or pass `bypassCache: true`.

**Comment by kakato10** [comment]
Thanks for the quick response!

Right now I've worked around the problem exactly using `bypassCache`. Unfortunately, I am not sure that's a solution. Here are my thoughts on the things you've suggested.

First try: If I use `bypassCache` in the place I make most of my requests, I will be making a great number of requests. Note, I might already have that exact entity in the store.

Second try: If I start using `loadRelations` where `with` doesn't work, I have to consider lots of previous use cases, so that I can know, whether this entity is already in the store.

Third try: If I use `loadRelations` everywhere, I'll have to refactor all my code containing the 'with' option to 'find' and `loadRelations`. This will be easy, but doesn't that make the `with` option useless? And as far as, I know `loadRelations` doesn't  yet support the nested relations notation.

**Comment by jmdobry** [comment]
You've two options:

A) Use `find` + `bypassCache: true` + `with`
B) Use `loadRelations`

In the long run, I believe option A will be more efficient. Even though you may be re-loading an individual record again, it can retrieve multiple relations with a single request, whereas `loadRelations` issues a request _for each_ relation. Option A will use fewer requests overall, especially if your number of relations grows over time.

**Comment by kakato10** [comment]
Thanks for the advice!
