### ISSUE TITLE
findAll() on scoped store (store.as()) does not add the result to the store collection

### ISSUE THREAD

**Issue by christophercr** [js-data/js-data#358]
Hi,

On the latest beta version (**3.0.0-beta.7**), calling findAll on the scoped store is not the same as calling such method in the store itself (the results are not added to the LinkedCollection):

```
store.findAll("user");
store.getCollection("user").getAll();  // shows the results cached by the previous line
```

That works as expected, whereas this doesn't:

```
var UserStore = store.as("user");
UserStore.findAll();
store.getCollection("user").getAll();  // the collection is empty, it was not cached by the previous line
UserStore.getCollection().getAll();  // this is also empty
```

The only way in which the results are cached is with the store.findAll() method.

In case of the "scoped" store, since it is part of the store, it should also cache the results right? Or maybe I'm missing something...

**Comment by jmdobry** [comment]
You're right, this is a bug.

**Comment by jmdobry** [comment]
Fixed. I'll cut a release within a day or so.
