### ISSUE TITLE
Object duplication can occur when an object's relationship's are set before its ID

### ISSUE THREAD

**Issue by nvahalik** [js-data/js-data#362]
For reasons that I can't yet determine, there are times when a Record's relationship is being set before it's ID gets set. This can cause a duplicate record to be added to the relationship's Record collection.

The only time this occurs is when an a Records properties look like this: 

```
{
  someRelationshipId: "actualValue",
  id: "someValue"
}
```

versus looking like this: 

```
{
  id: "someValue",
  someRelationshipId: "actualValue"
}
```

**Comment by jmdobry** [comment]
Fixed by #363
