### ISSUE TITLE
Fix change event data to only include properties changed since last change event

### ISSUE THREAD

**Issue by jmdobry** [js-data/js-data#372]

**Comment by pik** [comment]
:+1: This would be great, especially if glueing js-data to view-frameworks.

**Comment by jmdobry** [comment]
You can also listen for changes on specific properties, e.g. `.on('change:email', ...)`

**Comment by pik** [comment]
@jmdobry Yeah I saw that in the code, my use case (or I guess the glue use-case) is more generic. For example if doing two-way binding with a polymer-element you need to make a `notifyPath()` call per attr change made outside of the polymer-event loop, so being able to generically listen to changes and dispatch to the correct path would probably be the cleanest.
