### ISSUE TITLE
DS.clear() extremely slow

### ISSUE THREAD

**Issue by Heedster** [js-data/js-data#373]
On logging out a user, I am issuing DS.clear() so that all data is cleared from the stores. But if there is more than, say 200kb of data, the operation is taking too long, and thus the whole screen just freezes for sometime (~1 min). 

Can someone look into this?

**Comment by riorulzz** [comment]
@jmdobry Can you please take a look at this issue ... ?

**Comment by jmdobry** [comment]
Are either of you using js-data-angular by chance?

**Comment by Heedster** [comment]
Yes. I am using js-data-angular

**Comment by jmdobry** [comment]
My primary recommendation would be to upgrade to js-data v3. v2 is in maintenance mode and I don't have a lot of time to work on v2. `DS#clear()` just calls `DS#ejectAll` on all the Resources, and each `ejectAll` calls `eject` for each record. A lot of stuff happens.

A more optimized store clearing method could be written, but like I said, I don't have a lot of time to work on it, so I can't guarantee it would get done soon.
