### ISSUE TITLE
How to access response headers?

### ISSUE THREAD

**Issue by demisx** [js-data/js-data#38]
The documentation for `DS#findAll` show this example: 

```js
User.findAll({
  age: {
    '>': 30
  }
}).then(function (users) {
  // users[0].age; 55 // etc., etc.
});
```

What's the correct way to get a hold of the response headers? Would be great if docs showed this as well.

**Comment by jmdobry** [comment]
You can access the response headers in the `deserialize` hook of the DSHttpAdapter.

```js
DSHttpAdapter.defaults.deserialize = function (resource, data) {
  // get the headers
  data.headers; // {...}
  return data ? ('data' in data ? data.data : data) : data;
};

**Comment by jmdobry** [comment]
Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, JSData, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [mailing list](https://groups.io/org/groupsio/jsdata).

**Comment by demisx** [comment]
Sorry Jason, but I am not following. Wouldn't it make sense to have the headers in the same  callback function as the data itself. Something like.:

```js
User.findAll({
  age: {
    '>': 30
  }
}).then(function (users, responseHeades) {
... ... ...
});
```

Could you please give me an example of how to access the response heades within the findAll .then block?

**Comment by jmdobry** [comment]
You cannot access the headers in the `.then` block. Promises can't have multiple arguments passed to the `.then` callback (according to the spec). The in-memory cache (data store) and the particulars of various persistence layers (adapters) have been abstracted apart, so you can't get the headers directly from `DS#findAll`, which requires data from the adapter to be in an injectable form (object or array of objects). If the raw response from an adapter is not in injectable form then that's where the `deserialize` hook comes in, and this is where you can access the header.

```js
// you're using angular right?
app.config(function (User, DSHttpAdapter) {
  DSHttpAdapter.defaults.deserialize = function (resource, data) {
    // "resource" a the resource definition returned by defineResource
    // "data" is the object returned by $http
    // so you have "data.data", "data.config", etc.


    // the default payload extraction code
    // return data ? ('data' in data ? data.data : data) : data;

    // do something different if your server response has a different format
    if (resource.name === 'user') {
      // maybe you have some meta data you want to save
      myOwnPlace.lastMeta = data.data.meta;

      // or you can save the meta data right on the items
      if (angular.isArray(data.data) {
        angular.forEach(data.data.user, function (item) {
          item.meta = data.data.meta;
        });
      } else {
        data.data.user.meta = data.data.meta;
      }

      return data.data.user;
    } else {
      return data.data;
    }
  };

  User.findAll().then(function (users) {
    users[0].meta === myOwnPlace.lastMeta; // true
  });
});
```

Support is handled via the [mailing list](https://groups.io/org/groupsio/jsdata).
