### ISSUE TITLE
hasOne relations incorrectly creates links (v3)

### ISSUE THREAD

**Issue by Pargus** [js-data/js-data#380]
Using the same set of data in v2 and v3, hasOne relations gets incorrectly linked in v3.

Example in v2 that works as expected:
https://plnkr.co/edit/xsD94inh6vAmlnAgJbHk?p=preview
Example in v3 that shows the bug:
https://plnkr.co/edit/yyZiif4e5aMxUHCQM6dB?p=preview

Refer to the console.log's at the end of script.js for test cases.

**Comment by jmdobry** [comment]
Fixed by #379
