### ISSUE TITLE
Confusing method names

### ISSUE THREAD

**Issue by SystemParadox** [js-data/js-data#389]
The methods available for getting data are as follows:

```
get(id)
getAll([ids])
filter([params])
find(id)
findAll([params])
```

I am finding some of these names a bit confusing:

1. `get` is equivalent to `find`, but `getAll` is not equivalent `findAll` - you have to use `filter` instead. Can we do something to match these up better? To be honest, I don't really see the point of `getAll([ids])`, and I notice there isn't an async version. Perhaps `getAll`/`findAll` could accept an object of params or an array of ids?
2. "find" implies searching rather than fetching remote data, so it's not really clear that this is the async version. "Find" just doesn't work in my head - I repeatedly keep trying to use "fetch", and then have to check the documentation to find the correct name. Is there any chance we can rename or alias this?

I would propose the following:

```
get(id)
getAll([params or ids])
fetch(id)
fetchAll([params or ids])
```

Any thoughts?

**Comment by jmdobry** [comment]
Here's one thought:

~~`const store = new DataStore()`~~

```js
import {DataStore, utils} from 'js-data'

class SystemParadoxStore extends DataStore {
  getAll(...args) {
    // I'm not sure this check is sufficient to correctly
    // decide whether getAll or filter should be used
    if (utils.isSorN(args[0])) {
      return super.getAll(...args)
    }
    return super.filter(...args)
  }
  fetch(...args) {
    return super.find(...args)
  }
  fetchAll(...args) {
    return super.findAll(...args)
  }
}

const store = new SystemParadoxStore()
```

I don't like making a single method do more than one thing ([Single Responsibility Principle](https://en.wikipedia.org/wiki/Single_responsibility_principle)), so I'm not going to combine `filter` and `getAll`, as they do different things.

I picked these method names by looking at various ORMs/database clients for precendent, and these are the names I happened to settle on.

Luckily with v3, it's trivial to extend, alias, transform, or customize the method names however you want.

**Comment by SystemParadox** [comment]
That looks useful. Thanks.
