### ISSUE TITLE
`Relation is defined but the resource is not` Error

### ISSUE THREAD

**Issue by demisx** [js-data/js-data#39]
I have these two resources defined in Angular:

```js
.factory('Classified', function(DS) {
  return DS.defineResource({
    name: 'classified',
    endpoint: '/classifieds',
    relations: {
      hasMany: {
        ad: {
          foreignKey: 'adId',
          localField: 'ad'
        }
      }
    }
  });
});

.factory('Ad', function(DS) {
  return resource = DS.defineResource({
    name: 'ad',
    endpoint: '/ads',
    relations: {
      belongsTo: {
        classified: {
          localKey: 'classifiedId',
          localField: 'classified'
        }
      }
    }
  });
```

Then when I try to resolve `Classified` in my top level state:

```js
.config(function($stateProvider) {
  $stateProvider
    .state('app.classified', {
      url: '/classifieds/:classifiedId',
      resolve: {
        classified: function($stateParams, Classified) {
          return Classified.find($stateParams.classifiedId);
        }
      },
     ... ... ...
```

it throws this error:

```
RuntimeError: classified relation is defined but the resource is not!
```

Does it mean that if I define a relation, I need to inject the related model factories upon first use?

**Comment by jmdobry** [comment]
Yes, it's a quirk of Angular's dependency injection. The DI system is lazy in that it waits to execute the setup code for the dependency until the dependency is actually needed. So if you don't actually inject Ad or Classified before that route resolve is executed, then those resources actually haven't yet been registered with the data store.

One way I get around it is the inject all my resources into the `.run` function of my angular app.

**Comment by kentcdodds** [comment]
@demisx, this is how all of my factories look:

```js
.factory('Classified', function(DS) {
  return DS.defineResource({
    name: 'classified',
    endpoint: '/classifieds',
    relations: {
      hasMany: {
        ad: {
          foreignKey: 'adId',
          localField: 'ad'
        }
      }
    }
  });
}).run(function(Classified) {}); // this line
```

That way the file that creates it also makes sure that it runs :-)

**Comment by demisx** [comment]
@kentcdodds Aha! I like that. Thank you Kent.

**Comment by techniq** [comment]
@kentcdodds Nice tip!

With `strictdi = true` and (ES6), I use `.run(['Classified', () => {}]`
