### ISSUE TITLE
Changes to nested attribute doesn't emit "DS.change" event nor update the Last Modified timestamp of the collection

### ISSUE THREAD

**Issue by tamakisquare** [js-data/js-data#397]
Here is a demo of how changes to non-nested attribute behaves, as expected.
[Demo (non-nested attribute version)](http://plnkr.co/edit/mmscwxEITDwNHGnHevCL?p=preview)
This demo shows a team roster, which is divided into two lists - Starting and Bench. It offers functionality to move players between the lists and, as well as, to recruit new player (ie. add new player to bench). The two lists are implemented using _js-data-angular's_ `bindAll` to filter Player instances based on _status_ ("S" or "B") and to monitor changes to the attribute. The move between lists is simply a result of changing the attribute. 

All is good until I change a tiny bit of the demo - turn _status_ into a nested attribute. Change to the _status_ attribute (nested) does no longer emit "DS.change" event on the Player collection (used to automatically update Last Modified in the view) nor update the Player collection's _LastModified_ value. Here is the [Demo (nested attribute version)](http://plnkr.co/edit/wh7f9yxdZ1CsdVUnv0rr?p=preview)

Try clicking on "Move to Bench" and/or "Move to Starting" buttons to see no changes to the view. Next, try clicking on "Recruit New Player" button, you should see the view gets updated with not only adding a new player to the bench but all the previous clicks on "Move to Bench" and "Move to Starting" buttons are now reflected as well. 

I have no idea what's going on. At first, I thought there was some problem with digesting the changes, so I tried `Player.digest()` but nothing changed.

Can someone explain to me why changes to nested attribute behaves so differently from changes to non-nested attribute? Is this by design or an issue? How can I make it to behave the same as its non-nested counterpart? Thanks.

**Comment by jmdobry** [comment]
I don't know why `player.status = 'B';` works while `player.condition.status = 'B';` does not. By all accounts, they both should work. Unfortunately, JSData 2.x relies on `observe-js` (and `Object.observe`) for change detection, both of which are now deprecated and have been removed in JSData 3.x in favor of a new change detection system.

However, you might be happy to hear not all hope is lost. While `player.condition.status = 'B';` does not work, `player.set('condition.status', 'B');` _does_ work, correctly triggering the change detection. I hope that's sufficient for now.

**Comment by tamakisquare** [comment]
@jmdobry 

Thanks for the pointer. For my use case, using `set()` is sufficient. Just curious though, do you think this is something fixable at the js-data level?

I'll leave this issue to you to decide whether to close or not. Thanks once again.

**Comment by jmdobry** [comment]
I _could_ monkey patch the observe-js polyfill that's inside JSData 2.x, but it would significantly slow down its dirty-checking, and change its behavior away from how the original polyfill worked. This would be a breaking change, and 2.x won't get anymore breaking changes.

You'll have to use `set()`.
