### ISSUE TITLE
Adapters

### ISSUE THREAD

**Issue by jmdobry** [js-data/js-data#4]
- [x] - http
- [x] - localStorage
- [x] - localforage
- [x] - firebase
- [x] - mysql
- [x] - mariadb
- [x] - mongo
- [x] - postgres
- [x] - nedb
- [x] - sqlite3
- [x] - rethinkdb
- [x] - redis

**Comment by derekperkins** [comment]
What would be the recommended solution for integrating a Websocket platform like PubNub or Pusher? Would they need their own adapter? @tannerlinsley

**Comment by derekperkins** [comment]
I just saw #44, which appears to handle the use case just fine. Would there still be a benefit to having an adapter ala Firebase?

**Comment by jmdobry** [comment]
No. I don't see how websockets fit with the request/response format of the other adapters.

**Comment by alexzaporozhets** [comment]
@jmdobry how we can implement 3-way data binding? 
 - mongodb + nodejs backend (1+ servers)
 - multiple angularjs clients

**Comment by jmdobry** [comment]
With something like this:

```js
var socket = io.connect(app.url, { path: '/api/socket.io' });

  socket.on('create', function (data) {
    if (data.ownerId && $rootScope.loggedInUser && $rootScope.loggedInUser.id === data.ownerId) {
      DS.find(data.resource, data.id);
    }
    $rootScope.$broadcast('create', data.resource, data.id, data.ownerId);
  });
  socket.on('update', function (data) {
    if (data.id === 'all' && data.seriesId) {
      angular.forEach(DS.filter(data.resource, { seriesId: data.seriesId }), function (instance) {
        DS.refresh(data.resource, instance.id);
      });
    } else {
      DS.refresh(data.resource, data.id);
    }
    $rootScope.$broadcast('update', data.resource, data.id, data.ownerId);
  });
  socket.on('destroy', function (data) {
    if (data.id === 'all' && data.lessonId) {
      DS.ejectAll(data.resource, { lessonId: data.lessonId });
    } else {
      DS.eject(data.resource, data.id);
    }
    $rootScope.$broadcast('destroy', data.resource, data.id, data.ownerId);
  });
```

**Comment by alexzaporozhets** [comment]
@jmdobry thanks alot for the fast reply and I have few more question: 
  - where I can get the service side code (js-data + socket.io integration)?
  - how I should do the same for nodejs workers?

**Comment by jmdobry** [comment]
> where I can get the service side code (js-data + socket.io integration)?

I'm not sure what you mean. I don't have anything for you beyond that example.

> how I should do the same for nodejs workers?

Example code in Node:

lib/messageService.js

```js
// ...

function sendMessage(event, resource, instance) {
  // where io is "var io = require('socket.io').listen(server);" in app.js
  var io = container.get('io');
  var message = {
    id: instance.id,
    ownerId: instance.ownerId,
    resource: resource,
    event: event
  };
  if (instance.parentType) {
    message.parentType = instance.parentType;
  }
  if (instance.parentId) {
    message.parentId = instance.parentId;
  }
  if (instance.lessonId) {
    message.lessonId = instance.lessonId;
  }
  io.sockets.emit(event, message);
}

module.exports = {
  sendCreateMessage: function (resource, instance) {
    sendMessage('create', resource, instance);
  },

  sendDestroyMessage: function (resource, instance) {
    sendMessage('destroy', resource, instance);
  },

  sendUpdateMessage: function (resource, instance) {
    sendMessage('update', resource, instance);
  }
};  
```

Use with a resource:

```js
var Series = DS.defineResource({
    name: 'series',
    table: 'series',

    // ...

    afterCreate: function (Series, series, cb) {
      // ...

      // Broadcast that this series was created
      messageService.sendCreateMessage('series', series);

      // ...
    },

    afterUpdate: function (Series, series, cb) {
      // ...

      // Broadcast that this series was updated
      messageService.sendUpdateMessage('series', series);

      // ...
    },

    afterDestroy: function (Series, series) {
      // ...

      // Broadcast that this series was destroyed
      messageService.sendDestroyMessage('series', series);

      // ...
    }
  });
```

**Comment by catogonzalez** [comment]
[js-data/js-data-angular#147](https://github.com/js-data/js-data-angular/issues/147) is exactly what I am looking for: being able to use js-data with an adapter for Cordova SQLitePlugin so that I can use js-data-angular + js-data-sql in an hybrid mobile app. However, the docs say the [js-data-sql adapter is not supported in browsers](http://www.js-data.io/v1.8.0/docs/working-with-adapters).

Is there a way to use js-data-sql adapter in an hybrid mobile app (angularjs client)?

**Comment by jmdobry** [comment]
Actually, I can't remember who it was or where it was, but somebody told me that they were using the js-data-sql adapter in the browser, which I didn't think would work, but apparently was working for this person.

**Comment by catogonzalez** [comment]
Thanks for your reply @jmdobry. If you don't think it would work, then can you give me some directions on how would you implement/patch it to work? If it ends up being a whole project I might have to look for other solution due to a time constraint.

**Comment by jmdobry** [comment]
I don't actually have evidence that it doesn't work in the browser, I just never tried it. I think this person who was using js-data-sql in the browser to connect to sqlite for cordova. I'll see if I can find where they mentioned it. I can't actually think of any reason why it wouldn't work.

**Comment by catogonzalez** [comment]
Well, I tried to load js-data-sql in my project and it fails with this:
```
0     750666   error    Uncaught ReferenceError: module is not defined, http://localhost:8100/lib/js-data/js-data-sql.js, Line: 1
1     750791   error    Uncaught Error: [$injector:modulerr] Failed to instantiate module transale due to:
Error: [$injector:unpr] Unknown provider: DSSqlAdapterProvider
```
js-data-sql.js, Line: 1 has ```module.exports =...``` and there is the 'module' not defined. I don't know anything about Node.js programming but I guess that's a Node specificity that I would need to change to get this adapter to work in the borwser?

**Comment by jmdobry** [comment]
You're going to have to have a build step that uses webpack or browserify to package your code for the browser.
