### ISSUE TITLE
Make schemas consistent between modeling-your-data and js-data-examples

### ISSUE THREAD

**Issue by jredd** [js-data/js-data#401]
http://www.js-data.io/v3.0/docs/modeling-your-data

In the documentation, which is great btw, it show's the creation of schemas that implies the creation in a separate document. Then you import it 

`import * as schemas from '../shared/schemas';
`

I know this comes from your examples app since I've spent a decent amount of  time perusing the different repo's. The issue is that the schemas from the examples app repo are completely differently than the schemas in the documentation example. If someone doesn't know of the examples repo they won't understand this and thus fail at following along with the example. I had to go to the example schemas to find out the difference between what the documentation schema has and what the examples schemas has. It's probably confusing for people that are brand new to this.

**Comment by jmdobry** [comment]
Yes, they should be consistent and the docs should clarify the shared schemas file. This will take me a little longer to fix.

In the meantime, if you have any immediate suggested changes for either the `js-data-examples` repo or the docs, I'm happy to review PRs or suggested doc edits (there's a "Suggest Edits" in the top right corner of the docs).

**Comment by jredd** [comment]
No biggie I wasn't sure if you were aware and just wanted to point it out.

**Comment by crobinson42** [comment]
fixed in js-data-examples
