### ISSUE TITLE
Missing "beforeSave" lifecycle hook / "onSave" event

### ISSUE THREAD

**Issue by thelamborghinistory** [js-data/js-data#403]
I am missing a lifecycle hook here that gets called on resource creation as well as on updating: http://www.js-data.io/docs/model-lifecycle

**Comment by jmdobry** [comment]
Sorry for not responding to this earlier. What version of JSData are you using?

In 2.x and 3.x, there are just the beforeCreate/beforeUpdate and afterCreate/afterUpdate hooks. The reason there aren't before/after save hooks are that the save method of record instances is actually delegating to the create/update method of the Resource/Mapper. Save() is really just a sugar method that calls create or update.
