### ISSUE TITLE
Custom Pk field?

### ISSUE THREAD

**Issue by jredd** [js-data/js-data#404]
I have a model that comes in and doesn't have an id field. It's pk is another field all together. I have no control over how the model in the backend is defined and so I have to receive it as is. Is there way to tell the schema that another field is the pk field so I can do things like store.find('someModel', 'uniqueIdentifier') instead of having to do query filters?

**Comment by jmdobry** [comment]
`idAttribute: 'myPkField'`

**Comment by jredd** [comment]
Thanks! I actually just found it as I noticed you posted. Wouldn't it be better to define pk's in the schema? You'd be able to keep the definition of the schema contained instead of split apart. It took some digging for me to find this because I was making the wrong assumption about where that would be defined at. Though I can also see the value of defining it on the mapper as well.

**Comment by jmdobry** [comment]
JSData's schemas don't really care which field is the primary key, as the schemas are primarily concerned with validation. You can technically use JSData without defining any schemas.
