### ISSUE TITLE
What is the difference between create(), createInstance() and inject()

### ISSUE THREAD

**Issue by Offirmo** [js-data/js-data#408]
Some examples use `createInstance()`, other use `create()`. I've also seen an `inject()`

What is the difference between all those primitives ?

Could it be explained in the doc ?

**Comment by jmdobry** [comment]
* [`createInstance`](http://www.js-data.io/docs/dscreateinstance) - Instantiate an in-memory, unsaved record
* [`inject`](http://www.js-data.io/docs/dsinject) - Insert a record (an already saved record) into the in-memory datastore
* [`create`](http://www.js-data.io/docs/dscreate) - Insert a new record into the database, post a new record to the REST api, etc. This method is asynchronous, as it's making an RPC call.

**Comment by Offirmo** [comment]
Thanks !

**Comment by Offirmo** [comment]
You mention an "in-memory datastore". However, when a create a store and call  `create()`, I get rejected. Is using an adapter mandatory ? Isn't there a memory datastore ?

**Comment by jmdobry** [comment]
All of the asynchronous methods require that you have an adapter registered, as they all delegate to the adapter.

**Comment by Offirmo** [comment]
Thanks !
