### ISSUE TITLE
FindAll not respecting cacheResponse on new instance

### ISSUE THREAD

**Issue by jasonbodily** [js-data/js-data#410]
I'm working on v2.10.0 and the following is happening: 

```
// There are 10 works in the Work Resource
Work.findAll(); // returns 10

// Create work resource, cacheResponse
return this.work.DSCreate({ cacheResponse: true }).then(work => {
    this.Work.findAll(); // Returns 10 objects

    // Inject
    this.Work.inject(work);

    this.Work.findAll(); // Returns 10 objects

});
```

Is 'findAll' intended to ignore { cacheResponse: true} for newly created resources? Is it intended to ignore injected resources as well? I'd like for the newly created resource to show immediately in a list that is bound to the 'findAll' response. 

I recognize that getAll returns all the instances, but I'm intentionally using findAll and don't want to have to bypass the cache to reload everything when I know only one resource is new and can be injected. Is this possible?

Cheers, J

**Comment by jmdobry** [comment]
Try setting `useFilter` to `true`. http://www.js-data.io/docs/dsdefaults#usefilter

More details here: http://www.js-data.io/docs/dsfindall
