### ISSUE TITLE
DNS for js-data.io not working on Linux ?

### ISSUE THREAD

**Issue by pelletiermaxime** [js-data/js-data#413]
A bit of a weird one. It seems js-data.io is working fine on MacOS, but not on Linux:

"www.js-data.io’s server DNS address could not be found."

**Comment by jmdobry** [comment]
I just tried it on linux, it seems to be working fine ¯\_(ツ)_/¯

**Comment by pelletiermaxime** [comment]
It worked for an hour and now it's down again. The DNS server seems that have problems :S

**Comment by jmdobry** [comment]
Hopefully Readme.io doesn't have any more availability issues.
