### ISSUE TITLE
Shallow copy of model for editing

### ISSUE THREAD

**Issue by scott-taj** [js-data/js-data#414]
I'm working with `js-data@3.0.0-rc.4` and Angular 1. I needed to make a shallow copy of a model for editing. This is what I did to make it work: 

``` js
this.modelCopy = Object.assign(Object.create(Object.getPrototypeOf(model)), model);
var props = Object.getOwnPropertyDescriptors(model);

// Transfer non-enumerable js-data properties (_get, _set, _unset);
Object.keys(props)
  .filter(propName => !props[propName].enumerable)
  .forEach(propName => Object.defineProperty(this.modelCopy, propName, props[propName]));
```

Is there a better way to approach this?

**Comment by jmdobry** [comment]
Do you just need the properties? Or do you also need the `Record` functionality?

You could just do:

```js
const modelCopy = store.createRecord('mymodel', model.toJSON());
```

**Comment by scott-taj** [comment]
I also need the Record functionality.

**Comment by jmdobry** [comment]
What I posted ought to still give you the Record functionality.
