### ISSUE TITLE
Tracked properties sometimes throw error when updated

### ISSUE THREAD

**Issue by JaySunSyn** [js-data/js-data#416]
Thanks for your work!

js-data.js:6623 Uncaught (in promise) TypeError: Cannot read property 'indexOf' of undefined

![image](https://cloud.githubusercontent.com/assets/5872432/19804225/5e7e4b22-9d0d-11e6-94d2-81cadc776c38.png)

`version: 3.0.0-rc.5`

```
changed:undefined
changing:true
current:"http://localhost:8000/media/images/blabla/8679ae5a-4f7.jpg"
index:undefined
previous: undefined
this: undefined
```

**Comment by jmdobry** [comment]
Somehow I missed this issue. I have never seen this error, could you possible create a JSFiddle or Plunker with which I can reproduce the issue?

**Comment by rquast** [comment]
I am getting this one too (rc4).. updating to rc9 to see if it is still happening.

Don't know how to reproduce since it randomly happens.

**Comment by rquast** [comment]
I removed change tracking and I no longer get this issue.

**Comment by BennyAlex** [comment]
@jmdobry 
Hello, I get the error in my application, too. track changes is activated. It happens every time when I call record.save() in specific methode. 

> Uncaught (in promise) TypeError: Cannot read property 'indexOf' of undefined
    at Record.descriptor.set [as id] (js-data.js?2812:7181)
    at Object.deepMixIn (js-data.js?2812:521)
    at postProcess (js-data.js?2812:4395)
    at <anonymous>
descriptor.set @ js-data.js?2812:7181
deepMixIn @ js-data.js?2812:521
postProcess @ js-data.js?2812:4395
Promise rejected (async)
_callee4$ @ NewHolidays.vue?8bbd:224
tryCatch @ runtime.js?4a57:65
invoke @ runtime.js?4a57:299
prototype.(anonymous function) @ runtime.js?4a57:117
tryCatch @ runtime.js?4a57:65
maybeInvokeDelegate @ runtime.js?4a57:361
invoke @ runtime.js?4a57:273
prototype.(anonymous function) @ runtime.js?4a57:117
step @ asyncToGenerator.js?7b11:17
(anonymous) @ asyncToGenerator.js?7b11:28
Promise resolved (async)
step @ asyncToGenerator.js?7b11:27
(anonymous) @ asyncToGenerator.js?7b11:28
Promise resolved (async)
step @ asyncToGenerator.js?7b11:27
(anonymous) @ asyncToGenerator.js?7b11:28
Promise resolved (async)
step @ asyncToGenerator.js?7b11:27
(anonymous) @ asyncToGenerator.js?7b11:35
F @ _export.js?90cd:35
(anonymous) @ asyncToGenerator.js?7b11:14
saveAbsentDays @ NewHolidays.vue?8bbd:227
boundFn @ vue.runtime.esm.js?ff9b:188
invoker @ vue.runtime.esm.js?ff9b:1982
Vue.$emit @ vue.runtime.esm.js?ff9b:2492
click @ vuetify.js?dc48:6260
boundFn @ vue.runtime.esm.js?ff9b:188
invoker @ vue.runtime.esm.js?ff9b:1982
fn._withTask.fn._withTask @ vue.runtime.esm.js?ff9b:1780

**Comment by jmdobry** [comment]
@BennyAlex Could you create a plunker or stackblitz or jsfiddle or something with code that reproduces the error?

**Comment by phortx** [comment]
I'm having this issue too. Seems like it happens when there are properties in a newly created model which are `undefined` (having no default value and don't have been set between creation and saving) and then new values come from the server.

When you make sure you have default values for every property you don't set after creation, everything works.

I think this is a bug. js-data should allow to have empty properties when saving a new model.
