### ISSUE TITLE
Wrong association when referencing to the same model

### ISSUE THREAD

**Issue by m3l7** [js-data/js-data#419]
I'm using this model schema:

    this.model = models.store.defineMapper("user", {
      endpoint: "user",
      schema: userSchema,
      relations: {
        belongsTo: {
          user: {
            foreignKey: "distributorId",
            localField: "Distributor"
          }
        },
        hasMany: {
          user: {
             foreignKey: "distributorId",
             localField: "customers"
          }
        }
      }

when I try to find a user:

      store.find("user", 2).then( (user) => { }

Distributor is populated (with an apparently random user instance from the store) even if distributorId is null.

I'm using js data v3

**Comment by m3l7** [comment]
it seems that this problem happens for other belongsTo relations.
the problem is not in find method itself, rather in .add method.

I can solve by doing something like:

      user.find(1).then((user) => {
         store.add("user", user.toJSON());
      })

**Comment by m3l7** [comment]
I have investigated a little more.
The store associates wrong items when the foreignKey is null rather than undefined.
Adding something like:

      if (!record.distributorId) delete record.distributorId

in the deserialization hook solves completely the issue;

**Comment by m3l7** [comment]
I was using an old version of js data. rc5 doesn't have this problem.
Closing

**Comment by jmdobry** [comment]
Glad to see this was fixed already!
