### ISSUE TITLE
deserialize and beforeInject are called from the parent relation when loadRelations is used

### ISSUE THREAD

**Issue by mattlewis92** [js-data/js-data#42]
If I call loadRelations on a parent model, when the child relations are loaded the deserialize and beforeInject (possibly other methods as well) of the parent model are called on the child relations instead of the deserialize and beforeInject methods that are in the child model. Let me know if you need any more info to reproduce.

**Comment by jmdobry** [comment]
I think I know what you're talking about, I'll take a look.

**Comment by mattlewis92** [comment]
The issue seems to be on this line https://github.com/js-data/js-data/blob/master/src/datastore/async_methods/loadRelations.js#L25

This options object which is the resource of the parent is passed to the find methods of the child relations, instead it should be set when looping through the child relations. I tried to fix it but it broke loads of tests.
