### ISSUE TITLE
find Query using findAll result even with usePending: false [v3]

### ISSUE THREAD

**Issue by m3l7** [js-data/js-data#420]
I'm using something like this:

      store.findAll("model", {}).then()
      store.find("model", id, {usePendingFind: false, usePendingFindAll: false}).then()

the second request returns the result of the findAll. If I use functions for the usePending options, they are never called.

**Comment by jmdobry** [comment]
Can you please create a Plunkr or JSFiddle that I can use to reproduce the issue?

**Comment by jmdobry** [comment]
Any update on this?
