### ISSUE TITLE
events emitted multiple time per resources [V3]

### ISSUE THREAD

**Issue by Goopil** [js-data/js-data#422]
Hello, 

I'm actually making a plugin to use js data in vue. 
I've succesfully mapped collections and the contexted store (store.as('modelName')) to use it in components.

i didn't find the location of the actual data in collection. so to trig the ui change.
I'm catching the store events but at my big surprise, these events (add, change, remove, afterFind, etc) are emited several time per resource.

Is this a normal behavior ?

I will provide a feedle when i have time (thanks the end of the year for your supplementary workload)

but in the mean time could you confirm that this behavior is correct ? 
stuff used:
*  js-data@3.0.0-rc.6
* js-data-http@3.0.0-rc.2

thanks in advance and above all thank you for your great work !

best regards Goopil

**Comment by jmdobry** [comment]
Can you elaborate on "several times per resource"? Each emitted event can be tied back to an action taken by you that triggers the event. A Plunkr/Fiddle using the Vue plugin would be very helpful in understanding your question.

**Comment by jmdobry** [comment]
Any updates on this?

**Comment by Goopil** [comment]
Not really. I didn't encounter the problem with rc7. So it seems you have solved it already. I will comm again if i find somethings.
