### ISSUE TITLE
Example model schema with more formats like date, datetime, currency.

### ISSUE THREAD

**Issue by SukantGujar** [js-data/js-data#423]
Hi,

While going through the documentation on schemas, I missed examples for more diverse models, e.g. ones containing datetime, currencies etc. Please correct me if I got it wrong... as the schema is JSON Schema based, the idea is to follow the documentation on that. But for the sake of completeness of an already excellent documentation, can I request you to add some examples covering these types as well?

Thanks

**Comment by crobinson42** [comment]
http://www.js-data.io/docs/validation
