### ISSUE TITLE
resource.filter for substring

### ISSUE THREAD

**Issue by stephen-murby** [js-data/js-data#43]
[angular-data](https://github.com/js-data/js-data-angular/issues/295) copy issue. Added here as requested.

DEFAULT_RECORDS = [{ id: 1, name: 'John Evans', number: '01928 356115' },{ id: 16, name: 'Murbinator', number: '053180 080000' }];

```js
lookup: function (name) {
            var retrievedRecords = {};
            var _this = this;
            Record.findAll().then(function () {
                var params = {
                    where: {
                        name: {
                            'in': name
                        }
                    }
                };
                retrievedRecords = Record.filter(params);
                debugger;
                _this.lookupSuccess(retrievedRecords);
            }).catch(function (error) {
                console.log(error);
            });
        },
```

Where 'in': name name is "John" no record is found
Where 'in': name name is "John Evans" one record is found.
Looking at issue 238 that appears to be the way I should be filtering but is not the value I expect to be return for sub-string filtering.

angular-data : 1.5.3
angular : 1.3.8

**Comment by jmdobry** [comment]
In 1.1.0 you can now do:

```js
DS.filter('user', {
  where: {
    name: {
      contains: 'John'
    }
  }
});
```
which looks for items that have a name that contains "John", as opposed to:

```js
DS.filter('user', {
  where: {
    name: {
      'in': 'John'
    }
  }
});
```
which looks for items whose name is contained in "John".
