### ISSUE TITLE
Calling a custom method

### ISSUE THREAD

**Issue by Jufik** [js-data/js-data#431]
In a restfull api, we could expect such a pattern:

`/dogs/{:identifier}/{:some_action}`

Let says I need to make the dog Bark :-)

How to implement such a pattern using js-data? 
_eg_ Creating a bark function, available just like any other  Custom Instance Behavior?

**Comment by jmdobry** [comment]
Checkout Actions:

* [Actions in JSData v2.x](http://www.js-data.io/v2.9/docs/dsdefaults#actions)
* [Actions in JSData v3.x](http://www.js-data.io/v3.0/docs/js-data-http#http-actions)

**Comment by jmdobry** [comment]
Closing if no other questions.
