### ISSUE TITLE
Query params are passed to relation-loading request

### ISSUE THREAD

**Issue by altschuler** [js-data/js-data#434]
Posting my [SO question](http://stackoverflow.com/questions/41243318/jsdata-load-relations-without-opts) here as well as it's not getting much attention and I don't know how to tap into js-data to fix it (given it's not configurable).

The issues is that eagerly loading relations using `{ with: ['something'] }` the query parameters are forwarded to the relation request as well. Is there some configuration or hook that can be used to control if/what query params are forwarded?

I don't think the `queryTransform` hook on `Adapter` is going to help because from there I can't know whether it's a relation being loaded or a "direct" request.

I'm using v3.

**Comment by jmdobry** [comment]
Answered: http://stackoverflow.com/a/41926444/1153216
