### ISSUE TITLE
v3: Subsequent calls to findAll() failing when 'with' is supplied

### ISSUE THREAD

**Issue by olsgreen** [js-data/js-data#439]
Not sure whether this is a bug or whether I'm not doing something correctly.

I have a few mappers (contact & user) and the HTTP adapter backing the store, all with a fairly standard configuration. If I call `store.findAll('contacts', {with: ['user']})` once I get a few records back as expected, if I then call it again I get an empty recordset back. This only occurs while feeding the `with` parameter to my api. Have I missed something? Something todo with the caching?

I've setup a demo here: http://boxedcode.co.uk/js-data/index.html

Mappers:

    store.defineMapper('user', {
        relations: {
        hasMany: {
            contacts: {
                foreignKey: 'user_id',
                localField: 'contacts'
            }
        }
    }
    });

    store.defineMapper('contacts', {
      schema: {    
        type: 'object', // required
        properties: {
          name: { type: 'string' },
        },
      },
      relations: {
        belongsTo: {
            user: {
                foreignKey: 'user_id',
                localField: 'user'
            }
        }
      }
    });

Call:

    store.findAll('contacts', { 
        with: ['user'],
        orderBy: [['title', 'DESC']],
        offset: 0,
        limit: 10
    }).then((contacts) => {
        console.log(contacts);
    });

**Comment by jmdobry** [comment]
All of your code looks correct. However, your demo is using old versions of JSData v3. Can you update to js-data 3.0.0-rc.7 and js-data-http 3.0.0-rc.2 and see if the issue persists?

**Comment by olsgreen** [comment]
It does, I originally down graded to see whether the issue persisted, I've bumped it back up to the latest versions.

**Comment by jmdobry** [comment]
I see you upgraded `js-data-http` to `3.0.0-rc.2`, but can you also upgrade `js-data` to `3.0.0-rc.7`? (It's at `3.0.0-beta.2`).

I took another look at your code and realized the problem. `with` is not part of the JSData query syntax, rather it's an _option_ of the `findAll` method, so you'll need to change your code to match one of the following:

### Option 1 - Multiple requests

This requires that your server understands the "where" querystring parameter:

```js
const query = { 
  orderBy: [['title', 'DESC']],
  offset: 0,
  limit: 10
};
const options = {
  with: ['user']
};

store.findAll('contacts', query, options).then(...)
```

Here's a plunker that demonstrates: https://plnkr.co/edit/UCFJNg?p=preview

The plunker example makes two requests:

* `GET /stories?title=foobar`
* `GET /users?title=foobar&where={"_id":{"in":[123,234]}}`

In your case it would be:

* `GET /contacts?orderBy[]=[%22title%22,%22DESC%22]&offset=0&limit=10`
* `GET /users?where={"id":{"in":[1]}}`

### Option 2 - A single request

This requires that your server understands the "with" querystring parameter,
but you can't put `with` in the `query` argument passed to `findAll`, you must
give the `with` property directly to the HTTP adapter:

```js
const query = { 
  orderBy: [['title', 'DESC']],
  offset: 0,
  limit: 10
};
const options = {
  // This will be passed through to the HTTP adapter
  params: {
    with: ['user']
  }
};

store.findAll('contacts', query, options).then(...)
```

Here's a plunker that demonstrates: https://plnkr.co/edit/M6quP4?p=preview

The plunker example makes just one request, and expects the users to be embedded within the stories in the server's response:

* `GET /stories?with=user&title=foobar`

In your case it would be:

* `GET /contacts?with[]=user&orderBy[]=[%22title%22,%22DESC%22]&offset=0&limit=10`

### Note

This is a quirk of the HTTP adapter. For all other adapters, using the `with` option works as you'd expect, and you don't have to mess with the `params` option.

Also note that regardless of which versions you're using, the appropriate strategy is to use `find`/`findAll` to load data into the store, and then to use `get`/`getAll`/`filter` to select items out of the store when you need them.

Let me know if you need more clarification.
