### ISSUE TITLE
Validation failed for date type.  (RethinkDB specific data types)

### ISSUE THREAD

**Issue by telvin** [js-data/js-data#440]
I'm using js-data with RethinkDB driver, I find on the doc, js-data only supports the [basic data types](https://rethinkdb.com/docs/data-types/). 

My schema:
```
apps: new Schema({
        type: 'object',
        properties: {
            [other properties ...],
            created_on: {type: 'date'} // this will cause error
        }
    }),
```

If I use a RethinkDB specific data types like `date`, the js-data will throw exception
"types[_type] undefined". Even setting type to 'object', another error would be "validation failed" 

The date type of the field `created_on` will make the its value to be translated automatically by RethinkDB from following value
`Tue Feb 07 2017 20:38:47 GMT+07:00`

to

`{"epoch_time": 1486474727, "$reql_type$": "TIME", "timezone": "+07:00"}`

My quick fix is adding more date type into `Schema.js` file and rebuild the source. I have ran the tests and they are fine. I'm not sure whether this is the right way to go or not

```
const types = {
  array: utils.isArray,
  boolean: utils.isBoolean,
  integer: utils.isInteger,
  'null': utils.isNull,
  number: utils.isNumber,
  object: utils.isObject,
  string: utils.isString,
  date: utils.isDate // <== here
}
```

**Comment by jmdobry** [comment]
You don't need to rebuild from source, as that `types` object is exposed as a static property on the `Schema` class. Just do:

```js
import { Schema, utils } from 'js-data';

Schema.types.date = utils.date;
```
