### ISSUE TITLE
Audit v3 TypeScript definitions

### ISSUE THREAD

**Issue by jmdobry** [js-data/js-data#444]
There might be some instances where `dist/js-data.d.ts` is out of date, it would be great if somebody could audit the definitions for accuracy.

**Comment by jmdobry** [comment]
Perhaps related to #444

**Comment by kvandelden** [comment]
Mapper.afterUpdate is out of sync.  
![image](https://cloud.githubusercontent.com/assets/17126950/24183439/573599d8-0e96-11e7-9237-c9e8692aee57.png)

It looks like the after hook is missing props between id & opts

![image](https://cloud.githubusercontent.com/assets/17126950/24183467/8cd38302-0e96-11e7-8e94-2dd3b434a6e4.png)

**Comment by kvandelden** [comment]
Container class missing getMapperByName in typings...
![image](https://cloud.githubusercontent.com/assets/17126950/24482694/efea9494-14b8-11e7-86f1-a049dcec8e32.png)
