### ISSUE TITLE
findAll stop working after multiple calls

### ISSUE THREAD

**Issue by khamaileon** [js-data/js-data#450]
My code:
```js
console.log('before calling findAll');
return this.dataStore.findAll('place', { query, language },
  { force: true, suffix: 'autocomplete/' });
```
js-data-http/dist/js-data-http.js
```js
findAll: function findAll(mapper, query, opts) {
  console.log('call findAll');
  var _this8 = this;
```

After multiple requests, findAll stops being called despite "before calling findAll" appears in the console.

I'm using js-data 3.0.0-rc.8 and js-data-http 3.0.0-rc.2 on an ionic 2.1 project.

**Comment by jmdobry** [comment]
> After multiple requests

How many requests? How much time between requests? What are the values of `query` and `language`? What data does your server respond with?

Can you provide a plunker that demonstrates the issue you're seeing? I cannot reproduce with what you've shown here. Also, just yesterday I finished the detailed guide explaining how DataStore caching works: http://www.js-data.io/v3.0/docs/working-with-the-datastore#section-caching-queries

**Comment by khamaileon** [comment]
> How many requests?

I don't know exactly. I was playing with the UI.
> How much time between requests?

Less than 1 second.
> What are the values of query and language?

2 strings: I was switching alternately between "Paris" + "fr" and "Parim" + "fr"

What data does your server respond with?

Simple JSON data.

I'm now unable to reproduce it. I was on my phone in 4g. Maybe it has to do with my cell phone carrier.

I'm closing it for now and I will take a close look at the caching guide. Thanks @jmdobry
