### ISSUE TITLE
[questions] Is there any way to chunk the insertion of fetched resource ?

### ISSUE THREAD

**Issue by Goopil** [js-data/js-data#452]
In the case of fetching really large collection,  you will run in a ui freeze until the result are handled (tested with a 10000 row call).
i know this is not a really a js-data issue but  more of a  language  ~~bug~~ feature.
The solution i came up to counter this. Is to split the response in sized chunk and inject them over time to make it behave more like a stream insertion than a block.

Do you have some leads to where i could hook this feature ?

**Comment by jmdobry** [comment]
How are you currently inserting the data now?

**Comment by Goopil** [comment]
i'm not talking about row insertion like create() or createMany(), but more for List display with a findAll() on really large collections. 

for now, i've made some stress test with axios alone. To see how it would handle processing big queries. And this is fine. But when you insert it in a memory store (yours or any others, it's all the same)
It will result in a huge overhead to process the massive collection and by extension ,a freeze ui will fallow. has it follow the referenced store to update the dom (i'm working with vuejs there, but as far has i understand js framework it should be the same result with other frameworks) 

So if i can catch the request and split a 10000 rows collection in chunk of 1000 then insert the chunks in the memory store over time, this ease the load, and let me do other things on the ui even if i process a large collection.

**Comment by jmdobry** [comment]
You can certainly do what you suggest, just call `Mapper#findAll()` (e.g. `store.getMapper('comment').findAll(...)`) and insert chunks of the result into the store over time.
