### ISSUE TITLE
store.updateAll override all the props

### ISSUE THREAD

**Issue by Goopil** [js-data/js-data#453]
Hello, 
I've found some strange behavior.
when using updateAll on a collection to update say 1 prop,
all the props seems to be modified.
and that's not all. 
the other properties are set to undefined if specified in the resource schema 
Or not present at all in the record if not specified in the schema.

you can see it [there](https://plnkr.co/edit/V8DD59HS271raFGBaSgk)

**Comment by jmdobry** [comment]
Change from:

```js
store.defineMapper('Post', {
  schema: {
    properties: {
      'text_in_schema': 'string'
    }
  }
})
```

to

```js
store.defineMapper('Post', {
  schema: {
    properties: {
      'id': { type: 'string' },
      'user_id': { type: 'number' },
      'text_in_schema': { type: 'string' }
    }
  }
})
```
