### ISSUE TITLE
Feature Request:  onConflict   skip option

### ISSUE THREAD

**Issue by kvandelden** [js-data/js-data#454]
During the DataStore / Collection add(), if the record already exists, the current onConflict  options allow for "merge" and "replace".    Can you add a "skip/ ignore" option, which models how Entity Framework handles duplicate reads from a data source.  We want to avoid over writing changes the user may have already made to the record on the front end, but hasn't saved.... we consider the source record  to be stale after we have read it once.

Thanks,K

**Comment by Sweet-Bob** [comment]
+1

**Comment by jmdobry** [comment]
Anybody want to submit a PR for this?

**Comment by kvandelden** [comment]
Sure

**Comment by Sweet-Bob** [comment]
Yes yes yes! =)

**Comment by jmdobry** [comment]
@kvandelden Thanks for implementing this!
