### ISSUE TITLE
Polymorphic Relationships..

### ISSUE THREAD

**Issue by kvandelden** [js-data/js-data#455]
Hello,

I'd like to define two relationships to the same entity, but use different foreign keys and local fields.

Following this example, adjusting for v3...
https://github.com/js-data/js-data/issues/302

I am not able to define the relationship... without getRelation() throwing an error.
![image](https://cloud.githubusercontent.com/assets/17126950/24481777/59331234-14b2-11e7-9985-289fa2cdd7aa.png)

When the record relationships calls getRelation() to obtain the target mapper,  the system uses "Parents" to determine the mapper name.  
![image](https://cloud.githubusercontent.com/assets/17126950/24482042/217ca0ec-14b4-11e7-9f0f-4fc6c0a0225b.png)

 There doesn't appear to be a way to redefine getRelation().. to consider an alternative property like..foreignMapper.. 
![image](https://cloud.githubusercontent.com/assets/17126950/24482140/b7478cc2-14b4-11e7-9777-8ff8566665bf.png)

Since we subclass the stock DataStore, we could add support for mapper aliases... which may allow us get around this.

Any suggestions are welcome.

Thanks,
Kurt

**Comment by kvandelden** [comment]
I was able to work / hack around this by overriding our DataStore's subclass' getMapper() and getCollection() methods... to allow us to define aliases as <real_name> + ##. 

In the relationships.. added + '2'.
![image](https://cloud.githubusercontent.com/assets/17126950/24483303/d06e0f66-14bc-11e7-92ab-5b4e8e31b94a.png)

In the DataStore class.. 
![image](https://cloud.githubusercontent.com/assets/17126950/24483354/2f60c540-14bd-11e7-998e-27554e3d30ac.png)

**Comment by jmdobry** [comment]
I'm glad you got it to work by subclassing (one of the goals of v3 was to make these kinds of customizations possible).

However, you _can_ define multiple relationships to another Mapper, just use an array:

```js
import { Container } from 'js-data';

const store = new Container();

store.defineMapper('foo', {
  relations: {
    hasMany: {
      bar: [
        {
          localField: 'bars_1',
          foreignKey: 'foo_id_1'
        },
        {
          localField: 'bars_2',
          foreignKey: 'foo_id_2'
        }
      ]
    }
  }
})

store.defineMapper('bar', {
  relations: {
    belongsTo: {
      foo: [
        {
          localField: 'foo_1',
          foreignKey: 'foo_id_1'
        },
        {
          localField: 'foo_2',
          foreignKey: 'foo_id_2'
        }
      ]
    }
  }
})
```

Did using arrays not work for your use case?

**Comment by kvandelden** [comment]
Perfect.. I'll try that out.. I didn't catch that in the samples..

**Comment by kvandelden** [comment]
This worked.
