### ISSUE TITLE
`maxAge` as function which accepts `find`/`findAll` `params` as arguments

### ISSUE THREAD

**Issue by ljqx** [js-data/js-data#460]
Sometime we want different `maxAge` according to the query `params` for `find`/`findAll`. For example, when query `params` contains a date range, when the range contains today, we want the `maxAge` to be minimum to be real time, but if it doesn't contain today, the data is mostly fixed and we want a longer `maxAge`.

`maxAge` now is an integer, we cannot associate it with query `params` no matter we pass it to store or resource, if we construct `maxAge` for `find`/`findAll` function, that's too much for every references.

So better to support function `maxAge` which accepts query `params` which is `params` for `findAll` and `{ where: { idAttribute: id } }` for `find` and returns the millisecond as original `maxAge`.

If this is acceptable, I can send a PR for this.

**Comment by jmdobry** [comment]
Are you using JSData v2 or v3?

**Comment by ljqx** [comment]
@jmdobry v2

**Comment by crobinson42** [comment]
@ljqx v2 doesn't have any active enhancements planned - You have the option to migrate to v3 or of course you're welcome to submit a PR against the `v2` branch :-)
