### ISSUE TITLE
Mapper with schema: Cannot get POJO from Record instance

### ISSUE THREAD

**Issue by bdfoster** [js-data/js-data#461]
On 3.0.0.rc.9, when a Mapper is defined in a Container:
```javascript
store = new Container();
store.registerAdapter('rethinkdb', adapter, {
  default: true
});
store.defineMapper('person', {
  schema: {
    properties: {
      givenName: {
        description: 'The person\'s given (first) name.',
        type: 'string',
        minLength: 1,
        maxLength: 50,
        required: true
      },
      middleName: {
        description: 'The person\'s middle name.',
        type: 'string',
        minLength: 1,
        maxLength: 50,
        required: false
      },
      familyName: {
        description: 'The person\'s family (last) name.',
        type: 'string',
        minLength: 1,
        maxLength: 100,
        required: true
      },
      birthDate: {
        description: 'The person\'s date of birth.',
        type: 'string',
        format: 'date',
        required: false
      }
    }
  }
});
```
...you cannot get a JSON object (really, POJO) with all properties when a schema is in the mix:
```javascript
store.find('person', 1).then((record) => {
  console.log(record);
  console.log(record.toJSON());
});
```
However, you can get back a POJO if there's no schema defined:
```javascript
store = new Container();
store.registerAdapter('rethinkdb', adapter, {
  default: true
});
store.defineMapper('person');
store.find('person', 1).then((record) => {
  console.log(record);
  console.log(record.toJSON());
});
```
This seems like a bug, or at least an inconsistency in which I cannot find the documentation to correctly get a POJO from a Record instance.

**Comment by jmdobry** [comment]
so what does `record.toJSON()` give you?

**Comment by bdfoster** [comment]
Sorry, forgot to mention that.

If Mapper instance has a schema, `record.toJSON()` gives me a blank object:
```javascript
{}
```

On a result from `store.findAll` it gives me an array of blank objects, one
for each record:
```javascript
[{}, {}, {}] // if the collection has 3 records
```
Without a schema, everything returns normal including the generated `id`
field.

**Comment by jmdobry** [comment]
I'm struggling to reproduce the behavior you're seeing. Here's where I tried: https://runkit.com/jdobry/repro-461

Could you possibly put together a sample with with I can reproduce what you're seeing?

**Comment by bdfoster** [comment]
I can (probably won't be until tonight or tomorrow) but I think the biggest difference is that you're using `store.createRecord()` while I'm using `store.create()` and waiting on the resolved Promise. But I will get a better example for you as soon as possible.

**Comment by jmdobry** [comment]
Internally, `store.create()` should be resolving the promise with the result of calling `store.createRecord()`, e.g.

```js
import { Record } from 'js-data';
// ...
store.find('person', 1).then((person) => {
  console.log(person instanceof Record); // true
});
```

```js
import { Record } from 'js-data';
// ...
store.create('person', { givenName: 'John' }).then((person) => {
  console.log(person instanceof Record); // true
});
```

**Comment by bdfoster** [comment]
I'm going to close as invalid. After rewriting that section in the code, I found out I was importing the schema from another file the wrong way... Apparently I had a bad day :face_with_head_bandage: 

Thank you for your help!

**Comment by jmdobry** [comment]
¯\_(ツ)_/¯

**Comment by bodhisattva082915** [comment]
@bdfoster Could you describe the wrong way you were importing the schema from another file? I'm running into the same issue as you described and fixed it by defining my schema directly in the file that I define the mapper.

This will work fine..

```
// mapper.js
import { Record } from 'js-data';
import relations from './relations';
import ChimeraSchema from '../Schema';
import jsonSchemaDraft07 from 'ajv/lib/refs/json-schema-draft-07.json';

class ChimeraField extends Record {};

export default {
	collection: 'ChimeraField',
	recordClass: ChimeraField,
	schema: new ChimeraSchema({
		$schema: 'http://json-schema.org/draft-07/schema#',
		title: 'Chimera Field',
		description: 'Validates data as a JSON Schema property.',
		definitions: jsonSchemaDraft07.definitions,
		type: 'object',
		properties: {
			myField: 'hey',
			...jsonSchemaDraft07.properties
		}
	}),
	relations
};
```

This however will generate `{}` objects when applying the schema (almost as if the isn't there at all)

```
// mapper.js
import { Record } from 'js-data';
import schema from './schema';
import relations from './relations';
import ChimeraSchema from '../Schema';

class ChimeraField extends Record {};

export default {
	collection: 'ChimeraField',
	recordClass: ChimeraField,
	schema: new ChimeraSchema(schema),
	relations
};

// schema.js
import jsonSchemaDraft07 from 'ajv/lib/refs/json-schema-draft-07.json';

export default {
	$schema: 'http://json-schema.org/draft-07/schema#',
	title: 'Chimera Field',
	description: 'Validates data as a JSON Schema property.',
	definitions: jsonSchemaDraft07.definitions,
	properties: {
		myField: 'hey',
		...jsonSchemaDraft07.properties
	},
	required: [
		'modelId',
		'name'
	]
};
```
