### ISSUE TITLE
belongsTo:  foreign key set to undefined when missing referenced record..

### ISSUE THREAD

**Issue by kvandelden** [js-data/js-data#464]
We are running into an issue when defining a belongsTo relationship between two tables with the same primary key.  The relationship between the tables is 1:[0..1],   master.pk = peer.pk .  When we load the relationship of a master row,  when the peer table is empty, 1:0, the primary key of the master record is set to undefined.
In general, when a belongsTo relationship isn't resolved... is it possible to leave the original foreign key in tact?

Thanks,
Kurt

**Comment by kvandelden** [comment]
I can contribute a PR here.. let me know.

**Comment by kvandelden** [comment]
I may not be using the belongsTo relationship as it was intended.  If so changing this behavior doesn't make sense if aggregations are maintained based on the foreign key in question.
Here is my understanding.. 
A.   belongsTo: / hasMany can be paired to maintain aggregation relationships.  An collection index is created on the foreign key to speed up aggregation maintenance.

B.  belongsTo: relationships can be created one way.. a supporting index isn't needed to maintain the reverse hasMany relationship, which doesn't exist.  In this case, the missing record wouldn't need to change the foreign key, if the record isn't found. 

Maybe this can be a relationship property.. . allowing both behaviors to exist in the one way (B) case.
1. default behavior, maintain the foreign key as is.. (strict)
2. "soft" relationship.. don't maintain the foreign key if the value is set to undefined ?

**Comment by jmdobry** [comment]
I'm thinking case A is the primary supported use case. If you define a belongsTo relationship, js-data really expects you to also specify the reverse hasMany relationship (even if you don't intend to use it).

**Comment by kvandelden** [comment]
I was able to use a HasOne relationship in this case to avoid the behavior of setting the foreign key to undefined.
