### ISSUE TITLE
findAll issue when resource returns empty collection

### ISSUE THREAD

**Issue by NenadP** [js-data/js-data#469]
When using `findAll` and specifiying `idAttribute` in the model, if server returns empty collection, I get 

> "attrs" must contain the property specified by "idAttribute". 

I couldn't find a way how to handle this case, or documentation related to this.

**Comment by Tronix117** [comment]
It shouldn't do that, are you sure it returns an empty collection ? Do you have some plunkr with some JSON datas ?

**Comment by NenadP** [comment]
It's not possible to get it on plunker because it has wrappers around JsData but in a nutshell my RestAPI call returns
```json
{ "data": [] }
```
when calling...
```javascript
this.myService.findAll({ params }, { adapter: 'myAdapter' });
```
where `this.myservice` is repository
```javascript
export default {
	name: 'myService',
	endpointExtension: '{{id}}/my_endpoint',
	idAttribute: 'id',
	fields: ['id', 'username'],
};
```

I just wondered if that is default behaviour of jsData `findAll` to throw this if there is no data obtained?

**Comment by Tronix117** [comment]
On `find` the default behaviour is to reject an error, not with findAll, you should get an empty `array`.

I think the adapter you are using, is sending back something instead of an empty array, so JS-Data tries to inject that, but can't cause it doesn't find the `id`. Which adapter are you using ?

What are the wrapper methods that are used ?

**Comment by NenadP** [comment]
We use     `"js-data": "2.9.0"`, `"js-data-http": "2.2.2"`,
then...
```javascript 
import DSHttpAdapter from 'js-data-http';
const httpAdapter = new DSHttpAdapter(config);
```
...and then uses `httpAdapter.findAll`, but indeed there is some pre/post processing of data there which I need to investigate.

But if default behavior is to return empty array, it's good to close for the time being :)

**Comment by Tronix117** [comment]
Great, also don't forget to include versions of `js-data` and adapters, in future issues, because there is some major changes with v3 and it behaves differently (not on this matter though)

**Comment by jmdobry** [comment]
@Tronix117 is right, `findAll` was expecting the response to be an array and was injecting it into the store. v2 provides a few hooks where you could instruct js-data to use that nested data field, and v3 has even more hooks. There isn't a single answer on how you would approach this.
