### ISSUE TITLE
website kicking out 500

### ISSUE THREAD

**Issue by wookiecooking** [js-data/js-data#47]
![error](https://cloud.githubusercontent.com/assets/613991/6086794/86a0a8de-ae12-11e4-8e3c-40e66eeb2cba.png)

**Comment by kentcdodds** [comment]
Confirmed from my end.

**Comment by wookiecooking** [comment]
looks up now, ill close in a few minutes.

**Comment by jmdobry** [comment]
I talked to the Readme.io people, one of their providers went down, should
be back now.
