### ISSUE TITLE
Extensions in endpoints?

### ISSUE THREAD

**Issue by kutakdogan** [js-data/js-data#48]
Noticed that there isn't a way to add extensions to endpoints, such that the same resource could hit both `GET /posts.json` and `GET /posts/1.json`. My backend uses extension parsing which is why this poses a problem for me.

Tried some workarounds but ultimately would need to set the endpoint for each call to find() or findAll() etc, which defeats the DRY mentality.

If there were a way to (a) add extensions via config or (b) modify endpoints for each type of CRUD operation, the issue could be resolved. Thoughts?

**Comment by jmdobry** [comment]
I hadn't ever considered endpoint extensions, so there isn't really a way to do it in a DRY way right now. I'll have to think about it.

**Comment by jmdobry** [comment]
@kutakdogan Are you using js-data-angular? The quickest win I can think of for you here would be to add a request interceptor to $http that appends `.json` to the request url.

**Comment by kutakdogan** [comment]
Yes I am - that could certainly work. I ended up adding a couple of lines in js-data and js-data-angular to allow extensions defined in the configuration, but that was just a sticky-tape fix for my personal environment. I'll try the interceptor solution, otherwise this won't work in production, thanks.

**Comment by jmdobry** [comment]
js-data-http >= 1.2.0 and js-data-angular >= 2.2.0 support a `suffix` config option. 

See https://github.com/js-data/js-data-http/blob/master/test/find.spec.js#L94 and https://github.com/js-data/js-data-http/blob/master/test/find.spec.js#L94

**Comment by kutakdogan** [comment]
Works great thanks!
