### ISSUE TITLE
Support Replication

### ISSUE THREAD

**Issue by edwardjiawei** [js-data/js-data#482]
## Description
- Support Replication for across different DB. Can be narrow to table to table first like StrongLoop doing:
https://strongloop.com/strongblog/node-js-replication-mobile-offline-sync-loopback/

- js-data is one of good library out there as it support browser, which seldom find on node.js space for now. So this use case should allows more cross devices apps build on node.js

## Steps to reproduce
None.
Implement API like following for simple use case.

// sync the data every 2 seconds

setInterval(function() {
LocalTodo.replicate(RemoteTodo);
RemoteTodo.replicate(LocalTodo);
}, 2000);

Thanks!

**Comment by crobinson42** [comment]
@edwardjiawei this can be something that is handled in adapters either a custom adapter or your own code base and extending adapter methods. If you think this is a responsibility that should exist in js-data core, please post back.

**Comment by crobinson42** [comment]
Also, we have a slack team channel you can discuss this feature/enhancement in.
