### ISSUE TITLE
jsData with ReactJS

### ISSUE THREAD

**Issue by prionkor** [js-data/js-data#484]
This is rather a discussion then a question. I can not post it on SO. So, person me if I am breaking any rule. I am using React with Redux for my web application. However I still need a model/data layer for my application. Currently I am using axios for server call and manage the data collection in an object. Checking and Syncing with server if required. But it gets difficult to manage as the application grows bigger.

Is jsData correct choice for me? What I am looking for is a tool that will help me organize my data, cache data so I do not need to call server unnecessarily. I have used ember-data before and I loved it. So, I am looking for something similar. I have read part of the documentation for jsData and it looks promising. 

Requirements
----------------

1. If a previous occasion I called `/user/1` which fetched from server. Now if I try the same query again the data layer should make a the decision and return me previously sent data and save the extra roundtrip to the server.

2. Option to force fetch (avoid cache) if data is old. Saving data on local storage is okay.

3. JWT support on ajax calls.

I see angular adaptation of the library but no react. Is it a good idea to use this library with ractJS. As the library itself is framework agnostic so I guess I can use it but I would like an expert opinion.

Thank you :)

**Comment by Gregcop1** [comment]
I've used it with several angularjs and react projects and I think it's a really great lib. I've combined localstorage, indexedDB (localforage), http adapter and everything was smooth. Angularjs needs an adapter but react don't. You can you the http adapter. 
I've encountered some problems when the API was not RESTful. (weird entrypoints, weirs response..) but even in those cases, it's possible to find solution. I plan to make an adapter for hypermedia API one day (we use [Api platform](https://github.com/api-platform/) a lot here) but I've not started it yet.

**Comment by prionkor** [comment]
My application is also using redux. So the `store` object is a redux store. Not sure how to use jsdata with `react-redux`.

**Comment by Gregcop1** [comment]
It's independant. Redux keeps state of your app. If you want to interact with async data, you can try react-thunk or saga.
