### ISSUE TITLE
with doesn't support nested ressources

### ISSUE THREAD

**Issue by BennyAlex** [js-data/js-data#490]
## Description
In the docs I found the 'with'-option wich I try to use, but it looks like it's not working corrctly.

## Steps to reproduce
I try to get the products of a category ('category.products'). A category belongs to a company ('company.categories' / 'category.company')
I have a nested ressource here, so the category is found under 

> /api/companies/<company_id>/categories/<category_id>

And the products are 
> /api/companies/<company_id>/categories/<category_id>/products

This will work like I expect, it's using the right urls

```
const category = await store.find(CATEGORY, this.categoryId, {
  params: {companyId: this.companyId}
)
// -> /api/companies/<company_id>/categories/<category_id>
category.products = await store.findAll(PRODUCT, {
  categoryId: this.categoryId,
  companyId: category.companyId
})
// -> /api/companies/<company_id>/categories/<category_id>/products
```

But I don't like it much to do the products request by myself and add the products to the category manually, so I tried the 'with'-option

So this
```
const category = await store.find(CATEGORY, this.categoryId, {
          params: {companyId: this.companyId},
          'with': ['product'] // even tried 'products', same result
        })
```
will give me the following (wrong) url:

> /api/products?where=%7B%22categoryId%22:%7B%22%3D%3D%22:%22anzeigenblatt-kategorie-1%22%7D%7D

So is this a bug or did I missed something?

**Comment by crobinson42** [comment]
@BennyAlex if you're still having issues with your use case try to get some help by posting in the slack team #ineedhelp channel. If it turns out to be a bug you've discovered, please post back here.
