### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by jake-lambert-volusion** [js-data/js-data#491]
I am very interested in JS-Data. 

There seems to be very little activity in the repo and a growing list of issues which don't appear to have gotten any consideration.

Is this project actively maintained?

**Comment by crobinson42** [comment]
@jake-lambert-volusion from the JS-Data community slack #general channel:
https://js-data.slack.com/archives/C0D1H5L65/p1503072197000355
https://www.dropbox.com/s/nzy56cytmxpkzvn/Screenshot%202017-12-26%2014.35.50.png?dl=0

jmdobry
@everyone Hey folks, I'm in the process of performing the v3 stable release. `js-data`, `js-data-http`, `js-data-http-node`, `js-data-fetch`, `js-data-mongodb` and `js-data-sql` have all been upgraded to the latest and greatest and released to npm. In addition, the v3 docs on js-data.io are now the default. I'll work my way through the remaining adapters over the next couple days.

My activity on js-data has been low over the last several months for several reasons: 1) 2nd kid was born 2) moved to a new house 3) summer vacations 4) _really_ busy at work (we're hiring btw, see https://goo.gl/U9PttS, says `.NET` but we need Node.js folks as well, send me a DM).

That being said, js-data is not dead, in fact js-data downloads have nearly doubled from what they were 6 months ago. A project as large and complex as js-data should not depend on 1 person, so I'm asking for your help, whatever form that may take. I think there needs to be a discussion here on project maintenance going forward: I need to know 1) who is using js-data? 2) are you using it in a revenue-generating product? 3) can you/your company contribute and/or support continued js-data development? I talked to Evan You (creator of Vue.js) about his Patreon page, perhaps something along those lines could be an option for me here. There's also https://www.bountysource.com/, if you feel strongly about a particular bug/feature and your company needs it fixed.
