### ISSUE TITLE
instanceof for class instances

### ISSUE THREAD

**Issue by elado** [js-data/js-data#50]
I see that `model instanceof Resource` is not returning true, and the only way is to use `DS.definitions` as in

```js
user instanceof DS.definitions['user']['User']
```

Is there another recommended way? (Otherwise, feature request :smile: )

**Comment by jmdobry** [comment]
The resource definition returned by `DS#defineResource` is not the constructor function used to create instances. I tried, but I could not combine the dynamic generation of a named constructor function with the resources inheriting configuration from `DS#defaults` via the prototype. Maybe there's a way to do this, but it's beyond me (or beyond JavaScript).

Therefore, `DS#defineResource` returns a resource definition that inherits configuration from `DS#defaults` via the prototype while allowing you to override configuration when you define the resource, and a then separate named constructor function is generated on the fly from which instances can be created.

Example:

```js
var store = new JSData.DS();
var User = store.defineResource('user');
User.class; // "User"
User[User.class]; // function User() {}

var user = User.createInstance({ id: 1, name: 'John' });
user; // User {name: "John"}

user instanceof User; // false
user instanceof User[User.class]; // true
```

Perhaps I could add some sort of helper function for instanceof testing, e.g. `User.isOfClass(user); // true`, `User.is(user)`, etc.

**Comment by elado** [comment]
`User.is` sounds good. Care to elaborate on the `DS#defineResource` issue?
