### ISSUE TITLE
Future of JS Data

### ISSUE THREAD

**Issue by demisx** [js-data/js-data#504]
Hi. Can @jmdobry or any core people please share their vision on the future of JS Data? It appears there was not much activity since February 2018 and we are just worried that this awesome ORM has been abandoned. Any insight would be highly appreciated. Would like to use this ORM for new products and recommend to others, but it's hard to do this without understanding the product roadmap. Thank you very much!

**Comment by crobinson42** [comment]
Hi @demisx - @jmdobry has contributed a ton to this project and it's pretty stable and usable in production. As an open-source project, it's kind of up to the community to also help maintain a project if it's something they appreciate, enjoy, and possibly rely on. You are right in your observation there hasn't been much activity here - are you looking for anything on a roadmap that the library doesn't already offer?

**Comment by crobinson42** [comment]
PS thanks for the bump, I'll see about contributing a little time to helping move long some PR's and bug fixes.

**Comment by demisx** [comment]
@crobinson42 Thank you for your prompt reply. Truly appreciate it! I don't have anything at the moment  to ask for. I was mostly interested whether this project was still maintained and whether it could be recommended for the future projects. It is a great ORM and @jmdobry is one brilliant guy. Would be said to see this gem being abandoned. I guess it's not the case and I am very happy to hear it.

**Comment by jmdobry** [comment]
👋 Hey folks, I'm still around, just busy. JSData is alive, but surely deserves more of my attention. I appreciate each and every contribution to the project.

With regard to JSData v3: it's stable and ~done. I definitely need to circle back and fix any bugs that have cropped up and update development dependencies, as they seem to break every other month. But other than that, JSData is still kicking.

From a developer experience point of view, JSData, like most projects, could definitely use more/better docs and examples; I hopefully got http://js-data.io and http://api.js-data.io to the point where people can continue to be successful with the project.

**Comment by bodhisattva082915** [comment]
Just to @demisx, awesome ORM / ODM. Haven't seen something quite this robust in quite a while.
