### ISSUE TITLE
Fix broken example links in documentation

### ISSUE THREAD

**Issue by demisx** [js-data/js-data#516]
The Angular 1, Angular 2 and React example links return GitHub 404 error. See attached.

![screen shot 2018-07-30 at 5 46 15 pm](https://user-images.githubusercontent.com/4452412/43431007-b41ae818-9420-11e8-9f1d-2c7d272284d3.gif)

**Comment by crobinson42** [comment]
@dmitri you can suggest edits on the docs site.

**Comment by demisx** [comment]
@crobinson42 I was thinking about that, but won't I need to know what those links are?
