### ISSUE TITLE
unsubscribe http-adapter  ajax request in Angular 6

### ISSUE THREAD

**Issue by suchg** [js-data/js-data#517]
## Description

I am using js-data, http-adapter in Angular 6. After certain time I want to stop the asynchronous http ajax request. The store.findAll method return promis by which we can not stop the ajax request. That is why I am trying to use observables instead of promise, so by using unsubscribe method I could cancel ajax request.

I did follow the steps given in documentations of 'js-data with observables', but ultimately it returns the promise on use the store.findAll method.

Please help me how to convert from promise to observables and subscribe it.

## Environment

- js-data version: 3.0
- node or browser version: ^8.0
- operating system: windows10

**Comment by crobinson42** [comment]
@suchg I recommend posting on Stackoverflow or trying this out in the Slack channel for JS-data.
