### ISSUE TITLE
The latest tagged version is missing compiled files

### ISSUE THREAD

**Issue by jason-garner-volusion** [js-data/js-data#520]
## Description

The latest tagged version is missing compiled files, only the TypeScript definitions file is present. 

## Environment

- js-data version: 3.0.3
- node version: 10.6.0
- operating system: macOS High Sierra 10.13.4

## Steps to reproduce

Add to project using bower.json. Set dependency to "^3.0.1". Bower installs the latest tag 3.0.3. Fixed by setting to "3.0.1" for now.

Not pressing, but may cause issues for some users.

**Comment by crobinson42** [comment]
Thanks! Updated the 3.0.3 tag file tree
