### ISSUE TITLE
find & findAll throw when returned records don't validate with schema

### ISSUE THREAD

**Issue by crobinson42** [js-data/js-data#522]
js-data: `3.0.3`

When performing a `find` or `findAll` async operation to a back-end (js-data adapter), and your Mapper has a schema defined, do you expect the returned data from the server/adapter to be validated against the schema? If so, do you expect an error to throw on that validation and the `find` or `findAll` preventing any of the records from being available?

This question has been sprung because during testing I have ran across what appears to be a *bug*. Of course a `create` or `update` operation is expected to throw when a validation against the mapper’s schema fails. But, for example, if a back-end service returns data that doesn’t match your schema, currently it throws a validation error and blocks you from accessing that data (less using `_raw` option and circumventing a DataStore or SimpleStore cache).

If I have a `userSchema` that says a user’s phone property must be a string, ie: `phone: { type: "string" }` and I perform a `store.findAll('user', {})` and the back-end returns a list of records and 1 of them happens to contain all digits as the `user.phone` prop, the `store.findAll('user')` call throws with a message, “validation failed”. This is not what I would expect in this situation.

**Comment by crobinson42** [comment]
@zuzusik do you agree with the previous behavior? If so, would you propose any changes or enhancements?

**Comment by zuzusik** [comment]
we've found previous behavior destructive, it requires 100% data consistency on backend side, which sometimes really hard to have (specifically, in big systems where there are a lot of legacy code)

also, it is not performance wise in case where backend has validation (and this is the most part of cases, I believe) - if something was saved to backend - it means it has passed validation once, so no need to validate it when receiving

I would say that new default is suitable for most of use cases.
