### ISSUE TITLE
JS-Data v3.0 stop execution in lifecycle hook

### ISSUE THREAD

**Issue by KRaymundus** [js-data/js-data#526]
I am using js-data v3.0 and i am trying to prevent store-injection of the record received from my API upon update if the record was changed while saving.

In js-data v2.9 one could abort the lifecycle by calling a callback with an error as argument (docs)

Now in v3.0 I'm using the mapper#afterUpdate() lifecycle hook (docs), but I don't know how to abort the lifecycle.

**Comment by crobinson42** [comment]
Hi @KRaymundus  you want to take this to the JS-Data slack channel? http://slack.js-data.io/

**Comment by crobinson42** [comment]
The solution to this is using the mapper lifecycle (or mapperDefaults on the DataStore to apply to all mappers):

```
store.defineMapper('users', {
  afterFindAll(query, opts, results) {
    // whatever is returned here will be added [injected] to the "store"
    return null;
  }
)
```

> Note: if `undefined` is returned then the records will be added to the store. If `null` is returned it will NOT add anything to the store.

**Comment by KRaymundus** [comment]
Wow, ok that works. Great thanks! I have been trying for 12 hours before asking. Would be great if anything like this would be in the docs or stackoverflow.

**Comment by KRaymundus** [comment]
Just added a question and answer on stackoverflow:

https://stackoverflow.com/questions/52647639/js-data-v3-0-stop-execution-in-lifecycle-hook
