### ISSUE TITLE
DS#defineResource docs missing deserialize and serialize options

### ISSUE THREAD

**Issue by mattyway** [js-data/js-data#53]
The docs at http://www.js-data.io/v1.3.0/docs/dsdefineresource seem to be missing the deserialize and serialize options.

I am using the deserialize option like this:
```
DS.defineResource({
	name: 'info',
	endpoint: 'info',
	basePath: '/api',
	relations: {
		belongsTo: {
			document: {
				parent: true,
				localField: 'document',
				localKey: 'documentId'
			}
		}
	},
	deserialize: function (resource, data) {
		return [data.data];
	}
});
```

(I have an endpoint that returns a single object instead of an array and am using the deserialize function to place the object in an array so that js-data can use it.)

**Comment by jmdobry** [comment]
If you look at the [CHANGELOG](https://github.com/js-data/js-data-angular/blob/master/CHANGELOG.md#breaking-api-changes) for angular-data 1.x to js-data-angular 2.x you'll see that

> `deserialize` and `serialize` are now properties of `DSHttpAdapter.defaults`

and

> `deserialize` and `serialize` are now configuration options used solely by the http adapter

The options are documented [here](http://www.js-data.io/docs/dshttpadapter#default-settings). The API for js-data-http is the same as the http adapter provided by js-data-angular.

**Comment by mattyway** [comment]
Just to clarify, is specifying a deserialize function in DS.defineResource supported? The example I provided is working with js-data 1.3.0 and js-data-angular 2.1.0.

I missed the note stating that the page didn't list all of the available options. The page the note links to (http://www.js-data.io/v1.3.0/docs/dsdefaults) is also missing the deserialize and serialize functions however.

**Comment by jmdobry** [comment]
> Just to clarify, is specifying a deserialize function in DS.defineResource supported?

Not officially, but it should work. It depends on an internal implementation detail of js-data, which I would have to solidify as part of the API to make this officially supported and not prone to being broken.
