### ISSUE TITLE
feat: Call the inject and eject lifecycle hooks regardless of if the notify option is enabled

### ISSUE THREAD

**Issue by mattlewis92** [js-data/js-data#54]
My use case is that I have the notify option disabled as it causes significant performance issues when it is enabled and injecting several thousand entities at once, however I still want to hook into the before and after inject / eject methods. If you have a default inject / eject hook set then you could override it on a per model basis to a blank method if you required the same behaviour.

**Comment by jmdobry** [comment]
I'll come up with a backwards compatible way to split those up.
