### ISSUE TITLE
orderBy is not correctly comparing strings and null

### ISSUE THREAD

**Issue by zuzusik** [js-data/js-data#540]
## Description

In code below when `cA` is `null` and `cB` is any string, both conditions (`cA > cB` and `cA < cB`) are `false`. This way **any string is considered equal to null**, which is not right. Expected: records where field is `null` appear at the end of the result (exactly like `_.sortBy` works)
https://github.com/js-data/js-data/blob/c3d102a5b255578cd91684ec26f43ffee5044e10/src/Query.js#L266-L270

## Environment

- js-data version: 3.x
- node or browser version: any
- operating system: any

## Steps to reproduce

Try using `filter` with `orderBy` on string field, where some records in collection have this field as `null`

**Comment by crobinson42** [comment]
@zuzusik what do you expect the result of `String > null` to be?

**Comment by zuzusik** [comment]
@crobinson42 there is an expectation set in bug description: 

> Expected: records where field is `null` appear at the end of the result (exactly like `_.sortBy` works)

in lodash:

https://github.com/lodash/lodash/blob/488e62bd79443dd96fd83e631cccf3f68da489b1/test/sortBy.js#L43-L55

so, basically, I think `null` should be treated as empty value, i.e. empty string and put at the end of sorting

**Comment by crobinson42** [comment]
Sorry I missed that - if you have time to put a PR in I can review, merge and publish.

**Comment by crobinson42** [comment]
@zuzusik any comments on #563 ?

**Comment by zuzusik** [comment]
@crobinson42 generally #563 looks good to me - `js-data` definitely needs to consider locale when doing sorting, but also I don't think it is much related to current issue

**Comment by zuzusik** [comment]
BTW, I see now work on `js-data` 4 has started - I think it would be nice to fix current issue there (it looks like a breaking change to me) - I am happy to work on this 👍 could you please assign this issue to me and add to `v4` milestone - I will try to come up with a PR in next few days

**Comment by zuzusik** [comment]
Closing as it is fixed with https://github.com/js-data/js-data/pull/563
