### ISSUE TITLE
Multiple parents for nested urls (re-issued from https://github.com/js-data/js-data-angular/issues/250)

### ISSUE THREAD

**Issue by t-richter** [js-data/js-data#55]
Hi,
I have a special use-case, where multiple belongsTo are needed.
In our data-model, where we don't know the hierarchy-depth of nested elements in advance, so we use a 'general' entity, that is nested in 'itself'. We have an additional 'type' entity, defining the nodes special attributes, like this:
````javascript
name: 'Entity',
endpoint: 'entities.json',

relations:
{
    belongsTo:
    {
        Entity:
        {
            localField: 'parent',
            localKey: 'parentId',
            parent: false
        },
        EntityType:
        {
            localField: 'type',
            localKey: 'typeId'
        }
    },
    hasMany:
    {
        Entity:
        {
            localField: 'children',
            foreignKey: 'parentId'
        }
}
````

I didn't find a clue in the docs this wouldn't work, but unfortunately it doesn't seem to do so.
It produces an error:
````
Entity RuntimeError Object
  37.defaultsPrototype.error	
  37.defaultsPrototype.errorFn	
  _inject	
  _inject	
  inject	
  (anonymous function)	
  processResults	
  (anonymous function)	
  deferred.promise.then.wrappedCallback	
  (anonymous function)	
  $get.Scope.$eval	
  $get.Scope.$digest	
  $get.Scope.$apply	
  done	
  completeRequest	
  xhr.onreadystatechange	
Entity RuntimeError Object
  37.defaultsPrototype.error	
  37.defaultsPrototype.errorFn	
  _inject	
  _inject	
  inject	
  (anonymous function)	
  processResults	
  (anonymous function)	
  deferred.promise.then.wrappedCallback	
  (anonymous function)	
  $get.Scope.$eval	
  $get.Scope.$digest	
  $get.Scope.$apply	
  done	
  completeRequest	
  xhr.onreadystatechange	
Entity RuntimeError Object
  37.defaultsPrototype.error	
  37.defaultsPrototype.errorFn	
  _inject	
  _inject	
  inject	
  (anonymous function)	
  processResults	
  (anonymous function)	
  deferred.promise.then.wrappedCallback	
  (anonymous function)	
  $get.Scope.$eval	
  $get.Scope.$digest	
  $get.Scope.$apply	
  done	
  completeRequest	
  xhr.onreadystatechange	
TypeError: Cannot read property 'id' of undefined
````

**Comment by t-richter** [comment]
Sorry for posting this 'error' it seems it was casted due to my fault, 'EntityType' was not injected to the DS beforehand. I changed the resource definition from .factory to .run as described here:
http://www.js-data.io/v1.3.0/docs/js-data-angular
I still have a problem when trying to refer to a related item in a 'computed' property.
````
            name: 'Entity',
            endpoint: 'entities.json',

            relations:
            {
                belongsTo:
                {
                    Entity:
                    {
                        localField: 'parent',
                        localKey: 'parentId',
                        parent: false
                    }
                    ,
                    EntityType:
                    {
                        localField: 'type',
                        localKey: 'typeId',
                        parent: false
                    }
                }
                ,
                hasMany:
                {
                    Entity:
                    {
                        localField: 'children',
                        foreignKey: 'parentId'
                    }
                }

            },

            computed: {
                'label': ['name',
                    function (name) {
                        return name;
                    }
                ]
                ,
                'icon': ['type',
                    function (type) {
                        logger.info("has type: " + type);
                        return (type && type.iconref ? type.iconref : 'fa fa-file');
                    }
                ]

            }
````

the icon property will never resolve to anything else but "fa fa-file".
I'm not sure, if it's connected with the multiple belongsTo? Or a completely different issue?
Many thx anyway.

**Comment by jmdobry** [comment]
The computed property issue would be unrelated to the multiple belongsTo.

**Comment by rigobcastro** [comment]
Hi, What is the solution for multiple belongsTo with parent? I need the nested url for many models., e.g:

groups/{id}/permissions
users/{id}/permissions

Any idea for this? Thanks.

**Comment by jmdobry** [comment]
I haven't solved it yet. js-data still assumes a resource can only have one parent. I'm thinking I might be able to add an option so you can specify which relation to use as the parent when you're doing find, update, destroy, etc.

**Comment by rigobcastro** [comment]
@jmdobry Nice! I think this can optional via config, with this feature, the polymorphism would be posible http://en.wikipedia.org/wiki/Polymorphism_(computer_science) in js-data.

**Comment by t-richter** [comment]
Very cool, indeed!
Does the 'ready' tag mean, you've already done this? Can we check this out alrady?
thx!

**Comment by jmdobry** [comment]
No, it means it's ready to be worked on.

**Comment by pdorgambide** [comment]
+1 to allow inheritance on resource definition. An alternative will be set on defineResource (options, extends). 
```
 var User = store.defineResource({
  name: 'user',
  relations: {
    hasMany: {
      comment: {
        localField: 'comments',
        foreignKey: 'userId'
      }
    },
    belongsTo: {
      organization: {
        localKey: 'organizationId',
        localField: 'organization',
        
        // if you add this to a belongsTo relation
        // then js-data will attempt to use
        // a nested url structure, e.g. /organization/15/user/4
        parent: true
      }
    }
  }
});
var SecuredUser = store.defineResource({ 
name: 'secureduser',
 hasOne: {
      role: {
        localField: 'role',
        foreignKey: 'userId'
      }
    },
},User)
```

If inject an instace of secured

 ```
var userJson = {
  id: 10,
  name: 'John Anderson',
  profile: {
    email: 'John Anderson',
    id: 18,
    userId: 10
  }

};
SecuredUser.inject(userJson);
User.get(10) // 
```
it also will be avalable from User.get(10) and from UserSecured resource we can fetch the relations defined on User. 
``` User.loadRelations(user, ['comment'])

**Comment by jmdobry** [comment]
I think inheritance among resource definitions is a separate issue from a single resource belonging to multiple parent resources.

**Comment by pdorgambide** [comment]
Yes, you are right, the comment about polymorphism made me confuse.  If it is not implemented I may  open a new issue.
Thx a lot.

**Comment by WillsB3** [comment]
:+1: We also need the ability to be able to specify multiple belongsTo relations.

**Comment by jmdobry** [comment]
You can already have multiple belongsTo relationships. This issue is here because right now you can only have one belongsTo relationship that is also set to `parent: true`

**Comment by WillsB3** [comment]
@jmdobry Right. Unfortunately our project has many models where the endpoint relies on many multiple parent models so we are hitting the same issue as the OP of this issue.

@jmdobry We could take a look at implementing something with a view to opening a pull request if you can give us some guidance on the approach you would like to take?

**Comment by jmdobry** [comment]
I think the best way to address this might actually be with some architectural changes in 2.0. I'm wanting to make things a little more modular, with a more plugin-like architecture.

**Comment by jmdobry** [comment]
I'm going to release 2.0, then find a backwards compatible way to make this work.

**Comment by WillsB3** [comment]
:+1:

**Comment by tfoxy** [comment]
I'm willing to make a PR for this. Have you made any progress?

**Comment by jmdobry** [comment]
nope, nor do I have any ideas on the best way to implement or handle this

**Comment by tfoxy** [comment]
OK. I will check the code and try to come up with a solution.
