### ISSUE TITLE
typo in docs

### ISSUE THREAD

**Issue by xavifuefer** [js-data/js-data#56]
In http://www.js-data.io/v1.3.0/docs/js-data-angular when explaining adapters the first example has a line like that:
```javascript
DSFirebaseAdapterProvider.defaults = 'https://myfirebaseurl.com';
```
and should be
```javascript
DSFirebaseAdapterProvider.defaults.basePath = 'https://myfirebaseurl.com';
```

**Comment by jmdobry** [comment]
Thanks. In the future you can login to the docs and make suggested changes, which I can then merge in with a click of a button.
