### ISSUE TITLE
bug: items injected via a relationship fail to fire notifications

### ISSUE THREAD

**Issue by dremonkey** [js-data/js-data#72]
So I've been investigating this problem and it looks like the reason this is happening is that the parent options are overriding the options for the linked children. 

From what I can tell this is what is happening:

1. options are created for the parent - https://github.com/js-data/js-data/blob/master/src/datastore/sync_methods/inject.js#L218
2. parent options are passed to the ```_inject``` method: https://github.com/js-data/js-data/blob/master/src/datastore/sync_methods/inject.js#L240-L246
3. child ```inject``` method is called https://github.com/js-data/js-data/blob/master/src/datastore/sync_methods/inject.js#L240-L246. The options being passed in here are coming from the parent
4. child definition is extended with the parent options, overriding child definition https://github.com/js-data/js-data/blob/master/src/datastore/sync_methods/inject.js#L218

Does my analysis seem right to you?

**Comment by jmdobry** [comment]
Yes, I think I know what the issue is. The _inject calls for the relation need to just be given the "own" properties of the original `options` (if any were provided), instead of the augmented options you pointed out on line 218.

**Comment by dremonkey** [comment]
That was super fast. And yeah... that makes sense. Better than the solution I had come up with. I can work on implementing a fix now or do you want to handle it?

**Comment by jmdobry** [comment]
The fix is easy enough, I'll do it.

**Comment by jmdobry** [comment]
This might actually be related to #35

**Comment by dremonkey** [comment]
Thanks for quick fix. Unfortunately I think this bug is still present. I don't think it is enough to just save the original options in the ```inject``` method. When inject is called from another method (```findAll```, ```find```, etc) the option have already been augmented so the original options have essentially already been corrupted.

Is there a way to extract the original options from the augmented option?

**Comment by jmdobry** [comment]
That's a good point. So I did fix one instance of the problem–when you're calling `inject` directly. Indirect calls to `inject` still get the "corrupted" options. 

The fix will probably require changes to several more files. I'll probably add a helper method to the augmented `Options` prototype that gives you the original properties.
