### ISSUE TITLE
Yeoman generator / Cli utility

### ISSUE THREAD

**Issue by jgoux** [js-data/js-data#77]
Hi,
thanks for this wonderful library.
Is there a roadmap to create a yeoman generator or a cli utility to generate code and/or add features.
For example, your library is perfect to reuse view-models between a SPA and a node.js backend, and I think being able to generate API endpoint from js-data-schema would be neat to close the loop between the SPA and the backend.

I was interested in strongloop first, but it generates too much code (including authorization/login) and the angular files generated are complicated, it does too much for me. But as your library is minimal and very focused I think it could be really great to have a cli acheving the same purpose, meaning a set of minimal commands to do one task, but do it well.

**Comment by jmdobry** [comment]
Interesting idea. I myself don't use a cli to generate code, but I've got a buddy who works on the angular generator. Perhaps he has some tips.

**Comment by jmdobry** [comment]
I'm probably never going to work on a yeoman generator / Cli utility for js-data. You or anyone is welcome to work on one.

If someone gets serious about this and writes one and wants to be responsible for it, we could have the repo under the umbrella of the js-data Github organization, and you would be added to the organization with write access to the cli repo.

Closing this issue, hopefully not crushing anyone's dreams...
