### ISSUE TITLE
supporting composite PK/FKs

### ISSUE THREAD

**Issue by nlac** [js-data/js-data#78]
Hi,
i think it would be useful to support composite primary keys in models, so eg.
```
var SongModel = DS.defineResource({
  ...
  idAttribute: ["albumID","trackNumber"]
  ...
});
var song = SongModel.find([1381, 7]);
```
Same could go for the "localField" and "foreignKey" of the relation's definition.

I'm not sure how to append these composite keys to the RESTful URL's by default... maybe simply .../{albumID:1381,trackNumber:7} url-encoded.

**Comment by jmdobry** [comment]
Try this:

```js
var SongModel = DS.defineResource({
  // ...
  name: 'song',
  idAttribute: 'compoundId',
  computed: {
    compoundId: ['albumID', 'trackNumber', function (albumID, trackNumber) {
      return '' + albumID + '_' + trackNumber
    }]
  }
  // ...
});
SongModel._find = function (albumID, trackNumber, options) {
  return SongModel.findAll({ albumID: albumID, trackNumber: trackNumber }, options).then(function (songs) {
    if (songs.length) {
      return songs[0];
    } else {
      throw new Error('Not found!');
    }
  });
};
SongModel._find(1381, 7).then(function (song) {
  song.compoundId; // "1381_7"
  song.albumID; // 1381
  song.trackNumber; // 7

  SongModel.get(song.compoundId) === song; // true
});
```

**Comment by nlac** [comment]
That's COOL! It's incredible useful that i can use computed attribute as "idAttribute". Custom _find() is not even necessary, url can be like eg. `/rest/song/{albumID:1381,trackNumber:7}` so find() can be used. 

I wonder if i can use computed attributes for defining relations (as "localField","foreignKey")? I'll try it anyway - if yes, i think composite keys are already fully supported.

Thanks for the prompt answer.

**Comment by nlac** [comment]
I played around with js-data using computed properties as composite keys and could't find a blocked scenario.

**Comment by jmdobry** [comment]
Nice
