### ISSUE TITLE
Relations do not update Object.observe when removing them

### ISSUE THREAD

**Issue by MikaAK** [js-data/js-data#79]
At work we were running into issues using `Object.observe` to watch models. Normally `Object.observe` only does a shallow observe so we are using [nested-observe](https://github.com/rkusa/nested-observe) to do a deep watch. 

When using this however there has been some issues with running the callback when a relation is update. For example if you have a `User` and a user has many `Items` when removing single `user.items` it only performs the `Object.observe` callback the first time and other removes are ignored. 

I would like to test this is JS-fiddle or similar but cannot figure out how to import JS-data for some reason!

### Example of it without js data 
This is the expected behavior
```javascript
var newData = {}

Nested.observe(newData, function(changes) {
  console.log(changes)
})

newData.collection = [] // changes  callback is run

// Later on in code
newData.collection = newData.collection.concat([{
  item: 2,
  data: 'hello world'
}, {
  item: 3,
  data: 'hello bill'
}]) // changes callback is run

// later on
newData.collection.pop() // Changes callback is run

// Later on again
newData.collection.pop() // Changes callback is run
```

### With JS-Data
This is weird, the first time `.pop()` is called the changes callback runs, the second time however nothing happens

```javascript
var user = {}

Object.observe(user, function(changes) {
  console.log(changes)
})

user = User.get(3) // Change callback runs to initialize user
// user.collection is a hasMany relation on user 

user.collection.pop() // Callback is run

// later in code
user.collection.pop() // No callback is run O.o WHAT THE HECK
```

This behavior is unchanged weather using `.pop()` or `.eject()`.
My question is what does js-data do to collections to make them not run the `Object.observe` callback on change? I've confirmed that this only happens with JS-Data collections and when using a normal array nested however deep it works perfectly fine.

**Comment by jmdobry** [comment]
Hmm, weird. Can you post a little more of your code? What version of js-data are you using? Could you possibly create a plunker or jsfiddle that demonstrates the issue?

**Comment by MikaAK** [comment]
We are using `V1.5.8`, I've tried creating a plunker or jsfiddle but can't get `DS` to work after adding the file. We are using a custom store system [not-flux](https://github.com/MikaAK/not-flux) that does all the change watching. 

I'm not sure how much my code would help unfortunately as the callback for change doesn't even get run when removing items, but I'll add an example store anyway

We also use a custom api service and have the models being injected via an interceptor and then automatically deleted on successful delete (both these are working and have been tested, the data in the store is indeed updated to be the correct representation after ejecting but the callback is not run.)
```javascript
'use strict'

angular.module('edvisor.viewModels.partners.school')
  .factory('SchoolStore', ['NotFlux', '_', 'SchoolActions', 'Partnership', 'PartnershipBankAccount', function(NotFlux, _, SchoolActions, Partnership, PartnershipBankAccount) {
    return NotFlux.createStore({
      init() {
        SchoolActions.loadPartner.listen(this.loadPartner)
        SchoolActions.createBankAccount.listen(this.createBankAccount)
        SchoolActions.deleteBankAccount.listen(this.deleteBankAccount)
      },

      // States
      school: null,

      // Store handlers
      loadPartner(partnerId) {
        Partnership.findById(partnerId, ['partnershipBankAccounts'],
          {refresh: true})
            .success(data => {
              this.school = data
              //this.googlePlaceLookup(data.googlePlaceId)
            })
      },

      createBankAccount(data) {
        var self = this

        PartnershipBankAccount.create(data)
          .success(() => self.emit('partners:createBankAccount:success'))
          .then(() => this.emit('partners:createBankAccount:done'))
      },

      updateBankAccount(data) {
        PartnershipBankAccount.updateOne(data)
          .success(() =>  this.emit('partners:updateBankAccount:success'))
          .then(() => this.emit('partners:updateBankAccount:done'))
      },

      deleteBankAccount: function(data) {
        PartnershipBankAccount.delete(data.partnershipBankAccountId)
          .success(() => {
            this.emit('partners:deleteBankAccount:success')
            this.emitChange() // This is a hack to force a emitchange to happen.
          })
          .then(() => this.emit('partners:deleteBankAccount:done'))
      }
    })
  }])
```

**Comment by jmdobry** [comment]
So with the plunker, are you loading js-data.js and then js-data-angular.js? Here's an example plunker that works: http://plnkr.co/edit/Vu3fQOZaUlMc1BATEox5?p=preview

**Comment by MikaAK** [comment]
Plnkr and I don't seem to get along! I can't reach it without timing out!! But yes I am loading both `js-data.js` and `js-data-angular.js` Do you have a example plunker on JSBin or another codeshare site?

**Comment by jmdobry** [comment]
I did notice that plunker has been having issues today. I'll look for an example on another site.

So, to clarify on your example, the following happens: 

```js
var userAttrs = { id: 1, collection: [{ id: 1 }, { id: 2 }] };
var user = User.inject(userAttrs);
// notice the following
userAttrs === user; // false
userAttrs.collection === user.collection; // false
userAttrs.collection[0] === user.collection[0]; // false

// you start observing
Object.observe(user, function (changes) {
  console.log(changes);
});

// later
user.collection.pop(); // change callback fires

// later
user.collection.pop(); // change callback does NOT fire
```

**Comment by jmdobry** [comment]
I will say that while internally js-data uses a slimmed down version of observe-js for its own change detection, it's consumed in such a way that does not pollute the global scope or mess with native.

Doing a little more research on the spec for `Object.observe`, changing the number of items in an array is supposed to generate a `splice` change record, which is not in the accepted change record list for [`Object.observe`](http://arv.github.io/ecmascript-object-observe/#Object.observe). By default the `splice` change record type is used by [`Array.observe`](http://arv.github.io/ecmascript-object-observe/#Array.observe) only.

If I understand the spec correctly, `Object.observe(someObj, function (changes) { ... })` should _not_ fire the callback if an Array property of `someObj` gets new items or loses items. If the property itself changed (e.g. got pointed to a new array), then that should fire the provided `Object.observe` callback.

**Comment by MikaAK** [comment]
It does actually fire the callback though, this could be due to it being part of `observe-nested`. Taking the first example I showed in my first post, we can see that the callback is run when the array is changed. 

I'm not quite sure whats causing this, our temporary work around is to run the callback manually when updating but it would be great if the callback fired on changes!

```javascript
var newData = {}

Nested.observe(newData, function(changes) {
  console.log(changes)
})

newData.collection = [] // changes  callback is run

// Later on in code
newData.collection = newData.collection.concat([{
  item: 2,
  data: 'hello world'
}, {
  item: 3,
  data: 'hello bill'
}]) // changes callback is run

// later on
newData.collection.pop() // Changes callback is run

// Later on again
newData.collection.pop() // Changes callback is run
```

**Comment by jmdobry** [comment]
Notice that in Chrome, this is not the standard behavior of `Object.observe`. I ran the following in Chrome's console on this page.

```js
> var b = []
> undefined
> var a = { b: b }
> undefined
> Object.observe(a, function (changes) { console.log('changes', changes); })
> Object {b: Array[0]}
> a.c = 5
> VM431:2 changes [Object] // changes logged!
> 5
> a.b.push(1)
> 1
> // no changes logged when length of a.b changes
```

`nested-observe` must be doing something to change the standard behavior (fire changes for more than what `Object.observe` will do by itself). I'm wondering if you're starting your observation of the item before the item is injected into `DS` or before the item's relation gets linked. When you inject data into the store, it creates an initial copy that will then be used for the identity mapping. So, what you pass to inject and what inject returns will not refer to the same object.

**Comment by MikaAK** [comment]
Yes indeed it is, I pasted the [source](https://github.com/rkusa/nested-observe/blob/master/dist/nested-observe.js) into chrome console and checked for splice records and that's why its working! 

To clarify the entire store is actually watched when it gets [initialized](https://github.com/MikaAK/not-flux/blob/master/src/store.js#L19-L19), which means that when the data does get set via callback it would be the result of the `DS.inject`. 

The interceptor is a pretty simple one that parses the url and maps them like so

```javascript
let model,
     data = response.data

if (!dataContainsId(modelName, data)) return

data = 'data' in data ? angular.extend(data, {data: DS.inject(modelName, data.data)}) : DS.inject(modelName, data)

response.data = data
```

which means that in the callback the data would be the injected model.

**Comment by jmdobry** [comment]
At this point I'm going to ask why you want to use js-data in combination with not-flux. According to my (limited) experience with React and Flux, js-data itself can be used as the dispatcher/store in a flux architecture. I wrote an [example app](https://github.com/js-data/js-data-firebase/tree/master/examples/react) based on the Todo example on Facebook's Flux architecture page that replaces the dispatcher/flux code with js-data resources. Looking at not-flux's readme, js-data also has event emitting, can bind data to your $scope, transform data, etc. I haven't fully explored the possibilities here, so there are probably areas where js-data could be improved.

**Comment by MikaAK** [comment]
We finally decided to drop flux! This is not an issue any more.
