### ISSUE TITLE
Many-to-Many relational support

### ISSUE THREAD

**Issue by stringbeans** [js-data/js-data#82]
Is there any way to define a many-to-many relationship?

For example, I have these 3 tables:

entity
entityFile 
file

On the "entity", i want to have a relationship called "files" which does a join THROUGH entityFile. 

Is this currently possible? If not, can this be a feature request?

**Comment by jmdobry** [comment]
[This thread](https://groups.google.com/forum/?fromgroups#!topic/angular-data/o5UK8VYq680) on many-to-many relationships hails from back when js-data + js-data-angular was still angular-data, but it still applies.
