### ISSUE TITLE
Change detection incorrectly handles cycles in the 

### ISSUE THREAD

**Issue by rmja** [js-data/js-data#83]
Hi,

In a simple order/order line test case, when updating the order line, it is possible for the change detection to enter a loop, causing the browser to fail with `Maximum call stack size exceeded`.

The problem happens when the order line is saved twice, as the value of `previousAttributes[id]` contains cycles the second time.

A reproducing example is here: http://plnkr.co/edit/aDS76UPmplwS55X1qQFY

I do not know if the problem is:

1. that the `previousAttributes[id]` should not contain cycles, or
2. that the `diffObjectFromOldObject()` does not correctly handle cycles.

**Comment by jmdobry** [comment]
Thanks, I will debug.

**Comment by jmdobry** [comment]
Should be fixed in 1.5.11.

@rmja Thanks for the plunker demonstrating the issue, it makes debugging much faster and easier.

**Comment by rmja** [comment]
No problem - It also makes it much easier for me to isolate the problem and remove myself from the equation:) Thanks for fixing it so fast.
