### ISSUE TITLE
DS.Inject performance issues when reloading data

### ISSUE THREAD

**Issue by Patrik-Lundqvist** [js-data/js-data#84]
I'm having some performance issues since the introduction of DSUtils.copy in the inject cycle. When injecting a list of 400 objects a second time (reloading the same data) it takes significantly longer time (from 50ms to 8s). Is there any way to disable it?

[Here is a plunker](http://plnkr.co/edit/0Z7NSE?p=preview)

**Comment by jmdobry** [comment]
For me, with 1.5.12 your plunker runs the second inject in ~50-60ms. Cheers :)

**Comment by Patrik-Lundqvist** [comment]
Nice! You're doing some awesome work on this project, love it!

**Comment by jmdobry** [comment]
@Patrik-Lundqvist Thanks for the plunker demonstrating the issue, it makes debugging faster and easier.
