### ISSUE TITLE
endpoint should be part of query hash

### ISSUE THREAD

**Issue by rmja** [js-data/js-data#85]
Normally when I do `findAll(someObj)`, the query is cached based on the values in `someObj`. This is perfectly fine.
However, if I need to query the resource based on some custom endpoint, say `findAll({}, endpoint: '/endpoint1')` and later do a `findAll({}, endpoint: '/endpoint2')`, then the second query is not executed, as the hash key for the cache is based solely on the (empty) cache object.
The expected behaviour would be that the endpoint was part of the hash key.

**Comment by jmdobry** [comment]
This is an interesting point. However, the data store is not supposed to know any particulars about how or from where data gets into the store. It treats all data the same. Tying an option like `endpoint` to the hash would be coupling the data store to something that is only used for a specific adapter. Your most immediate way around this would be to do: `findAll({}, { endpoint: '/endpoint2', bypassCache: true })`

**Comment by SystemParadox** [comment]
It is possible to generalise this behaviour. Consider that `endpoint` could be used to select data from several different SQL tables or views. In which case, it would indeed make sense for the "endpoint" (or whatever generic name might be more appropriate) in the query hash.

**Comment by SystemParadox** [comment]
Having said that, `js-data-http` uses `endpoint` and `js-data-sql` uses `table`: I found this pretty useful when I had a resource that used a plural table name but a singular endpoint.

**Comment by jmdobry** [comment]
Little apparent interest...closing.
