### ISSUE TITLE
unused parameter 'resourceName'

### ISSUE THREAD

**Issue by nlac** [js-data/js-data#86]
js-data.js, line 4086 - i think resourceName should be removed from the wrapper fn
```javascript
def.validate = function (resourceName, attrs, cb) {
  def.schema.validate(attrs, {
	ignoreMissing: def.ignoreMissing
  }, function (err) {
	if (err) {
	  return cb(err);
	} else {
	  return cb(null, attrs);
	}
  });
};
```

**Comment by jmdobry** [comment]
Why? `validate` is a lifecycle hook, and all lifecycle hooks use the same function signature. Changing this would be a breaking API change. I will point out that the variable should be named `resource`, not `resourceName`.

**Comment by nlac** [comment]
Oh, reading the doc about the model-lifecycle it became clear, somehow i skipped that part.. didn't realize that validate() is a hook.. thx. (looking at the code it just was strange that there's an unused parameter)
