### ISSUE TITLE
Issue with docs?

### ISSUE THREAD

**Issue by kenborge** [js-data/js-data#87]
Hi. I was wondering if there are something wrong with the docs, for instance the links under the guides section seem to be dead

**Comment by jmdobry** [comment]
Can you please be very specific as to which links are broken, so I can fix them? e.g. the url of the page that has broken links

**Comment by kenborge** [comment]
None of them was working earlier today, but they look fine now for some reason, the only one not working now is the Getting Started with js-data link under guides

**Comment by jmdobry** [comment]
What part of the world are you in? At one time there was someone in Germany who was having trouble viewing the docs. The docs are hosted by Readme.io. If there is a problem with the hosting, the most I can do is forward to the Readme.io folks the specific problem you are having. Or you can email them at support@readme.io
