### ISSUE TITLE
Wrong second argument passed to afterCreateInstance

### ISSUE THREAD

**Issue by jmdobry** [js-data/js-data#91]

**Comment by facultymatt** [comment]
Great to see this fixed so quickly! Thanks! is this same issue with [beforeCreateInstance](https://github.com/js-data/js-data/blob/master/src/datastore/sync_methods/index.js#L128) or is the attrs in this case the expected behavior?

**Comment by jmdobry** [comment]
`attrs` in the case of `beforeCreateInstance` is the expected behavior. It gives you a chance to modify `attrs` before they are used to create the instance. So perhaps the `beforeCreateInstance` hook is a good place to `addDefaultsToTarget`.
