### ISSUE TITLE
Object returned from findAll

### ISSUE THREAD

**Issue by kenborge** [js-data/js-data#94]
Angular-data supported having an object returned from a findAll. JSdata just throws an error that it did not receive an array. This makes i difficult to integrate with some APIs that have endpoints that returns single objects without ending with an ID in the path.

Ex: /message returns just a message object because there exits only one message

**Comment by jmdobry** [comment]
You should be using [actions](http://www.js-data.io/v1.5.12/docs/dsdefaults#actions) or creating your own static methods to handle this.

**Comment by kenborge** [comment]
Well there are several issue with using actions for this(and i guess it's the same with methods), like from what i can tell actions don't support endpoints with IDs, so you can't do /message/<id>/action. They also don't use the resource and caching system right? So if the endpoint returns a resource it is not put into the cache, and the query is also not added to the list of visited Urls

**Comment by kenborge** [comment]
Managed to get around the action on an ID issue by setting up a resource with a belongsTo relation but no endpoint. But is there a way to make it use the caching system

**Comment by jmdobry** [comment]
Items cannot be injected into the data store unless they have a primary key. `find` expects an object that has a primary key. `findAll` expects an array of objects that have primary keys. Non-conformative use cases like this can use various hooks (deserialize, etc.) to "fix" data before it gets injected.

**Comment by kenborge** [comment]
How about something like a config you can set on the action that indicates that a resource is returned, so the framework would then cache it? Is it not a pretty common use case that an action endpoint returns an updated resource

**Comment by jmdobry** [comment]
There are plenty of ways to accomplish this right without bogging js-data down with more options and code.

Perhaps in 2.0 with an improved architecture and url building/http module, actions can be easier and more advanced like you wish. I made a note to take a look at actions in the [2.0 issue](https://github.com/js-data/js-data/issues/68).
