### ISSUE TITLE
feat: actions should use defaultAdapter of the resource

### ISSUE THREAD

**Issue by kenborge** [js-data/js-data#95]
Currently you have to specify what adapter to use in each action definition(if not using http). But if the action is defined on a resource that sets defaultAdapter it should use the same adapter without the need to specify it again.

**Comment by jmdobry** [comment]
Question: You're using `actions` with an adapter other than `http`?

**Comment by kenborge** [comment]
Yeah, i have two adapters that inherit the http adapter, to add some api specific behaviour. So they still have an HTTP method.

**Comment by jmdobry** [comment]
That makes sense
