### ISSUE TITLE
linkAll does not change lastModified of resources

### ISSUE THREAD

**Issue by kenborge** [js-data/js-data#96]
When linkAll is run, either manually, or by the framework after a resource that is a relation has been fetched from the server, it does not modify the modified timestamp of the resources that it links to this resource. This causes the callback in bindOne/all to not be called after the link has happened.

**Comment by jmdobry** [comment]
I'm not convinced that the last modified timestamp should change. It is the defined behavior that changes are monitored for individual items. Changes in an item's relations do not count as changes in the item. An item's link to one of its relations is not part of its schema (unless your not normalizing your data at all). When an item gets linked to its relations, the item has not changed. There are no changes to save. 

You (as the user) know when items get linked. It either happens whens items are injected (after `findAll`, etc.), or when you manually create the links (`linkAll`, etc.), all of which are called by your code, s if you need to do some View-specific logic, do it there.

**Comment by jmdobry** [comment]
Yes, I'm sure the current behavior is how it should be. With the changes in #107, this definitely will never happen. 

If you're wanting to react to changes in relations, then you should observe them directly. An item's links to its relations are only there for the convenience of immediate access, no more. They won't even be enumerable with the changes in #107, though that will probably be configurable.
